### ISSUE TITLE
rocBLAS-3.3.0 leaves undefined symbol `llvm::yaml::IO::getContext()' but does not request lib to satisfy it

### ISSUE THREAD

**Issue by fuag15** [ROCmSoftwarePlatform/rocBLAS#1124]
### What is the expected behavior
- I can link libs with rocblas.so built from rocBLAS 3.3.0

### What actually happens
- I get an error in both rocALUTION-3.3.0 and miopen 

ld: /usr/lib64/librocblas.so.0.1: undefined reference to `llvm::yaml::IO::getContext()'

### How to reproduce
- build rocBLAS
attempt to link against it by building rocALUTION or miopen

### Environment
| Hardware | description |
|-----|-----|
| GPU | Vega64 |
| CPU | Threadripper |

| Software | version |
|-----|-----|
| ROCK | v3.3.0 |
| ROCR | v3.3.0 |
| HCC | v3.3.0 |
| Library | v3.3.0 |

**Comment by fuag15** [comment]
I spent this weekend digging at this in downtime and didn't get very far but here's what I've found so far. Somehow rocblas is including a symbol to llvm::yaml::IO::getContext() but not requesting any .so to satisfy it. Here's the relevant info i could find

`
ldd librocblas.so
	linux-vdso.so.1 (0x00007ffebc709000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f43412f9000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f43411ae000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f434118b000)
	libhc_am.so.3 => /usr/lib/hcc/3.3/bin/../lib/libhc_am.so.3 (0x00007f43410f8000)
	libmcwamp.so.3 => /usr/lib/hcc/3.3/bin/../lib/libmcwamp.so.3 (0x00007f4340b45000)
	libhip_hcc.so.3 => /usr/lib/hip/lib/libhip_hcc.so.3 (0x00007f4340506000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libstdc++.so.6 (0x00007f4340287000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgcc_s.so.1 (0x00007f434026d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f434009e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4346435000)
	libhsa-runtime64.so.1 => /usr/lib64/libhsa-runtime64.so.1 (0x00007f433ff36000)
	libamd_comgr.so.1 => /usr/lib64/libamd_comgr.so.1 (0x00007f433f649000)
	libhsakmt.so.1 => /usr/lib64/libhsakmt.so.1 (0x00007f433f61c000)
	libelf.so.1 => /usr/lib64/libelf.so.1 (0x00007f433f601000)
	librt.so.1 => /usr/lib64/../../lib64/librt.so.1 (0x00007f433f5f7000)
	libclangFrontendTool.so.11roc => /usr/lib/llvm/roc/lib/libclangFrontendTool.so.11roc (0x00007f433f5ee000)
	liblldELF.so.11roc => /usr/lib/llvm/roc/lib/liblldELF.so.11roc (0x00007f433f33a000)
	liblldCommon.so.11roc => /usr/lib/llvm/roc/lib/liblldCommon.so.11roc (0x00007f433f2f0000)
	libLLVMAMDGPUCodeGen.so.11roc => /usr/lib/llvm/roc/lib/libLLVMAMDGPUCodeGen.so.11roc (0x00007f433edfe000)
	libLLVMAMDGPUAsmParser.so.11roc => /usr/lib/llvm/roc/lib/libLLVMAMDGPUAsmParser.so.11roc (0x00007f433ec54000)
	libLLVMAMDGPUDisassembler.so.11roc => /usr/lib/llvm/roc/lib/libLLVMAMDGPUDisassembler.so.11roc (0x00007f433ebe6000)
	libLLVMSymbolize.so.11roc => /usr/lib/llvm/roc/lib/libLLVMSymbolize.so.11roc (0x00007f433ebcd000)
	libLLVMMCDisassembler.so.11roc => /usr/lib/llvm/roc/lib/libLLVMMCDisassembler.so.11roc (0x00007f433ebc5000)
	libclangFrontend.so.11roc => /usr/lib/llvm/roc/lib/libclangFrontend.so.11roc (0x00007f433ea1f000)
	libclangDriver.so.11roc => /usr/lib/llvm/roc/lib/libclangDriver.so.11roc (0x00007f433e7fe000)
	libclangSerialization.so.11roc => /usr/lib/llvm/roc/lib/libclangSerialization.so.11roc (0x00007f433e619000)
	libclangBasic.so.11roc => /usr/lib/llvm/roc/lib/libclangBasic.so.11roc (0x00007f433e0b4000)
	libLLVMOption.so.11roc => /usr/lib/llvm/roc/lib/libLLVMOption.so.11roc (0x00007f433e0a2000)
	libLLVMIRReader.so.11roc => /usr/lib/llvm/roc/lib/libLLVMIRReader.so.11roc (0x00007f433e099000)
	libLLVMLinker.so.11roc => /usr/lib/llvm/roc/lib/libLLVMLinker.so.11roc (0x00007f433e075000)
	libLLVMAMDGPUDesc.so.11roc => /usr/lib/llvm/roc/lib/libLLVMAMDGPUDesc.so.11roc (0x00007f433dd3c000)
	libLLVMAMDGPUInfo.so.11roc => /usr/lib/llvm/roc/lib/libLLVMAMDGPUInfo.so.11roc (0x00007f433dd37000)
	libLLVMCodeGen.so.11roc => /usr/lib/llvm/roc/lib/libLLVMCodeGen.so.11roc (0x00007f433d80d000)
	libLLVMBitWriter.so.11roc => /usr/lib/llvm/roc/lib/libLLVMBitWriter.so.11roc (0x00007f433d7c8000)
	libLLVMDebugInfoDWARF.so.11roc => /usr/lib/llvm/roc/lib/libLLVMDebugInfoDWARF.so.11roc (0x00007f433d72c000)
	libLLVMObject.so.11roc => /usr/lib/llvm/roc/lib/libLLVMObject.so.11roc (0x00007f433d619000)
	libLLVMMCParser.so.11roc => /usr/lib/llvm/roc/lib/libLLVMMCParser.so.11roc (0x00007f433d5a7000)
	libLLVMMC.so.11roc => /usr/lib/llvm/roc/lib/libLLVMMC.so.11roc (0x00007f433d4c9000)
	libLLVMCore.so.11roc => /usr/lib/llvm/roc/lib/libLLVMCore.so.11roc (0x00007f433d1b0000)
	libLLVMBinaryFormat.so.11roc => /usr/lib/llvm/roc/lib/libLLVMBinaryFormat.so.11roc (0x00007f433d18d000)
	libLLVMSupport.so.11roc => /usr/lib/llvm/roc/lib/libLLVMSupport.so.11roc (0x00007f433cfb7000)
	libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x00007f433cfa7000)
	libpci.so.3 => /usr/lib64/libpci.so.3 (0x00007f433cf98000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f433cf7e000)
	libclangCodeGen.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangCodeGen.so.11roc (0x00007f433c9a1000)
	libclangRewriteFrontend.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangRewriteFrontend.so.11roc (0x00007f433c921000)
	libclangARCMigrate.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangARCMigrate.so.11roc (0x00007f433c61c000)
	libclangStaticAnalyzerFrontend.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangStaticAnalyzerFrontend.so.11roc (0x00007f433c5aa000)
	libLLVMX86CodeGen.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMX86CodeGen.so.11roc (0x00007f433c182000)
	libLLVMX86AsmParser.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMX86AsmParser.so.11roc (0x00007f433c0e2000)
	libLLVMX86Desc.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMX86Desc.so.11roc (0x00007f433be4f000)
	libLLVMX86Info.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMX86Info.so.11roc (0x00007f433be48000)
	libLLVMLTO.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMLTO.so.11roc (0x00007f433bde3000)
	libLLVMPasses.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMPasses.so.11roc (0x00007f433bce8000)
	libLLVMDemangle.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMDemangle.so.11roc (0x00007f433bcaa000)
	libLLVMAMDGPUUtils.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMAMDGPUUtils.so.11roc (0x00007f433bc45000)
	libLLVMAsmPrinter.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMAsmPrinter.so.11roc (0x00007f433bb60000)
	libLLVMGlobalISel.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMGlobalISel.so.11roc (0x00007f433ba9f000)
	libLLVMMIRParser.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMMIRParser.so.11roc (0x00007f433ba60000)
	libLLVMSelectionDAG.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMSelectionDAG.so.11roc (0x00007f433b71d000)
	libLLVMipo.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMipo.so.11roc (0x00007f433b53a000)
	libLLVMTarget.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMTarget.so.11roc (0x00007f433b52a000)
	libLLVMScalarOpts.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMScalarOpts.so.11roc (0x00007f433b1fa000)
	libLLVMVectorize.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMVectorize.so.11roc (0x00007f433b10f000)
	libLLVMTransformUtils.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMTransformUtils.so.11roc (0x00007f433af05000)
	libLLVMAnalysis.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMAnalysis.so.11roc (0x00007f433ab05000)
	libLLVMDebugInfoPDB.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMDebugInfoPDB.so.11roc (0x00007f433aa4d000)
	libclangParse.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangParse.so.11roc (0x00007f433a927000)
	libclangSema.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangSema.so.11roc (0x00007f4339f4e000)
	libclangEdit.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangEdit.so.11roc (0x00007f4339f3d000)
	libclangAST.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangAST.so.11roc (0x00007f4339989000)
	libLLVMProfileData.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMProfileData.so.11roc (0x00007f4339919000)
	libclangLex.so.11roc => /usr/lib/llvm/roc/lib/../lib/libclangLex.so.11roc (0x00007f4339848000)
	libLLVMBitstreamReader.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMBitstreamReader.so.11roc (0x00007f433982f000)
	libLLVMAsmParser.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMAsmParser.so.11roc (0x00007f43397b7000)
	libLLVMBitReader.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMBitReader.so.11roc (0x00007f4339738000)
	libLLVMTextAPI.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMTextAPI.so.11roc (0x00007f4339709000)
	libLLVMRemarks.so.11roc => /usr/lib/llvm/roc/lib/../lib/libLLVMRemarks.so.11roc (0x00007f43396d1000)
	libtinfo.so.6 => /lib64/libtinfo.so.6 (0x00007f4339693000)
	libudev.so.1 => /lib64/libudev.so.1 (0x00007f4339660000)
	libLLVMCoverage.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMCoverage.so.11roc (0x00007f4339636000)
	libLLVMObjCARCOpts.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMObjCARCOpts.so.11roc (0x00007f4339609000)
	libLLVMCoroutines.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMCoroutines.so.11roc (0x00007f43395d4000)
	libLLVMFrontendOpenMP.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMFrontendOpenMP.so.11roc (0x00007f43395ad000)
	libLLVMInstrumentation.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMInstrumentation.so.11roc (0x00007f4339492000)
	libLLVMInstCombine.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMInstCombine.so.11roc (0x00007f4339351000)
	libclangRewrite.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libclangRewrite.so.11roc (0x00007f433933f000)
	libclangAnalysis.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libclangAnalysis.so.11roc (0x00007f4339222000)
	libclangStaticAnalyzerCheckers.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libclangStaticAnalyzerCheckers.so.11roc (0x00007f4338d9b000)
	libclangStaticAnalyzerCore.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libclangStaticAnalyzerCore.so.11roc (0x00007f4338b6d000)
	libclangCrossTU.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libclangCrossTU.so.11roc (0x00007f4338b5b000)
	libLLVMCFGuard.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMCFGuard.so.11roc (0x00007f4338b53000)
	libLLVMX86Utils.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMX86Utils.so.11roc (0x00007f4338b4b000)
	libLLVMAggressiveInstCombine.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMAggressiveInstCombine.so.11roc (0x00007f4338b33000)
	libLLVMDebugInfoCodeView.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMDebugInfoCodeView.so.11roc (0x00007f4338a69000)
	libLLVMDebugInfoMSF.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/libLLVMDebugInfoMSF.so.11roc (0x00007f4338a55000)
	libclangASTMatchers.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/../lib/libclangASTMatchers.so.11roc (0x00007f43389c2000)
	libclangIndex.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/../lib/libclangIndex.so.11roc (0x00007f4338971000)
	libclangFormat.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/../lib/../lib/libclangFormat.so.11roc (0x00007f43388d1000)
	libclangToolingCore.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/../lib/../lib/libclangToolingCore.so.11roc (0x00007f43388bd000)
	libclangToolingInclusions.so.11roc => /usr/lib/llvm/roc/lib/../lib/../lib/../lib/../lib/../lib/libclangToolingInclusions.so.11roc (0x00007f43388ac000)
`

`
readelf -d ./librocblas.so

Dynamic section at offset 0x299f758 contains 34 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so.2]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libhc_am.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libmcwamp.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libhip_hcc.so.3]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libgcc_s.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [librocblas.so.0]
 0x000000000000001d (RUNPATH)            Library runpath: [/usr/lib/hcc/3.3/bin/../lib:/usr/lib/hcc/3.3/lib]
 0x000000000000000c (INIT)               0x526000
 0x000000000000000d (FINI)               0x1f536cc
 0x0000000000000019 (INIT_ARRAY)         0x2998f08
 0x000000000000001b (INIT_ARRAYSZ)       1664 (bytes)
 0x000000000000001a (FINI_ARRAY)         0x2999588
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x200
 0x0000000000000005 (STRTAB)             0xdfa50
 0x0000000000000006 (SYMTAB)             0x34720
 0x000000000000000a (STRSZ)              3678335 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000003 (PLTGOT)             0x29a2000
 0x0000000000000002 (PLTRELSZ)           635328 (bytes)
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000017 (JMPREL)             0x48a830
 0x0000000000000007 (RELA)               0x4700b8
 0x0000000000000008 (RELASZ)             108408 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffffe (VERNEED)            0x46ff18
 0x000000006fffffff (VERNEEDNUM)         6
 0x000000006ffffff0 (VERSYM)             0x461ad0
 0x000000006ffffff9 (RELACOUNT)          523
 0x0000000000000000 (NULL)               0x0
`

`
nm ./librocblas.so | grep yaml | grep getContext
                 U _ZN4llvm4yaml2IO10getContextEv
0000000001e99db0 W _ZN7Tensile13Serialization8IOTraitsIN4llvm4yaml2IOEE10getContextERS4_
`

not sure where to go from here but this is a wierd state of affairs. I'm out of my league in linker land here but this results in both miopen and rocALUTION failing to link against rocblas with the error described above.

**Comment by bragadeesh** [comment]
Please try rocblas / rocm 3.7
