### ISSUE TITLE
Build rocBLAS failed on nvcc platform

### ISSUE THREAD

**Issue by ABadCandy** [ROCmSoftwarePlatform/rocBLAS#115]
Hi, I followed https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Setting-up-enviroment-on-NVIDIA-platform to install hip_nvcc  successfully which in /opt/rocm/hip , but https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/Build-rocBLAS-libraries-and-verification-code to  install rocBLAS faild like following:
1. The C++ compiler "/opt/rocm/hip/bin/hipcc" is not able to compile a simple
  test program.
2. nvcc fatal : Unknown option '-amdgpu-target'

my OS is ubuntu14.04 server x86_64, and when i compiler rocblas used ccmake .. it shows EMPTY CACHE,
so I can only execute cmake like this:
cmake .. -DBUILD_SHARED_LIBS=ON -DCMAKE_PREFIX_PATH=~/repos/rocBLAS/build/library-package 
-DCPACK_PACKAGE_INSTALL_PREFIX=/opt/rocm/rocblas -DHIP_ROOT=/opt/rocm/hip 
-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DHOST_TOOLCHAIN_NAME=gcc

What is the problem here? Expecting a reply !

**Comment by amcamd** [comment]
Building rocBLAS on NVIDIA platform is no longer supported. The Wiki "Setting up environment on NVIDIA platform" has been removed.

Please build rocBLAS on a machine with [ROCm](https://github.com/RadeonOpenCompute/ROCm) installed. To build rocBLAS please follow instructions in the rocBLAS Wiki.

Note that ROCm 1.6 requires Ubuntu 16.04. This requirement is listed at https://github.com/RadeonOpenCompute/ROCm .

**Comment by tingxingdong** [comment]
@kknox , shall we drop CUDA support or not?

**Comment by sunway513** [comment]
Applications still rely on hipBlas wrappers for integration on NV path. But we can recommend ppl to use hcblas wrapper instead if we decided to drop NV support on rocBlas here.

**Comment by kknox** [comment]
Until we get the rocBLAS cmake infrastructure working on cuda path, users should use the [hipBLAS marshalling](https://github.com/ROCmSoftwarePlatform/hipBLAS) library.
