### ISSUE TITLE
Can I run rocBlas on CPU?

### ISSUE THREAD

**Issue by MangalaVenakat** [ROCmSoftwarePlatform/rocBLAS#1153]
I am trying to run rocBlas on CPU:
Is there a way to provide rocblas_handle to point to CPU(host).

I see CPU(host) is not accounted with below api's
hipGetDeviceCount returns 1
hipGetDeviceProperties : returns GPU name

I am able to successfully run rocblas on GPU and now I want to run same on CPU

**Comment by bragadeesh** [comment]
rocBLAS is only designed for GPU execution and supports a list of GPUs (matching most of what rocm supports); running on cpu is not supported
