### ISSUE TITLE
Radeon VII: Incomplete device identification leading to slowness if human-readable ids are available

### ISSUE THREAD

**Issue by t-vi** [ROCmSoftwarePlatform/rocBLAS#1155]
Hi,

I debugged a performance discrepancy with the Radeon VII and it turned out that it comes from matching of device names.

### What actually happens

I have a Radeon VII (great device!) in a Linux computer.
When I don't have `pci.ids` installed, the device (hipDeviceGetName) reports itself as `Device 66af` and everything is great.
When I do have `pci.ids` installed, the device reports itself as `Vega 20 [Radeon VII]` and because this does not match the any of the provided device names in the .yaml's (typically `["Device 66a0", "Device 66a1", "Device 66a7", "Device 66af", "Vega 20"]`), it uses the fallback configuration, leading to much slowness.

### What is the expected behavior

Use Vega 20 config, i.e. provide the same speed, regardless of pci.ids installed or not.

### How to reproduce

You can reproduce e.g. using PyTorch (in the official docker from the ROCm site or on bare metal):

```python
import timeit
import torch

x = torch.randn(100, 100, device="cuda")
y = torch.randn(100, 100, device="cuda")

z = x @ y

torch.cuda.synchronize()
print(torch.cuda.get_device_name(), timeit.timeit("x @ y ; torch.cuda.synchronize()", number=1000, globals=globals()))
```

```
# with pci.ids installed
$ python3 test_mm.py
Vega 20 [Radeon VII] 0.06138330406975001
# remove entry from /usr/share/misc/pci.ids
$ python3 test_mm.py
Device 66af 0.036246914067305624
```

### Environment

Hardware: Radeon VII
CPU: Intel Core i5-7500
ROCm 3.5 from debs or the PyTorch docker from ROCm deep learning page

## Commentary

I see various options fixing this (possibly in Tensile), in decreasing preference:
- Don't use strings, but the descriptive bits of the device info.
- Have a "semifallback" matching the device name with " [...]" stripped.
- At build time, generate matching ids from pci.ids for each "Device xxxx" id.

I expect this to potentially affect other GPUs, too, grepping in the rocBLAS source:
`$ rgrep Device . | sed 's/"/\n/g' | grep '^Device [67]...$' | sort | uniq | sed 's/Device //'`
66a0 66a1 66a7 66af 6860 6861 6862 6863 6864 686c 687f 7300 731f 7380 7388 738c 7390

```
	66a0  Vega 20 [Radeon Instinct]
	66a1  Vega 20
	66a7  Vega 20 [Radeon Pro Vega 20]
	66af  Vega 20 [Radeon VII]
	6860  Vega 10 [Radeon Instinct MI25]
	6861  Vega 10 XT [Radeon PRO WX 9100]
	6862  Vega 10 XT [Radeon PRO SSG]
	6863  Vega 10 XTX [Radeon Vega Frontier Edition]
	6864  Vega 10 [Radeon Pro V340]
	686c  Vega 10 [Radeon Instinct MI25 MxGPU]
	687f  Vega 10 XL/XT [Radeon RX Vega 56/64]
	7300  Fiji [Radeon R9 FURY / NANO Series]
	731f  Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
```
some, but not all of the Vega 10 cards have matching strings.

The pci.ids is from https://pci-ids.ucw.cz/

## Final words

I might add that this cost me a lot of time and sweat to debug this, taking apart my bare metal software stack, comparing traces etc to find why it would be slower than running from within docker. So I would be really glad if we could spare others to go through the same.

(cc @mvermeulen )

**Comment by mvermeulen** [comment]
Note the following shows that the pci id database seems to have been updated:
```
prompt% docker run -it --device=/dev/dri --device=/dev/kfd --network=host --group-add=video -v /home/mev:/home/mev rocm/dev-ubuntu-18.04:3.5 /bin/bash

prompt> /opt/rocm/bin/rocminfo | grep Marketing
sh: 1: lsmod: not found
  Marketing Name:          AMD Ryzen Threadripper 1950X 16-Core Processor
  Marketing Name:          Device 66af                        

prompt> apt update && apt install -y pciutils

prompt> /opt/rocm/bin/rocminfo | grep Marketing
sh: 1: lsmod: not found
  Marketing Name:          AMD Ryzen Threadripper 1950X 16-Core Processor
  Marketing Name:          Vega 20                            

prompt> update-pciids
Downloaded daily snapshot dated 2020-06-24 03:15:01

prompt> /opt/rocm/bin/rocminfo | grep Marketing
sh: 1: lsmod: not found
  Marketing Name:          AMD Ryzen Threadripper 1950X 16-Core Processor
  Marketing Name:          Vega 20 [Radeon VII]             
```

**Comment by bragadeesh** [comment]
The device identification and logic around solution(gpu kernel) selection is changing in a refactor of Tensile; the new logic only uses gfx generation and not the device strings, and would be stable and not sensitive to the above issues. This change is planned for rocm release very soon (3.7 tentative) and should solve the problem.

**Comment by t-vi** [comment]
@bragadeesh Awesome! Is there any way to get a pre-release? (Compiling Tensile and rocBLAS would be within reach.)

**Comment by bragadeesh** [comment]
@t-vi 
I am expecting the master branch of rocblas (and the associated Tensile version) to be updated sometime next week, which should be something good to try. I can provide an update as we get closer.

**Comment by t-vi** [comment]
Cool, thank you!

**Comment by bragadeesh** [comment]
Latest master is a good candidate to try for the new method of device selection

**Comment by bragadeesh** [comment]
Closing, this feature is enabled in rocm 3.7 which has been released.
