### ISSUE TITLE
[Build Error] [CMake] Cannot find hip

### ISSUE THREAD

**Issue by acxz** [ROCmSoftwarePlatform/rocBLAS#1156]
### What is the expected behavior
- Including rocblas in a cmake project like `find_package(rocblas)` should be successful.

### What actually happens
- When using find_package(rocblas), it fails since it cannot find hip, even though hip is installed.

```
CMake Error at /usr/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findhip.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "hip", but
  CMake did not find one.

  Could not find a package configuration file provided by "hip" with any of
  the following names:

    hipConfig.cmake
    hip-config.cmake

  Add the installation prefix of "hip" to CMAKE_PREFIX_PATH or set "hip_DIR"
  to a directory containing one of the above files.  If "hip" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  /opt/rocm/rocblas/lib/cmake/rocblas/rocblas-config.cmake:89 (find_dependency)
  cmake/public/LoadHIP.cmake:131 (find_package)
  cmake/public/LoadHIP.cmake:169 (find_package_and_print_version)
  cmake/Dependencies.cmake:995 (include)
  CMakeLists.txt:411 (include)
```

FindHIP.cmake is installed on the system but Findhip.cmake is not.

### How to reproduce
- Call `find_package(rocblas)` in a cmake project.

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v3.5.1 |
| ROCR | v3.5.0 |
| HCC | N/A |
| Library | v0.0 | ???
| ROCBLAS | v3.5.0 |

Downstream issue: https://github.com/pytorch/pytorch/issues/41886

**Comment by acxz** [comment]
Closing this issue since this does not directly pertain to this repo but rather the lack of functionality in `FindHIP.cmake` in the HIP package.

**Comment by amcamd** [comment]
See comments and discussion for issue 303 in rocFFT (https://github.com/ROCmSoftwarePlatform/rocFFT/issues/303).

**Comment by TorreZuk** [comment]
I will close this issue tomorrow as the find_package(rocblas) is now demonstrated in  https://github.com/ROCmSoftwarePlatform/rocBLAS-Examples/commit/a5b3b1e4683f41c48344b637cebcbbb7ca348e84 .   Note CMAKE_PREFIX_PATH may need to be set to find the rocBLAS and/or hip cmake config files.    find_package( hip ) with lowercase hip is the form used within rocBLAS as is the prescribed form to be used by downstream clients of hip.   The PR https://github.com/ROCmSoftwarePlatform/rocBLAS/pull/1157  be closed shortly as well as these changes are not desired.
