### ISSUE TITLE
Bug in dgmm

### ISSUE THREAD

**Issue by mkstoyanov** [ROCmSoftwarePlatform/rocBLAS#1160]
### What is the expected behavior
- dgmm should compute the dense times diagonal matrix product

### What actually happens
- there is a typo in the method and A and X are added instead of being multiplied

### How to reproduce
- see https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/library/src/blas3/rocblas_dgmm.hpp on lines 34 and 38
- `C[tx + ldc * ty] = A[tx + lda * ty] + X[ty * incx];` should be `C[tx + ldc * ty] = A[tx + lda * ty] * X[ty * incx];`

### Environment
Current state of the repo as of Aug 10, 2020.

**Comment by TorreZuk** [comment]
Thanks Miroslav for catching and clearly reporting the problem.  This issue should now be fixed in the master branch by taking commit 6d9136819aeaedac5a41d067e8a3b58c291f99c5 made on Aug 13, 2020.  It is expected to be in the ROCm 3.8 release.  Let us know if you have further concerns.

**Comment by mkstoyanov** [comment]
Thanks @TorreZuk it seems fixed now. We should be able to close the issue.
