### ISSUE TITLE
build error with 3.8.x

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/rocBLAS#1168]
### What is the expected behavior
-
be able build according to instruction
### What actually happens
-
build failed.
### How to reproduce
-
either install -i or install -id failing:
(see attached build log)
[roc-blas-build.log](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/5345601/roc-blas-build.log)

### Environment
Ubuntu 1804
| Hardware | description |
|-----|-----|
| GPU | device string |
Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 [Radeon Instinct MI25 MxGPU]
| CPU | device string |
model name      : Intel Xeon Processor (Skylake, IBRS)

| Software | version |
3.8.x
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by xuhuisheng** [comment]
please check whether there is /opt/rocm/llvm/bin/clang exists?
The building of rocBLAS need llvm and hip installation.

**Comment by TorreZuk** [comment]
Yes please ensure you have the prerequisites installed: https://github.com/ROCmSoftwarePlatform/rocBLAS#prerequisites
If you installed rocm-dkms over an earlier install look for a broken symlink /opt/rocm and ensure it points to a valid installation, e.g. rocm->/opt/rocm-3.8.0

**Comment by cgmb** [comment]
The link to the ROCm install instructions in the rocBLAS README is redirecting to the ROCm docs homepage. It's still pretty easy to find the install instructions from there, but we might want to update that.

Just for convenience, here's a direct link to the ROCm install instructions for Ubuntu: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu

**Comment by gggh000** [comment]
There is nowhere in the rocBLAS readme about prereq, while I am sweating through llvm, ran into much issues and built the release version including lld,clang built and now getting this error:


    "/opt/rocm/bin/hipcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeTmp

    Run Build Command:"/usr/bin/make" "cmTC_2e761/fast"
    /usr/bin/make -f CMakeFiles/cmTC_2e761.dir/build.make CMakeFiles/cmTC_2e761.dir/build
    make[1]: Entering directory '/root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_2e761.dir/testCXXCompiler.cxx.o
    /opt/rocm/bin/hipcc     -o CMakeFiles/cmTC_2e761.dir/testCXXCompiler.cxx.o -c /root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeTmp/te    stCXXCompiler.cxx
    Linking CXX executable cmTC_2e761
    /usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2e761.dir/link.txt --verbose=1
    /opt/rocm/bin/hipcc       CMakeFiles/cmTC_2e761.dir/testCXXCompiler.cxx.o  -o cmTC_2e761
    /usr/bin/ld: cannot find -lclang_rt.builtins-x86_64
    clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
    CMakeFiles/cmTC_2e761.dir/build.make:97: recipe for target 'cmTC_2e761' failed
    make[1]: *** [cmTC_2e761] Error 1
    make[1]: Leaving directory '/root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeTmp'
    Makefile:126: recipe for target 'cmTC_2e761/fast' failed
    make: *** [cmTC_2e761/fast] Error 2




  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:29 (project)


-- Configuring incomplete, errors occurred!
See also "/root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeOutput.log".
See also "/root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeError.log".
+ check_exit_code 1
+ ((  1 != 0  ))
+ exit 1
root@sriov-guest:~/ROCm/rocBLAS# clang-11
clang-11: command not found
root@sriov-guest:~/ROCm/rocBLAS# find /opt/rocm-3.8.0/ -name clang-11
/opt/rocm-3.8.0/llvm/bin/clang-11
root@sriov-guest:~/ROCm/rocBLAS# ls -l /opt/rocm-3.8.0/llvm/bin/clang-11
-rwxr-xr-x 1 root root 139194848 Oct 14 15:30 /opt/rocm-3.8.0/llvm/bin/clang-11
root@sriov-guest:~/ROCm/rocBLAS#

**Comment by TorreZuk** [comment]
You shouldn't have to build llvm as the llvm build to use will be in the ROCm platform installation.
By prerequisites the ROCm platform is just the rocm-dkms installation which is described https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu
Remove old installation and force remove any /opt/rocm that aren't purged, following instructions at the link.  After
sudo apt install rocm-dkms    
Ensure there is a symlink from /opt/rocm to the new installation.
Your error message:
/usr/bin/ld: cannot find -lclang_rt.builtins-x86_64  suggests a toolchain issue, so remove any custom clang you have from your path before building.  That builtins lib should be in /opt/rocm/llvm/lib/clang/X.Y.Z/lib/linux/ so mixing compilers/linkers could be your issue.

**Comment by cgmb** [comment]
This is my script for installing ROCm on a fresh Ubuntu 18.04 machine, based on the rocmdocs installation guide Torre linked (note that it ends with a reboot):
```
sudo su -
apt update
apt install libnuma-dev wget gnupg
wget -q -O - https://repo.radeon.com/rocm/rocm.gpg.key | apt-key add -
echo 'deb [arch=amd64] http://repo.radeon.com/rocm/apt/debian/ xenial main' > /etc/apt/sources.list.d/rocm.list
apt update
apt install rocm-dkms
reboot
```

Then for building rocBLAS:
```
sudo apt install git gfortran
git clone https://github.com/ROCmSoftwarePlatform/rocBLAS.git -b rocm-3.8.0
cd rocBLAS
./install.sh -id
```

On a clean install, that should cover everything you need.

**Comment by gggh000** [comment]
there is no custom toolchain installed. rock-dkms did not install llvm (did not see in /opt/rocm-3.8.x/ the llvm folder, completely missing. so i had to build and install llvm http://github.com/RadeonOpenCompute/llvm-project.

That way, I managed to get ahead by ridding several lld missing errors and now stuck now at  -lclang_rt.builtins-x86_64 error message.

**Comment by cgmb** [comment]
roc*k*-dkms is the ROCm kernel driver, but roc*m*-dkms is the full ROCm development stack, which includes the rock kernel driver, llvm-amdgpu and other such development tools.

**Comment by cgmb** [comment]
I discovered debtree today and am quite enjoying using it. I used it to produce this dependency diagram, may help clarify the relationship between the rocm-dkms and rock-dkms packages:

![rocm-dkms-partial-tree](https://user-images.githubusercontent.com/4886803/96190465-870a9880-0eff-11eb-8583-5ffc8f5915e1.png)

**Comment by gggh000** [comment]
I have the installation through -id switch working. The build error was due to fact it was in virtual guest machine. 

Now I tried building -c (client) build and getting following error:

./install -c
CMake Warning at /opt/rocm/share/rocm/cmake/ROCMChecks.cmake:37 (message):
  The toolchain variable 'CMAKE_CXX_FLAGS' is modified in the CMakeLists.txt.
Call Stack (most recent call first):
  clients/benchmarks/CMakeLists.txt:9999 (rocm_check_toolchain_var)
  clients/benchmarks/CMakeLists.txt:18 (set)


-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   program_options
CMake Error at clients/benchmarks/CMakeLists.txt:38 (find_package):
  Could not find a package configuration file provided by "cblas" with any of
  the following names:

    cblasConfig.cmake
    cblas-config.cmake

  Add the installation prefix of "cblas" to CMAKE_PREFIX_PATH or set
  "cblas_DIR" to a directory containing one of the above files.  If "cblas"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/root/ROCm/rocBLAS/build/release/CMakeFiles/CMakeOutput.log".
+ check_exit_code 1
+ ((  1 != 0  ))
+ exit 1
root@ixt-rack-70:~/ROCm/rocBLAS#

**Comment by cgmb** [comment]
`-d` only installs the dependencies for the options you've selected. The clients require additional dependencies, so use `./install.sh -cd` the first time you build the clients.

**Comment by gggh000** [comment]
OK, I installed with -cd option and worked. Previously i used -d so thought may not be necessary for client option.

**Comment by gggh000** [comment]
i think this can be closed. thanks.,

**Comment by cgmb** [comment]
Nice. Glad to hear it's working for you!
