### ISSUE TITLE
Is this the AMD alternative of cudnn? 

### ISSUE THREAD

**Issue by LifeIsStrange** [ROCmSoftwarePlatform/rocBLAS#1174]
If so I think that should be said in the Readme. 
Also Cudnn claim each year to make performance breakthrough, I hope that rocBLAS keep up in performance, you should at least have the transparency to show performance benchmarcks results vs Cudnn. 
As a potential CDNA buyer, I won't buy it until there is convincing deep learning benchmarcks.

**Comment by bragadeesh** [comment]
Please see: https://github.com/ROCmSoftwarePlatform/MIOpen
