### ISSUE TITLE
Poor performance of trmm function

### ISSUE THREAD

**Issue by AdhocMan** [ROCmSoftwarePlatform/rocBLAS#1175]
We are working on a computational material science code and noticed extremely poor performance of the `rocblas_ztrmm` function compared to cuBLAS. This is the major factor in poor performance of our application on AMD GPUs.

### What is the expected behavior
- Performance somewhere close to cuBLAS.

### What actually happens
- When comparing a MI50 with rocBLAS and a Tesla P100 with cuBLAS, rocBLAS is about 200 times slower. 

### How to reproduce
Here are sample programs for rocBLAS and cuBLAS with a typical problem size for our application (.txt extension to allow direct upload):
[bench_trmm_hip.cpp.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/5495578/bench_trmm_hip.cpp.txt)
[bench_trmm_cuda.cpp.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/5495579/bench_trmm_cuda.cpp.txt)

### Environment
| Hardware | description |
|-----|-----|
| GPU | AMD Radeon Instinct MI50 |
| CPU | AMD EPYC 7501 |

| Software | version |
|-----|-----|
| ROCm | v3.9.0 |

**Comment by amcamd** [comment]
Thank you for providing test code to show the poor performance of rocblas_ztrmm. We will work on improving performance or rocblas_ztrmm.

**Comment by AdhocMan** [comment]
This seems to have been solved in the recent ROCm 4.2.0 release, thanks.
Performance is much better now and it's no longer a bottleneck for our application.
