### ISSUE TITLE
when it will use stdc++17

### ISSUE THREAD

**Issue by kylin0061** [ROCmSoftwarePlatform/rocBLAS#1180]
### What is the expected behavior
- I see rocBLAS is using stdC++14,so  I can't compile it on the aarch64. so I want to use stdC++17 to compile it .

### What actually happens
-

### How to reproduce
-

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by bragadeesh** [comment]
rocBLAS has dependencies on several other projects and also need to work with a list of compilers; At this time C++14 is the best support available given those constraints; No plans to move to c++17 at this time.
