### ISSUE TITLE
Poor performance of D(Z)syrkx

### ISSUE THREAD

**Issue by elbriggs** [ROCmSoftwarePlatform/rocBLAS#1184]
### What is the expected behavior
- For certain types of matrix ops a D(Z)gemm call can be replaced with D(Z)syrkx. Using the cuda version on Summit at ORNL D(Z)syrkx is considerably faster than D(Z)gemm in the RMG electronic structure code.

### What actually happens
- On a workstation (Epyc7502 with dual Radeon VII's) using syrkx is roughly twice as slow as using dgemm. System is running Ubuntu 20.0.4 with ROCM4.0 (hipblas routines are actually called).

### How to reproduce
- Easily reproduced by running RMG. If this is not a known issue I can try to generate a standalone test case.

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx906 |
| CPU |AMD EPYC 7502P 32-Core Processor |

| Software | version |
|-----|-----|
| ROCK | v4.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Hipblas | 0.38.0.457-rocm-rel-4.0-23-400d551  |

**Comment by amcamd** [comment]
Thank you for reporting this D(Z)syrkx performance problem. We will look into improving D(Z)syrkx performance. 

Can you supply the D(Z)syrkx arguments used by your RMG electronic structure code. One way to do this would be to enable rocBLAS logging by setting the environment variable ROCBLAS_LAYER to the value 2, then running your application. There is more information on logging at https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/docs/source/logging.rst .

**Comment by elbriggs** [comment]
There were thousands of syrkx calls over the course of the run but only two unique sizes that I have included below. Within the larger code if I replace the syrkx call with gemm it runs about twice as fast. I don't know if it's helpful but this job used 32 MPI procs with 16 assigned to each Radeon VII.

./rocblas-bench -f syrkx -r f64_r --uplo L --transposeA T -n 1536 -k 8192 --alpha 0.0734285 --lda 8192 --ldb 8192 --beta 0 --ldc 1536
./rocblas-bench -f syrkx -r f64_r --uplo L --transposeA T -n 2048 -k 8192 --alpha 0.0734285 --lda 8192 --ldb 8192 --beta 0 --ldc 2048

**Comment by amcamd** [comment]
Thank you, we will aim to improve D(Z)syrkx performance for these sizes.

**Comment by amcamd** [comment]
A new algorithm for syrkx is checked into the develop and master branches of rocBLAS. It will be in the next release of rocBLAS.

For the sizes in this issue, the performance measured on MI100 for the old and new dsyrkx is in the table below.


|     N   |      K     |  old GFlop/sec  |  new GFlop/sec  |
|-------|---------|------------------|-------------------|
| 1536  |   8192  |         935           |       1736             |
| 2048  |   8192  |         987           |       2507             |
