### ISSUE TITLE
FP16 is much slower than FP32

### ISSUE THREAD

**Issue by qianqing13579** [ROCmSoftwarePlatform/rocBLAS#1186]
When I use migraphx(https://github.com/ROCmSoftwarePlatform/AMDMIGraphX) to do inference on Rocm,I find that FP16 is much slower than FP32 on VGG network when batchsize is set to 1. I try to do profiling and find that the function rocblas_gemm_ex is the reason. But I do not know why.

**Comment by TorreZuk** [comment]
rocblas_gemm_ex functions will use different kernels depending on your arguments and your card all with varying performance.   If you set the environment variable
export ROCBLAS_LAYER=2
it may indicate the parameter types being used for the rocblas_gemm_ex function call.
https://rocblas.readthedocs.io/en/latest/functions.html#rocblas-gemm-ex-batched-strided-batched
Additional mixed precision optimized kernels are being added so you can expect performance improvements in future releases.
If you provide some more details we may be able to advise further, but you can also consult directly the MIGraphX issue board to get advice on performance tuning if you can't follow their documentation.
Thanks.

**Comment by qianqing13579** [comment]
I set ROCBLAS_LAYER=3 on VGG network with batchsize=1, and I see a lot of information as follows.
FP32:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7fadbf200000,f32_r,4096,0x7fb655204000,f32_r,25088,1,0x7fb655266000,f32_r,4096,0x7fb655266000,f32_r,4096,f32_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f32_r --lda 4096 --b_type f32_r --ldb 25088 --beta 1 --c_type f32_r --ldc 4096 --d_type f32_r --ldd 4096 --compute_type f32_r --algo 0 --solution_index 0 --flags 0

FP16:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7f40aa600000,f16_r,4096,0x7f40a0a047d0,f16_r,25088,1,0x7f40a0a027d0,f16_r,4096,0x7f40a0a027d0,f16_r,4096,f16_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f16_r --lda 4096 --b_type f16_r --ldb 25088 --beta 1 --c_type f16_r --ldc 4096 --d_type f16_r --ldd 4096 --compute_type f16_r --algo 0 --solution_index 0 --flags 0

**Comment by qianqing13579** [comment]
@TorreZuk 
I set ROCBLAS_LAYER=3 on VGG network with batchsize=1, and I see a lot of information as follows.
FP32:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7fadbf200000,f32_r,4096,0x7fb655204000,f32_r,25088,1,0x7fb655266000,f32_r,4096,0x7fb655266000,f32_r,4096,f32_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f32_r --lda 4096 --b_type f32_r --ldb 25088 --beta 1 --c_type f32_r --ldc 4096 --d_type f32_r --ldd 4096 --compute_type f32_r --algo 0 --solution_index 0 --flags 0

FP16:
rocblas_gemm_ex,111,111,4096,1,25088,1,0x7f40aa600000,f16_r,4096,0x7f40a0a047d0,f16_r,25088,1,0x7f40a0a027d0,f16_r,4096,0x7f40a0a027d0,f16_r,4096,f16_r,0,0,0
./rocblas-bench -f gemm_ex --transposeA N --transposeB N -m 4096 -n 1 -k 25088 --alpha 1 --a_type f16_r --lda 4096 --b_type f16_r --ldb 25088 --beta 1 --c_type f16_r --ldc 4096 --d_type f16_r --ldd 4096 --compute_type f16_r --algo 0 --solution_index 0 --flags 0

**Comment by TorreZuk** [comment]
Thanks for your problem sizes and parameters.  Can you provide the version you are using and your graphics card?

**Comment by jianlongf** [comment]
I found the same problem recently by comparing fp32 with fp16 performance in same parameters.  
Firstly,  I got rocblam-bench commands through set ROCBLAS_LAYER=2. Then I run them by rocblas-bench (I builded it by source). 
The example is below. As you can see, fp32 is better than fp16 in the size, but it doesn't always.(**I noticed --compute_type f32_r in fp16 commands. can I change it to fp16? Do it degrade accuracy of model?**)

./rocblas-bench -f gemm -r f32_r --transposeA T --transposeB N -m 4096 -n 1 -k 240 --alpha 1 --lda 240 --ldb 240 --beta 0 --ldc 4096
Query device success: there are 1 devices
-------------------------------------------------------------------------------
Device ID 0 : Vega 20
with 17.2 GB memory, max. SCLK 1801 MHz, max. MCLK 1000 MHz, compute capability 9.0
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------

transA,transB,M,N,K,alpha,lda,ldb,beta,ldc,rocblas-Gflops,us
T,N,4096,1,240,1.0000000,240,240,0.0000000,4096,79.2774194,24.8000000

./rocblas-bench -f gemm_ex --transposeA T --transposeB N -m 4096 -n 1 -k 240 --alpha 1 --a_type f16_r --lda 240 --b_type f16_r --ldb 240 --beta 0 --c_type f16_r --ldc 4096 --d_type f16_r --ldd 4096 --compute_type f32_r --algo 0 --solution_index 0 --flags 0
Query device success: there are 1 devices
-------------------------------------------------------------------------------
Device ID 0 : Vega 20
with 17.2 GB memory, max. SCLK 1801 MHz, max. MCLK 1000 MHz, compute capability 9.0
maxGridDimX 2147483647, sharedMemPerBlock 65.5 KB, maxThreadsPerBlock 1024, warpSize 64
-------------------------------------------------------------------------------

transA,transB,M,N,K,alpha,lda,ldb,beta,ldc,rocblas-Gflops,us
T,N,4096,1,240,1.0000000,240,240,0.0000000,4096,31.4070288,62.6000000

And My model has 6 size gemm size and the collective result is as below:
**m/n/k**
1. 4096/1/240
   1. fp32 26.6000000
   2. fp16 70.2000000 us
2. 4096/1/1024
   1. fp32 89.7000000
   2. fp16 75.6000000
3. 4096/1/2048
   1. fp32 258.5000000 us
   2. fp16 122.4000000 us
4. 1280/1/320
   1. fp32 16.6000000 us
   2. fp16 57.4000000 us
5. 512/1/1344
   1. fp32 20.3000000 us
   2. fp16 220.3000000 us
6. 29/1/512
   1. fp32 51.9000000 us
   2. fp16 86.2000000 us

**Comment by qianqing13579** [comment]
@TorreZuk 
I use rocm3.3. I use rocminfo command,and the output is as follows:
  Name:                    gfx906                             
  Marketing Name:          Vega 20                            
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          4096(0x1000)                       
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    9                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26273(0x66a1)                      
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1600                               
  BDFID:                   37120                              
  Internal Node ID:        9                                  
  Compute Unit:            60                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16760832(0xffc000) KB              
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx906          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32

**Comment by TorreZuk** [comment]
@jianlongf yes performance will vary by size and rocBLAS version and card.   Yes you can change the types but some versions may report unsupported type.   It depends on your model whether you can get valid results with lower precision accumulation, I can't make general statements.  You can experiment.

**Comment by TorreZuk** [comment]
@qianqing13579 if possible updating to a newer rocm may provide better performance.  Additional precision support may get added and some performance optimizations may be made in any rocBLAS release, see https://rocblas.readthedocs.io/en/latest/ and earlier release notes to see changes.  My advice is to get the latest and experiment with sizes to see what performs best for you. Please consult the AMDMIGraphX board or further performance advice as that constrains your calls into rocBLAS.    I hope this information suffices so I'll close this issue.

**Comment by qianqing13579** [comment]
@TorreZuk 
I use Rocm4.0 instead of Rocm3.3,and I find that FP16 is much faster than FP32.Thanks!

**Comment by TorreZuk** [comment]
Thank you for upgrading to ROCm 4.0. It is good to see ROCm 4.0 provides improved performance.  We will review the problem sizes mentioned in this issue going forward.
