### ISSUE TITLE
build clients-only error

### ISSUE THREAD

**Issue by frank2679** [ROCmSoftwarePlatform/rocBLAS#1187]
### What is the expected behavior
I have installed ROCm and rocBLAS according to [instructions](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/docs/source/install.rst).
I want to build clients and run bench/tests, which should be like [this](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/docs/source/clients.rst).

### What actually happens
when I build clients, error happens as follows: 

```bash
CMake Error at clients/benchmarks/CMakeLists.txt:7 (find_package):
  Could not find a package configuration file provided by "cblas" with any of
  the following names:

    cblasConfig.cmake
    cblas-config.cmake

  Add the installation prefix of "cblas" to CMAKE_PREFIX_PATH or set
  "cblas_DIR" to a directory containing one of the above files.  If "cblas"
  provides a separate development package or SDK, be sure it has been
  installed.
```

### How to reproduce
-
```
./install.sh --clients-only
```

### Environment
| Hardware | description |
|-----|-----|
|GPU |GeForce RTX 2070 SUPER |

| Software | version |
|-----|-----|
| OS | Ubuntu 18.04 |

**Comment by TorreZuk** [comment]
You are missing the dependencies as I expect you built the library without clients when you installed dependencies.
You can try with the flags for dependencies and clients only, 
install.sh -d --clients-only 
if that fails do the full dependency and library build with clients using: install.sh  -dc

**Comment by frank2679** [comment]
Thanks for reply. 
Since I interrupt the installation "./install.sh -d" yesterday, now, when I run "./install.sh -d --clients-only" or "./install.sh -dc", Error happens like: 
```
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libomp-dev : Depends: libomp5 (= 5.0.1-1)
E: Unable to correct problems, you have held broken packages.
+ check_exit_code 100
+ ((  100 != 0  ))
+ exit 100
```

**Comment by TorreZuk** [comment]
Did you just try reinstall.
apt install libomp5
General checks:
sudo apt-get clean && sudo apt-get update
Otherwise you'll have to google repairing broken packages as there are multiple routes.

**Comment by frank2679** [comment]
At last, I build the rocBLAS with sources. In previous, I installed rocblas with `apt install rocblas`, and build clients with `install.sh --clients-only`. But the two versions don't match. So I remove rocblas and reinstall it by `install.sh -i`. And since my PC has problems connecting with github accidently, I turn off the tensile. Finally, it seems built successfully.
But error occurs when I run `./rocblas-test --gtest_filter=*quick*`, which is as follows
```bash
rocBLAS version: 2.39.0.3155-8a11982c

Query device error: cannot get device count
Error: invalid device ID. There may not be such device ID.
```
What's the problem? Does it mean my ROCm platform is not ok?
Thanks for your help.

**Comment by TorreZuk** [comment]
It looks like your rocBLAS version is very new, the branch are you building seems to be develop.
What is the version of rocm that you installed (4.0 ?)  as it should match the rocBLAS branch, so use rocm-4.0.x branch if you have installed rocm 4.0, or whatever version use matching branch or rocBLAS to release of rocm.
This is the most likely cause, sorry you may have to rebuild again using an older rocBLAS branch.

**Comment by frank2679** [comment]
I reinstalled rocBLAS to match ROCm 4.0.x, but problem remains. 
I recall that when I installed ROCm, error occues as follows, it may be the reason. 
I followed the instuction: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu. 

But how to install ROCm correctly? 

```
$ /opt/rocm/bin/rocminfo
ROCk module is NOT loaded, possibly no GPU devices
Unable to open /dev/kfd read-write: No such file or directory
frank is not member of "video" group, the default DRM access group. Users must be a member of the "video" group or another DRM access group in order for ROCm applications to run successfully.
hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.
```

**Comment by frank2679** [comment]
> 
> 
> I reinstalled rocBLAS to match ROCm 4.0.x, but problem remains.
> I recall that when I installed ROCm, error occues as follows, it may be the reason.
> I followed the instuction: https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu.
> 
> But how to install ROCm correctly?
> 
> ```
> $ /opt/rocm/bin/rocminfo
> ROCk module is NOT loaded, possibly no GPU devices
> Unable to open /dev/kfd read-write: No such file or directory
> frank is not member of "video" group, the default DRM access group. Users must be a member of the "video" group or another DRM access group in order for ROCm applications to run successfully.
> hsa api call failure at: /src/rocminfo/rocminfo.cc:1142
> Call returned HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events.
> ```
another test output as follows
```
$ /opt/rocm/opencl/bin/clinfo
Number of platforms:                             2
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 1.2 CUDA 11.1.70
  Platform Name:                                 NVIDIA CUDA
  Platform Vendor:                               NVIDIA Corporation
  Platform Extensions:                           cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_copy_opts cl_nv_create_buffer cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_device_uuid
  Platform Profile:                              FULL_PROFILE
  Platform Version:                              OpenCL 2.0 AMD-APP (3212.0)
  Platform Name:                                 AMD Accelerated Parallel Processing
  Platform Vendor:                               Advanced Micro Devices, Inc.
  Platform Extensions:                           cl_khr_icd cl_amd_event_callback


  Platform Name:                                 NVIDIA CUDA
Number of devices:                               1
  Device Type:                                   CL_DEVICE_TYPE_GPU
  Vendor ID:                                     10deh
  Max compute units:                             40
  Max work items dimensions:                     3
...
```

**Comment by frank2679** [comment]
sorry, forget the new output. 
```
$ ./rocblas-test
rocBLAS version: 2.32.0.2844-cc18d25f

Query device error: cannot get device count
Error: invalid device ID. There may not be such device ID.
```

**Comment by TorreZuk** [comment]
sudo usermod -a -G video  $LOGNAME  && sudo reboot 
If on Ubuntu20: 
sudo usermod -a -G render  $LOGNAME  && sudo reboot
If it still fails, then you may have to reinstall rocm as the install may be messed up due to the permissions.

**Comment by TorreZuk** [comment]
This user group information is in the section Prerequisites above the Supported OS section that you linked to.   I'll assume you managed to get it working if I don't hear back and will close this issue in a couple days.

**Comment by TorreZuk** [comment]
@frank2679 did you add the video group permissions and still have that error?
If so can you run /opt/rocm/bin/rocm_agent_enumerator to confirm you have a AMD graphics card installed that is capable of being used with rocBLAS.   If you only have an NVIDIA card for now you could use the hipBLAS library built with a CUDA backend, as the clients within rocBLAS only support AMD cards.  However, this would not test your rocBLAS build or install.   See https://github.com/ROCmSoftwarePlatform/hipBLAS for details on building the hipBLAS library.
