### ISSUE TITLE
Build error with GCC11

### ISSUE THREAD

**Issue by grinness** [ROCmSoftwarePlatform/rocBLAS#1191]
Hi, 

I am on Arch (x86-64), I have compiled successfully the roc-dev metapackage, however rocblas  does not compile successfully:

In file included from /opt/rocm/llvm/lib/clang/12.0.0/include/cuda_wrappers/complex:75:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/complex:703:7: error: __host__ __device__ function '__failed_assertion' cannot overload __host__ function '__failed_assertion'
      __glibcxx_assert( __rho >= 0 );
      ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++config.h:754:5: note: expanded from macro '__glibcxx_assert'
    __glibcxx_assert_1(_Condition)        \
    ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++config.h:743:13: note: expanded from macro '__glibcxx_assert_1'
       void __failed_assertion();       \
            ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/bits/atomic_base.h:266:7: note: previous declaration is here
      __glibcxx_assert(__b != memory_order_consume);
      ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++config.h:754:5: note: expanded from macro '__glibcxx_assert'
    __glibcxx_assert_1(_Condition)        \
    ^
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/x86_64-pc-linux-gnu/bits/c++config.h:743:13: note: expanded from macro '__glibcxx_assert_1'
       void __failed_assertion();       \
            ^
1 error generated when compiling for host.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:272: Tensile/lib/CMakeFiles/TensileHost.dir/source/llvm/YAML.cpp.o] Error 1
1 error generated when compiling for host.
make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:286: Tensile/lib/CMakeFiles/TensileHost.dir/source/llvm/Loading.cpp.o] Error 1
make[2]: Leaving directory '/home/marco/.cache/yay/rocblas/src/build'
make[1]: *** [CMakeFiles/Makefile2:205: Tensile/lib/CMakeFiles/TensileHost.dir/all] Error 2
make[1]: Leaving directory '/home/marco/.cache/yay/rocblas/src/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/home/marco/.cache/yay/rocblas/src/build'
==> ERROR: A failure occurred in build().
    Aborting...
error making: rocblas

the same error is reported here by another user:
https://github.com/rocm-arch/rocm-arch/issues/606

the comment suggest that this is an issue with gcc 11:

gcc --version                                                    
gcc (GCC) 11.1.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### How to reproduce
I am using AUR PKGBUILD:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocblas

The PKGBUILD points here:

to reproduce:
yay -S rocblas

**Comment by yxsamliu** [comment]
that's a known issue of clang with gcc11.1. it has been fixed in clang trunk https://reviews.llvm.org/rG9a75c06cd9d94d3fd13c47a01044da97b98cf26b but is not in ROCm release yet.

gcc10 should work.

**Comment by grinness** [comment]
Hi, 

Thanks for your reply

I am trying to recompile with gcc10, but the complexity of the interdependent relationships between packages is a considerable issue, ie:

I have re-compiled with gcc10 rocblas  (-DCMAKE_C_COMPILER=gcc-10) and llvm-amd (-DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10), but rocblas still trows an error as Clang12 (in rocm/llvm )includes gcc-11 stuff:

In file included from /opt/rocm/llvm/lib/clang/12.0.0/include/cuda_wrappers/complex:75:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/complex:703:7: error: __host__ __device__ function '__failed_assertion' cannot overload __host__ function '__failed_assertion'
      __glibcxx_assert( __rho >= 0 );

Any advice? 

Cheers
G.

**Comment by yxsamliu** [comment]
can you paste the output of `/opt/rocm/llvm/bin/clang -v` ? there may be multiple libstdc++

**Comment by grinness** [comment]
Sure, output as below:

pt/rocm/llvm/bin/clang -v                                          ✔ ╱ marco@gemini 
clang version 12.0.0 (https://aur.archlinux.org/llvm-amdgpu.git 1a836b482400feabae8a760f8817796ae46b560e)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/llvm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/11.1.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0
Selected GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
Found HIP installation: /opt/rocm, version 4.2.21204-5182933

**Comment by yxsamliu** [comment]
since you have both gcc11.1 and gcc10.2, clang chooses gcc11.1. you need to uninstall gcc11.1.

**Comment by grinness** [comment]
Hi yxsamliu,

from what I can see, uninstalling gcc11 is not really straightforward in Arch due to its dependencies and general structure of distro as package gcc  provides gcc11:

sudo pacman -R gcc                                            
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing gcc breaks dependency 'gcc' required by clang
:: removing gcc breaks dependency 'gcc' required by dkms
:: removing gcc breaks dependency 'gcc=11.1.0-1' required by gcc-fortran
:: removing gcc breaks dependency 'gcc>=3.3.1' required by vital-synth

I installed manually gcc-10 alongside gcc (gcc11)

is is possible to force /opt/rocm/llvm/bin/clang to select gcc-10?

**Comment by yxsamliu** [comment]
try --gcc-toolchain=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0

**Comment by yxsamliu** [comment]
To compile HIP program you need to use hipcc or clang as C++ compiler, which is done by the cmake file of rocBLAS. You cannot choose gcc as C++ compiler. To fix the specific issue, clang needs to use libstdc++ of gcc10. This needs to be done by passing the option --gcc-toolchain=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0 to hipcc or clang. You may set env var HIPCC_COMPILE_FLAGS_APPEND='--gcc-toolchain=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0' to force that option passed to hipcc.

**Comment by grinness** [comment]
Hi yxsamliu,

the 

HIPCC_COMPILE_FLAGS_APPEND='--gcc-toolchain=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0'

has no effect, neither the "--gcc-toolchain=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0" -- tried as CXXFLAG and/or cmake option

I managed to get the compilation starting (it beaks, see further down) with gcc-10 and relevant libs using the following (all tests passed and linked):
  PATH="/opt/rocm/llvm/bin:${PATH}" \
  CXX=/opt/rocm/bin/hipcc \
  CXXFLAGS="${CXXFLAGS} -fcf-protection=none -I/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++/x86_64-pc-linux-gnu -I/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/include/c++ -L/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0" \
  cmake -B build -Wno-dev \
        -S "$_dirname" \
	-DCMAKE_C_COMPILER=gcc-10 \
	-DCMAKE_LIBRARY_PATH=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0 \
	-DCMAKE_PREFIX_PATH=/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0 \
        -DCMAKE_INSTALL_PREFIX=/opt/rocm \
        -DCMAKE_PREFIX_PATH=/opt/rocm/llvm/lib/cmake/llvm \
        -Damd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr \
        -DBUILD_WITH_TENSILE=ON \
        -DBUILD_WITH_TENSILE_HOST=ON \
        -DTensile_LIBRARY_FORMAT=yaml \
        -DTensile_COMPILER=hipcc \
        -DTensile_ARCHITECTURE=all \
        -DTensile_LOGIC=asm_full \
        -DTensile_CODE_OBJECT_VERSION=V3 \
        -DBUILD_CLIENTS_TESTS=OFF \
        -DBUILD_CLIENTS_BENCHMARKS=OFF \
        -DBUILD_CLIENTS_SAMPLES=OFF \
        -DBUILD_TESTING=OFF

  make -C build

however, even with gcc-10 the rocblas compilation fails (compiling for gfx803):
[...]
In file included from /opt/hd01/projects/pkgbuild/rocm-amd/src/rocBLAS-rocm-4.2.0/library/src/blas_ex/../blas1/rocblas_reduction_template.hpp:7:
/opt/hd01/projects/pkgbuild/rocm-amd/src/rocBLAS-rocm-4.2.0/library/src/blas_ex/../blas1/fetch_template.hpp:34:17: error: reference to __host__ function 'norm<float>' in __host__ __device__ function
    return std::norm(A);

[...]
In file included from /opt/hd01/projects/pkgbuild/rocm-amd/src/rocBLAS-rocm-4.2.0/library/src/blas_ex/../blas1/rocblas_reduction_template.hpp:7:
/opt/hd01/projects/pkgbuild/rocm-amd/src/rocBLAS-rocm-4.2.0/library/src/blas_ex/../blas1/fetch_template.hpp:34:17: error: reference to __host__ function 'norm<double>' in __host__ __device__ function
    return std::norm(A);

2 errors generated when compiling for gfx803.
make[2]: *** [library/src/CMakeFiles/rocblas.dir/build.make:328: library/src/CMakeFiles/rocblas.dir/blas_ex/rocblas_nrm2_strided_batched_ex.cpp.o] Error 1
make[2]: Leaving directory '/opt/hd01/projects/pkgbuild/rocm-amd/src/build'
make[1]: *** [CMakeFiles/Makefile2:311: library/src/CMakeFiles/rocblas.dir/all] Error 2
make[1]: Leaving directory '/opt/hd01/projects/pkgbuild/rocm-amd/src/build'
make: *** [Makefile:156: all] Error 2
make: Leaving directory '/opt/hd01/projects/pkgbuild/rocm-amd/src/build'
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by TorreZuk** [comment]
@grinness can you describe your goal of using gcc.  We only support building rocBLAS using the rocm clang / hipcc toolchain.  You should be able to include the API header files and link against the library using gcc, but the library itself requires hip and the mentioned toolchain to compile and that is why you can't build it with gcc.

**Comment by grinness** [comment]
Hi TorreZuk,

I am just trying to compile rocblas 4.2.0 on my platform -- nothing else.
I use the PKGBUILD from AUR as the Arch4edu repo does not come with support for my GPU (rx480, gfx803)
In fact I have been compiling from AUR successfully since ROCM 4.0 ( and possibly earlier versions too)

The problem arose as the compilation process breaks in ROCM 4.2 with errors (see my first post):

In file included from /opt/rocm/llvm/lib/clang/12.0.0/include/cuda_wrappers/complex:75:
/usr/lib64/gcc/x86_64-pc-linux-gnu/11.1.0/../../../../include/c++/11.1.0/complex:703:7: error: host device function '__failed_assertion' cannot overload host function '__failed_assertion'
__glibcxx_assert( __rho >= 0 );

It is ROCM (or more precisely llvm-agpu from ROCM git repos) that includes headers from gcc-11 in its wrappers.

As I have been told (see second post from top, from  yxsamliu) that gcc10 works, I simply tried to change the include that ROCM platform sucks in from gcc-11 to gcc10 (and thus linking libs and compiler if it needs it).

Note that the output of the self configuration process of rocblas looks like the below (using the AUR original build script):

[...]
==> Starting build()...
-- The CXX compiler identification is Clang 12.0.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rocm/bin/hipcc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Use hip-clang to build for amdgpu backend
[..]
-- using GIT Tensile fork=ROCmSoftwarePlatform from branch=3438af228dc812768b20a068b0285122f327fa5b
[...]
-- The C compiler identification is GNU 11.1.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- ROCclr at /opt/rocm/lib/cmake/rocclr
-- hip::amdhip64 is SHARED_LIBRARY
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS
-- Performing Test HIP_CLANG_SUPPORTS_PARALLEL_JOBS - Success

From the above you can see that rocblas itself is detecting Clang 12 and gcc11

Finally, if you look at my last post above it is hipcc the CXX compiler -- this as in the AUR PKGBUILD:
CXX=/opt/rocm/bin/hipcc 

Note again that I can compile fine all the rocm-dev metapackage from AUR. It is rocblas that breaks.

For your reference the list of packages that compile fine without intervention from rocm-dev are:
depends=('comgr' 'hip-rocclr' 'hsa-amd-aqlprofile' 'hsakmt-roct' 'llvm-amdgpu'
         'openmp-extras' 'rocm-cmake' 'rocm-dbgapi' 'rocm-device-libs'
         'rocm-gdb' 'rocm-smi-lib64' 'rocm-utils' 'hsa-rocr'
         'rocprofiler' 'roctracer')

**Comment by TorreZuk** [comment]
It seems like the mixing of toolchains is still happening.  I would try forcing the both C++ and C compilers to hipcc and say they work so that cmake doesn't mess up the paths by detecting other compilers:
export CMAKE_CXX_COMPILER=hipcc
export CMAKE_C_COMPILER=hipcc
export CMAKE_CXX_COMPILER_WORKS=1
export CMAKE_C_COMPILER_WORKS=1
(If hipcc for C fails you can try to keep your gcc10  as not much should be compiled as C)
Tensile is encapsulated build of separate cloned repo and so does it's own cmake config so environment variables you could try if your script variables don't seem to be used.
If tensile build still tries looking in gcc11 and there isn't any thing like update-alternatives on arch linux you may try remapping the default symlinks to gcc10 from gcc11.
> It is ROCM (or more precisely llvm-agpu from ROCM git repos) that includes headers from gcc-11 in its wrappers.
The complex failure only uses #include_next so is based on the currently detected toolchain search paths.
To monitor the compilation include search path to see why and where gcc11 is used over gcc10 you can set:
export HIPCC_VERBOSE=7
Let us know if this provides further clues or works.

**Comment by yxsamliu** [comment]
one workaround is manaully patch /opt/rocm/llvm/lib/clang/12.0.0/include/cuda_wrappers/complex

with https://reviews.llvm.org/rG9a75c06cd9d94d3fd13c47a01044da97b98cf26b

then it should work with gcc11

**Comment by grinness** [comment]
Thank you TorreZuk and yxsmliu.

I followed yxsamliu suggestion and applied the patch as in 

https://reviews.llvm.org/rG9a75c06cd9d94d3fd13c47a01044da97b98cf26b

RocBlas 4.2.0 now compiles fine.

I went ahead and compiled the rocm-libs metapackage from AUR. 
The following libs also compile fine:
rocsolver                       
hipblas                          
rocprim                         
hipcub                          
rocsparse                     
hipsparse

Unfortunately  miopengemm exits compilation with errors:

/home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp: In function ‘std::vector<int> MIOpenGEMM::get_priority_confirmed(std::vector<int>, size_t)’:
/home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp:213:19: error: ‘numeric_limits’ is not a member of ‘std’
  213 |     if (x == std::numeric_limits<int>::max())
      |                   ^~~~~~~~~~~~~~
/home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp:213:34: error: expected primary-expression before ‘int’
  213 |     if (x == std::numeric_limits<int>::max())
      |                                  ^~~
/home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp:213:34: error: expected ‘)’ before ‘int’
  213 |     if (x == std::numeric_limits<int>::max())
      |        ~                         ^~~
      |                                  )


the errors above are due to:
miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp:213:19: error: ‘numeric_limits’ is not a member of ‘std’
  213 |     if (x == std::numeric_limits<int>::max())

Is it related to gcc11?
Has somebody forgot to add an #include <limits> somewhere?
Should I close this and open a new comment on MIOpenGEM page?

Thanks
G

**Comment by yxsamliu** [comment]
It seems MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp forgets to include `<limits>`

**Comment by grinness** [comment]
Hi,

I would also add that compiling miopengemm the outtput spams the following message:

In file included from /usr/include/CL/cl.h:20,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/platform.hpp:10,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/hint.hpp:10,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/oclutil.hpp:9,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/hyperparams.hpp:13,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/derivedparams.hpp:14,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/bundle.hpp:8,
                 from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/miogemm.cpp:4:
/usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
   22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")


Rocm-opencl-runtime provide Opencl 2.0 not 3.0:
https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime

Does the above make sense?

Thanks again.

**Comment by TorreZuk** [comment]
Great to hear the patch Sam pointed out works for this.   If you don't mind please copy and paste your last MIOpenGEMM comments into a new issue for miopengemm as it sounds like that library team may have to make changes, and then this issue can be closed.   @yxsamliu you can watch for that new issue right?

**Comment by grinness** [comment]
ok, thanks again
closing now

**Comment by yxsamliu** [comment]
> Hi,
> 
> I would also add that compiling miopengemm the outtput spams the following message:
> 
> In file included from /usr/include/CL/cl.h:20,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/platform.hpp:10,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/hint.hpp:10,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/oclutil.hpp:9,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/hyperparams.hpp:13,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/derivedparams.hpp:14,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/bundle.hpp:8,
> from /home/marco/.cache/yay/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/miogemm.cpp:4:
> /usr/include/CL/cl_version.h:22:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)’
> 22 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)")
> 
> Rocm-opencl-runtime provide Opencl 2.0 not 3.0:
> https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime
> 
> Does the above make sense?
> 
> Thanks again.

/usr/include/CL/cl_version.h is not part of ROCm opencl package, which may be incomptable with MIOpenGEMM. ROCm OpenCL has /opt/rocm/opencl/include/CL/cl_version.h

**Comment by grinness** [comment]
Hi xsamliu,

> 
> /usr/include/CL/cl_version.h is not part of ROCm opencl package, which may be incomptable with MIOpenGEMM. ROCm OpenCL has /opt/rocm/opencl/include/CL/cl_version.h

I understand that this is not part of rocm, but then why miopengemm is including that file and not it's own?
To me this is an issue in the 'autoconf' of miopengemm -- the /usr/include/CL/cl_version.h is part of the distro. if miopengemm wants its own include, it should be aware of it and where it is

I am wrong?

**Comment by grinness** [comment]
> Hi xsamliu,
> 
> > /usr/include/CL/cl_version.h is not part of ROCm opencl package, which may be incomptable with MIOpenGEMM. ROCm OpenCL has /opt/rocm/opencl/include/CL/cl_version.h
> 
> I understand that this is not part of rocm, but then why miopengemm is including that file and not it's own?
> To me this is an issue in the 'autoconf' of miopengemm -- the /usr/include/CL/cl_version.h is part of the distro. if miopengemm wants its own include, it should be aware of it and where it is
> 
> I am wrong?

xsamuliu,

I just checked and I do not have on my system an /opt/rocm/opencl/include/CL/cl_version.h

I do have the below:
> find /opt/rocm -name "cl_version.h"                                                                      
/opt/rocm/include/CL/cl_version.h

**Comment by yxsamliu** [comment]
do you have the compilation command line for miogemm.cpp? I would expect it to have -I/opt/rocm/opencl/include. Probably it finds /usr/include/CL/cl_version.h due to /opt/rocm/opencl/include is missing.

**Comment by grinness** [comment]
Hi yxsamliu,

the AUR PKGBUILD default build section looks like:

l# -fcf-protection is not supported by HIP, see
  # https://github.com/ROCm-Developer-Tools/HIP/blob/rocm-4.2.x/docs/markdown/clang_options.md
  # -fPIC fixes linking errors with boost.
  export CXX=/opt/rocm/llvm/bin/clang++
  export CXXFLAGS="${CXXFLAGS} -fcf-protection=none -fPIC"

  cmake -P install_deps.cmake \
        --minimum --prefix "$srcdir/deps"

  cmake -B build -Wno-dev \
        -DMIOPEN_BACKEND=HIP \
        -DCMAKE_INSTALL_PREFIX=/opt/rocm \
        -DCMAKE_PREFIX_PATH="$srcdir/deps"

  make -C build

There is nothing specific on includes that is non standard that I can see

The source comes directly from ROCm github (plus a specific boost patch):
url="https://github.com/ROCmSoftwarePlatform/MIOpen"
pkgname=miopen-hip
pkgver=4.2.0
source=("$pkgname-$pkgver.tar.gz::$url/archive/rocm-$pkgver.tar.gz"
        'boost-1.72-download.patch')

**Comment by grinness** [comment]
For what concern the rocm-opencl-runtime:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocm-opencl-runtime

the cmake  command installs in prefix /opt/rocm:


build() {
    CFLAGS="$CFLAGS -isystem /opt/rocm/include/compiler/lib -isystem /opt/rocm/include/compiler/lib/include -isystem /opt/rocm/include/elf" \
    CXXFLAGS="$CXXFLAGS -isystem /opt/rocm/include/compiler/lib -isystem /opt/rocm/include/compiler/lib/include -isystem /opt/rocm/include/elf" \
    cmake -DCMAKE_INSTALL_PREFIX=/opt/rocm \
          -DUSE_COMGR_LIBRARY=yes \
          -DBUILD_TESTING=OFF \
          "$_dirname"
    make

should the prefix be /opt/rocm/opencl ?

**Comment by yxsamliu** [comment]
The error you saw about opencl version happened when you built MIOpenGEMM, right? It is a different package than MIOpen:

https://github.com/ROCmSoftwarePlatform/MIOpenGEMM

You can specify opencl include path and library path by cmake.

**Comment by grinness** [comment]
Hi yxamliu,

it is the same package.
I'll change the cmake  -DOPENCL_LIBRARIES=<opencl-library-path> -DOPENCL_INCLUDE_DIRS<opencl-headers-path>
I'll also add that #include<limits>  and test out

Thanks

**Comment by grinness** [comment]
I confirm that adding the cmake flags at build time solves the issue with inclusion of system CL include.
Also including limits in MIOpenGEMM-rocm-4.2.0/miopengemm/src/enums.cpp solves the compilation error

Note the following:

 In file included from /opt/rocm/include/CL/cl.h:32,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/platform.hpp:10,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/hint.hpp:10,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/oclutil.hpp:9,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/hyperparams.hpp:13,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/derivedparams.hpp:14,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/include/miopengemm/bundle.hpp:8,
                 from /opt/hd01/projects/pkgbuild/miopengemm/src/MIOpenGEMM-rocm-4.2.0/miopengemm/src/programcacher.cpp:6:
/opt/rocm/include/CL/cl_version.h:34:104: note: ‘#pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)’
   34 | #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
