### ISSUE TITLE
Difference between Tensile_ARCHITECTURE and Tensile_LOGIC?

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/rocBLAS#1192]
What are Tensile_ARCHITECTURE and Tensile_LOGIC, and how are they supposed to be used?

**Comment by sdquiring** [comment]
`Tensile_ARCHITECTURE` allows you to limit the GPU architecture(s) that are targeted when building Tensile within rocBLAS.  By default, it has the same value as `AMDGPU_TARGETS` which would mean a consistent set of GPUs between Tensile and the rest of rocBLAS.

`Tensile_LOGIC` allows you to select a different logic directory from within https://github.com/ROCmSoftwarePlatform/rocBLAS/tree/develop/library/src/blas3/Tensile/Logic , effectively a different set of kernels for GEMM.  This is mostly for experimentation purposes.

**Comment by TorreZuk** [comment]
Thanks @sdquiring !   Some more background on Tensile logic is at https://rocmdocs.amd.com/en/latest/ROCm_Tools/tensile.html#librarylogic if you want to dig deeper.  The architecture set in Tensile_ARCHITECTURE should be the one passed into -a of install.sh as you want compilation for the GPU architectures to be consistent for rocBLAS library source kernels and the tensile library (embedded in rocBLAS).    The current install.sh in develop now just sets AMDGPU_TARGETS which is applied to both build configurations.

**Comment by TorreZuk** [comment]
Closing this issue @haampie but you can open another if you have further questions.  If they are specific to Tensile logic you can open them on the Tensile repo.   Thanks.
