### ISSUE TITLE
Minor typos: thown -> thrown

### ISSUE THREAD

**Issue by twhite-cray** [ROCmSoftwarePlatform/rocBLAS#1200]
https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/9d6a6d8d33d20da172c6a1dae6c7389296a647e6/library/src/tensile_host.cpp#L828
https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/9d6a6d8d33d20da172c6a1dae6c7389296a647e6/library/src/tensile_host.cpp#L834

**Comment by amcamd** [comment]
Thanks for reporting this typo. It is corrected in the develop branch with commit 6588efe.
