### ISSUE TITLE
incremental compile

### ISSUE THREAD

**Issue by jianlongf** [ROCmSoftwarePlatform/rocBLAS#1201]
### What is the expected behavior
- incremental compile

### What actually happens
- every time I used install.sh to build client. It seems like building from scratch and cost a lot times.

### How to reproduce
- ./install -c

### Environment
| Hardware | description |
|-----|-----|
| GPU | Vega 20 |

| Software | version |
|-----|-----|
| ROCM | 4.0.x |

And another problem. I wanna extract gemm kernel from rocBLAS because I wana fuse(gemm + relu / gemm + add / gemm + max ) operations. But there is not such api in rocBLAS. So is there guide about that.

**Comment by amcamd** [comment]
Hello Jianlongf, 
For an incremental compile can you please:
cd build/release; make

Also, to speed up install.sh, can you use the -a flag to specify the vega20 architecture. I use the following in a script to build rocBLAS for a single architecture, not a fat binary for multiple architectures:

if [ "$(/opt/rocm/bin/rocm_agent_enumerator | grep -m 1 gfx900)" == "gfx900" ]; then
    echo "=====ISA = gfx900, use -agfx900 directive ===================="
    time VERBOSE=1 ./install.sh -agfx900 -c 2>&1 | tee install.out
elif [ "$(/opt/rocm/bin/rocm_agent_enumerator | grep -m 1 gfx906)" == "gfx906" ]; then
    echo "=====ISA = gfx906, use -agfx906:xnack- directive ===================="
    time VERBOSE=1 ./install.sh -agfx906:xnack- -c 2>&1 | tee install.out
elif [ "$(/opt/rocm/bin/rocm_agent_enumerator | grep -m 1 gfx908)" == "gfx908" ]; then
    echo "=====ISA = gfx908, use -agfx908:xnack- directive ===================="
    time VERBOSE=1 ./install.sh -agfx908:xnack- -c 2>&1 | tee install.out
elif [ "$(/opt/rocm/bin/rocm_agent_enumerator | grep -m 1 gfx90a)" == "gfx90a" ]; then
    echo "=====ISA = gfx90a, use -agfx90a:xnack- directive ===================="
    time VERBOSE=1 ./install.sh -agfx90a:xnack- -c 2>&1 | tee install.out
else
    echo "build fat binary, ISA != gfx900 and ISA != gfx906 and ISA != gfx908 and ISA != gfx90a"
    time VERBOSE=1 ./install.sh -c 2>&1 | tee install.out
fi

The gemm kernels in rocBLAS are written in assembly. Do you want to extract assembly kernels? We do not document the internal API for the gemm kernels. You can find the assembly kernel files with 
find . -name *.s

**Comment by jianlongf** [comment]
@amcamd  Thanks a lot. That's very help to me.
