### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by haampie** [ROCmSoftwarePlatform/rocBLAS#1204]
When compiling rocBLAS I'm getting this error for as long as I remember:
```
*******************************************************************************
*----------------------------------- ERROR -----------------------------------*
* The variable 'CMAKE_CXX_FLAGS' should only be set by the cmake toolchain,
* either by calling 'cmake -DCMAKE_CXX_FLAGS=" -D__HIP_HCC_COMPAT_MODE__=1 -std=c++14"' or
* set in a toolchain file and added with
* 'cmake -DCMAKE_TOOLCHAIN_FILE=<toolchain-file>'.
*-----------------------------------------------------------------------------*
*******************************************************************************
```

**Comment by TorreZuk** [comment]
I think I remember a day when it wasn't there :-)   I have asked for it to be fixed a long while back too so I'll prod them again, I also had agreed with changes that would not incorrectly call it such a thing an error but those were not accepted.  It may be I can get them to fix it or perhaps will be able to fix it myself now, I'll keep you posted.

**Comment by TorreZuk** [comment]
https://github.com/ROCmSoftwarePlatform/Tensile/pull/1403 looks like it may be close to going in and should fix the last ones.

**Comment by haampie** [comment]
Nice, that's great!

**Comment by TorreZuk** [comment]
Additionally now rocm-cmake will report these cases as ROCMChecks warnings:|https://github.com/RadeonOpenCompute/rocm-cmake/pull/62 and environment variable toggles have been added.
