### ISSUE TITLE
Compilation warning

### ISSUE THREAD

**Issue by lucbv** [ROCmSoftwarePlatform/rocBLAS#1214]
### What is the expected behavior
- I would like to avoid warnings from the library to have my own code build and link cleanly on top of rocblas

### What actually happens
- I am getting the following warning:
```
/opt/rocm-4.3.0/rocblas/include/internal/rocblas_bfloat16.h:59:9: warning: declaration shadows a variable in the global namespace [-Wshadow]
        truncate
        ^
/usr/include/unistd.h:994:12: note: previous declaration is here
extern int truncate (const char *__file, __off_t __length)
           ^
1 warning generated when compiling for host.
```

### How to reproduce
- I believe just building host code and linking against rocblas using the clang compiler will generate that warning

### Environment
| Hardware | description |
|-----|-----|
| GPU | MI100 |
| CPU | 64-core AMD EPYC 7662 “Rome” CPU |

| Software | version |
|-----|-----|
| ROCm | v4.3.0 |
| rocBLAS | v2.39.0 |

In general I believe that rename the variable would solve this issue and looking at the rocBLAS repo, this issue is likely still present in the develop branch.

**Comment by NaveenElumalaiAMD** [comment]
Hi, Thank you for reporting this issue. I did not get the compilation warning when I tried to reproduce this error from my side. Would you be able to provide more information, a sample code and  how you built it?

**Comment by lucbv** [comment]
@NaveenElumalaiAMD thanks, sorry for being slow in my response!

**Comment by NaveenElumalaiAMD** [comment]
@[lucbv](https://github.com/lucbv), a fix for this issue has been merged to the rocBLAS `develop` branch.
Commit ID:  [1dc27bd](https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/1dc27bd2be483e39bdf347c3b01dd7ed64ab8836) 
I will go ahead and close this ticket. If you are not satisfied with the fix, you could re-open this issue. Thanks
