### ISSUE TITLE
Fortran examples

### ISSUE THREAD

**Issue by Madu86** [ROCmSoftwarePlatform/rocBLAS#1224]
Hello, 
I want to use bindings from rocblas_module.f90; but unfortunately, I couldn’t find any examples in ROCBLAS manual (https://rocblas.readthedocs.io/_/downloads/en/master/pdf/). Where can I find some fortran examples? Thanks!

**Comment by TorreZuk** [comment]
Hi @Madu86 ,
You can look at https://github.com/ROCmSoftwarePlatform/rocBLAS-Examples/tree/develop/Languages/Fortran and the three client samples that use fortran: https://github.com/ROCmSoftwarePlatform/rocBLAS/tree/develop/clients/samples. 
If you try to follow those and get stuck let us know what errors you see and what fortran you are trying to use
Thanks.

**Comment by Madu86** [comment]
Hi @TorreZuk, Thank you very much. I went through your examples and wrote the drivers I needed. With gfortran-7.5, I didnt encounter any problems.

**Comment by TorreZuk** [comment]
Thanks for reaching out to us. Closing the issue.
