### ISSUE TITLE
Compilation error with vanilla llvm-13

### ISSUE THREAD

**Issue by Maxzor** [ROCmSoftwarePlatform/rocBLAS#1229]
Hello,
Cross-posting as this might very be a rocBLAS issue instead of a Tensile one:
https://github.com/ROCmSoftwarePlatform/Tensile/issues/1455.

**Comment by TorreZuk** [comment]
So @Maxzor is this resolved based on your comment in the Tensile issue?   We will only directly support compilation using the llvm clang bundled with the rocm distribution and it sounds like your build is using other llvm so relies on others to fix it.   Anyway  please comment further or close this issue.

**Comment by Maxzor** [comment]
@TorreZuk I updated the issue with another point that I am facing.
This is not just an "other" LLVM, this is upstream LLVM, so some support for it would be really nice.
