### ISSUE TITLE
rocblas_hgemm is not implement

### ISSUE THREAD

**Issue by BiranLi** [ROCmSoftwarePlatform/rocBLAS#123]
In this version we can not test the half-precision performance, because I found that function rocblas_hgemm have not been implement.
How can we test the half-precision performance in VEGA10-MI25?

**Comment by kknox** [comment]
Can you define what you are looking for with 'semi-fine' performance?

**Comment by BiranLi** [comment]
@kknox Sorry, it's my false. I mean half-precision floating-point format gemm's performance. How to test it in MI25?

**Comment by kknox** [comment]
@BiranLi 
HGEMM is a case where our software implementation is trailing our hardware implementation; we don't have a optimized kernel yet that can leverage the float16 packed math necessary to demonstrate peak half rate.  It is a feature we are looking at, and we want to do it right, but we have to first finish other feature dependencies that hgemm would leverage.  
As we work on this, you might be interested to know of the independent [gcngemm implementation](https://github.com/hyln9/GCNGEMM), which includes an hgemm implementation optimized for prior generation( fiji, single rate, limited GEMM parameters implemented).

**Comment by tingxingdong** [comment]
@hyln9

**Comment by BiranLi** [comment]
@kknox Thank you for your reply. I have looked into the independent gcngemm. But it 's only optimized for fiji while my hardware is vega-MI25.I have test sgemm in rocblas and miopengemm. The latter than the former in MI25 is twice as fast speed. 
By the way, the library [hcBLAS](https://github.com/ROCmSoftwarePlatform/hcBLAS) helpful? I found hgemm api in its include file.

**Comment by kknox** [comment]
Yes, gcngemm is optimized for fiji, but until we get packed fp16 kernels in rocblas it is the best implementation I know of.
If you are measuring miopengemm as faster than rocblas for sgemm, can you share the GEMM parameters you tested?  We would be interested in running our own benchmarks.

hcblas was a port to hip of the clblas source, as a way to bootstrap libraries development.  Development of hcblas should ramp down as rocblas gains more functionality.  It might be interesting to measure for your application if you have time, but i don't expect faster results

**Comment by BiranLi** [comment]
@kknox OK, I get it.
My test issues of sgemm as follow, and  the speed measured with miopengemm is similar with measured with cuBlas in P40.

m | k | n
-- | -- | --
128 | 832 | 2048
128 | 2048 | 2048
128 | 2048 | 9024
256 | 832 | 2048
256 | 2048 | 2048
256 | 2048 | 9024
