### ISSUE TITLE
Missing code to support --relocatable

### ISSUE THREAD

**Issue by amd-isparry** [ROCmSoftwarePlatform/rocBLAS#1237]
### What is the expected behavior
- ./install --relocatable
should work.

### What actually happens
    ./install.sh: unrecognized option '--relocatable'
    getopt invocation failed; could not parse the command line
and the program exits with a return code of 1.

### How to reproduce
- "./install -r"
### Environment
N/A
The 'display_help' function has

    -r, --relocatable                Add RUNPATH(based on ROCM_RPATH) and remove ldconf entry.

in it, but the getopt call doesn't handle either.

**Comment by daineAMD** [comment]
Hi @amd-isparry
Looks like that help message was added from hipBLAS mistakenly, it doesn't look like there has been any work on implementing this in rocBLAS. I'll work on adding it and let you know when it's available in develop.
