### ISSUE TITLE
rocblas-clients  build error for ROCm 5.1.1 

### ISSUE THREAD

**Issue by yukirora** [ROCmSoftwarePlatform/rocBLAS#1241]
### What is the expected behavior
- I want to only build rocblas clients for ROCm 5.1.1 inside docker image [rocm/pytorch:rocm5.1.1_ubuntu20.04_py3.7_pytorch_1.10.0](https://registry.hub.docker.com/layers/pytorch/rocm/pytorch/rocm5.1.1_ubuntu20.04_py3.7_pytorch_1.10.0/images/sha256-df3e74b4f80ba64ae3d040824ee49e858c5ee4810f44a3747e744b577a928b24?context=explore)

### What actually happens
- It failed to build and I got the 'header file tensile_host.hpp not found in rocBLAS/clients/benchmarks/client.cpp ' error 
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/37182275/163548595-6d53fb73-9086-45c5-b7ff-b78b35f08b0e.png">

### How to reproduce
git clone -b rocm-5.1.1 https://github.com/ROCmSoftwarePlatform/rocBLAS.git ./rocBLAS
cd ./rocBLAS && ./install.sh --dependencies --clients-only 

I can fix this issue by 
 - adding '    $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/../../library/src/include>' in rocBLAS/clients/benchmarks/CMakeLists.txt at line#20 
**or** 
 - change the tensile_host.hpp to right relative path in rocBLAS/clients/benchmarks/client.cpp
 
but could you please help me on how to add this patch into ROCm 5.1.1 branch or tag?

**Comment by rkamd** [comment]
@yukirora , 
Thanks for identifying the issue, a fix has been merged to 'release/rocm-rel-5.1' branch.
Commit ID: https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/06fde28a42e814f23de1eb675abf9879056e700b

**Comment by yukirora** [comment]
really thanks for your quick action

**Comment by yukirora** [comment]
Thanks, it works for me and close the issue.
