### ISSUE TITLE
Please enable two factor authentication in your github account

### ISSUE THREAD

**Issue by DeeptimayeeSethi** [ROCmSoftwarePlatform/rocBLAS#1243]
@rdkl;@NEELMCW;@directml;@sriharikarnam;@mlseqasa

We are going to enforce two factor authentication in (https://github.com/ROCmSoftwarePlatform/) organization on 29th April, 2022 . 
Since we identified you as outside collaborator for ROCmSoftwarePlatform organization, you need to enable two factor authentication in your github account else you shall be removed from the organization after the enforcement. 
Please skip if already done.

To set up two factor authentication, please go through the steps in below link:

https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/configuring-two-factor-authentication

Please email "Deeptimayee.Sethi@amd.com" for queries

**Comment by NaveenElumalaiAMD** [comment]
Closing this issue as the people tagged here are not directly associated with the rocBLAS library.
