### ISSUE TITLE
rocm5.1 build fails due to yaml missing but pyyaml is installled.

### ISSUE THREAD

**Issue by gggh000** [ROCmSoftwarePlatform/rocBLAS#1244]
pip3 list | grep yaml -i
PyYAML                  3.12

./install.sh -icd 
...
...
   Tensile_LIBRARY_FORMAT

-- Build files have been written to: /root/ROCm-5.1/rocBLAS/build/release
+ check_exit_code 0
+ ((  0 != 0  ))
+ [[ true == true ]]
+ make -j96 install
Scanning dependencies of target rocblas-common
Scanning dependencies of target rocblas_device_malloc
Scanning dependencies of target rocblas_fortran
Scanning dependencies of target rocblas-test-data
Scanning dependencies of target rocblas_proto_templates
[  0%] Generating staging/rocblas_common.yaml
[  0%] Generating staging/rocblas_gentest.py
[  0%] Generating /root/ROCm-5.1/rocBLAS/build/release/include/internal/rocblas_device_malloc.hpp
[  0%] Generating ../staging/rocblas_gtest.data
[  1%] Generating staging/rocblas_template.yaml
[  2%] Generating prototypes from /root/ROCm-5.1/rocBLAS/library/src.
[  2%] Built target rocblas_device_malloc
[  2%] Built target rocblas-common
[  3%] Building Fortran object clients/CMakeFiles/rocblas_fortran.dir/__/library/include/rocblas_module.f90.o
Traceback (most recent call last):
  File "../common/rocblas_gentest.py", line 12, in <module>
    from yaml import CLoader as Loader
ModuleNotFoundError: No module named 'yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../common/rocblas_gentest.py", line 14, in <module>
    from yaml import Loader
ModuleNotFoundError: No module named 'yaml'
make[2]: *** [clients/gtest/CMakeFiles/rocblas-test-data.dir/build.make:117: clients/staging/rocblas_gtest.data] Error 1
make[1]: *** [CMakeFiles/Makefile2:769: clients/gtest/CMakeFiles/rocblas-test-data.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target rocblas_proto_templates
[  3%] Built target rocblas_fortran
make: *** [Makefile:155: all] Error 2
+ check_exit_code 2
+ ((  2 != 0  ))
+ exit 2

**Comment by TorreZuk** [comment]
Merging this into issue #1234 as closely related.   As I expect it relates to OS, as stated in that issue:  "Unfortunately Centos Stream 8 is not one of the ROCm supported OS (System Requirements) as listed at https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.1.1/page/Overview_of_ROCm_Installation_Methods.html  " If details on python modules installed are provided in that issue we can advise on workarounds but for now closing these issues as duplicates.
