### ISSUE TITLE
[Bug]: rocBLAS doesn't build for gfx908 (MI100)

### ISSUE THREAD

**Issue by dipietrantonio** [ROCmSoftwarePlatform/rocBLAS#1250]
### Describe the bug
I am trying to install rocBLAS (as part of a wider rocm5.1 installation from source) to run on a supercomputer node with a Mi100 card. Here is my command line to compile it
```
cd $BUILD_FOLDER/rocBLAS
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="$ROCM_INSTALL_DIR/llvm;$ROCM_INSTALL_DIR;$ROCM_INSTALL_DIR/hip"\
	-DCMAKE_TOOLCHAIN_FILE=../toolchain-linux.cmake \
	-DTENSILE_USE_MSGPACK=OFF -DCMAKE_INSTALL_PREFIX=$ROCM_INSTALL_DIR ..
run_command make
run_command make install
cd $BUILD_FOLDER
```

 I get the following error, hinting that the Mi100 is not supported yet. Is there something I can do?
```
Stack dump:
0.      Program arguments: /opt/rocm-dev2/llvm/bin/clang++ -x assembler -target amdgcn-amd-amdhsa -mcode-object-version=2 -mcpu=gfx1030 -mno-wavefrontsize64 -c -o /home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Ailk_Bjlk_SB_GB_MT128x128x16_SN_1LDSB0_APM14gJbgJoOhaj1_r6Jhlc1xJ7NyRUW0jYTyEb_T0l8lis=.o /home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Ailk_Bjlk_SB_GB_MT128x128x16_SN_1LDSB0_APM14gJbgJoOhaj1_r6Jhlc1xJ7NyRUW0jYTyEb_T0l8lis=.s
 #0 0x00005630519085a4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x00005630519064c4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/rocm-dev2/llvm/bin/clang+++0x261a4c4)
 #2 0x0000563051851348 llvm::CrashRecoveryContext::HandleExit(int) (/opt/rocm-dev2/llvm/bin/clang+++0x2565348)
 #3 0x00005630518fe772 llvm::sys::Process::Exit(int, bool) (/opt/rocm-dev2/llvm/bin/clang+++0x2612772)
 #4 0x00005630500518e3 (/opt/rocm-dev2/llvm/bin/clang+++0xd658e3)
 #5 0x0000563051857709 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/rocm-dev2/llvm/bin/clang+++0x256b709)
 #6 0x00005630503d9caa llvm::AMDGPU::IsaInfo::AMDGPUTargetID::toString[abi:cxx11]() const (/opt/rocm-dev2/llvm/bin/clang+++0x10edcaa)
 #7 0x000056305037edf6 (anonymous namespace)::AMDGPUAsmParser::ParseDirectiveAMDGCNTarget() AMDGPUAsmParser.cpp:0:0
 #8 0x000056305038e433 (anonymous namespace)::AMDGPUAsmParser::ParseDirective(llvm::AsmToken) AMDGPUAsmParser.cpp:0:0
 #9 0x00005630515341ba (anonymous namespace)::AsmParser::parseStatement((anonymous namespace)::ParseStatementInfo&, llvm::MCAsmParserSemaCallback*) AsmParser.cpp:0:0
#10 0x0000563051528462 (anonymous namespace)::AsmParser::Run(bool, bool) AsmParser.cpp:0:0
#11 0x0000563050057763 ExecuteAssemblerImpl((anonymous namespace)::AssemblerInvocation&, clang::DiagnosticsEngine&) cc1as_main.cpp:0:0
#12 0x0000563050058e70 cc1as_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/rocm-dev2/llvm/bin/clang+++0xd6ce70)
#13 0x000056305004c8ef ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#14 0x00005630521bfe59 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#15 0x00005630518511c7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/rocm-dev2/llvm/bin/clang+++0x25651c7)
#16 0x00005630521c008c clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.0) Job.cpp:0:0
#17 0x000056305218aefc clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/rocm-dev2/llvm/bin/clang+++0x2e9eefc)
#18 0x000056305218b83f std::_Function_handler<void (), clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const::'lambda'()>::_M_invoke(std::_Any_data const&) Compilation.cpp:0:0
#19 0x000056305218f595 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/rocm-dev2/llvm/bin/clang+++0x2ea3595)
#20 0x0000563052198ff2 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/rocm-dev2/llvm/bin/clang+++0x2eacff2)
#21 0x000056304ffc0ce8 main (/opt/rocm-dev2/llvm/bin/clang+++0xcd4ce8)
#22 0x00007f590160c083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#23 0x000056305004c4ce _start (/opt/rocm-dev2/llvm/bin/clang+++0xd604ce)
Command '['/opt/rocm-dev2/llvm/bin/clang++', '-x', 'assembler', '-target', 'amdgcn-amd-amdhsa', '-mcode-object-version=2', '-mcpu=gfx908', '-mwavefrontsize64', '-c', '-o', '/home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Alik_Bljk_CB_GB_MT32x64x16_MI16x16x4x1_SN_1jssIkxJnB4oGXbjD63raRyFuQOI6TLlcsj3TLzJ5-Nw=.o', '/home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Alik_Bljk_CB_GB_MT32x64x16_MI16x16x4x1_SN_1jssIkxJnB4oGXbjD63raRyFuQOI6TLlcsj3TLzJ5-Nw=.s']' returned non-zero exit status 1.
 #0 0x000055611b1b55a4 PrintStackTraceSignalHandler(void*) Signals.cpp:0:0
 #1 0x000055611b1b34c4 llvm::sys::CleanupOnSignal(unsigned long) (/opt/rocm-dev2/llvm/bin/clang+++0x261a4c4)
 #2 0x000055611b0fe348 llvm::CrashRecoveryContext::HandleExit(int) (/opt/rocm-dev2/llvm/bin/clang+++0x2565348)
 #3 0x000055611b1ab772 llvm::sys::Process::Exit(int, bool) (/opt/rocm-dev2/llvm/bin/clang+++0x2612772)
 #4 0x00005561198fe8e3 (/opt/rocm-dev2/llvm/bin/clang+++0xd658e3)
 #5 0x000055611b104709 llvm::report_fatal_error(llvm::Twine const&, bool) (/opt/rocm-dev2/llvm/bin/clang+++0x256b709)
 #6 0x0000556119c86caa llvm::AMDGPU::IsaInfo::AMDGPUTargetID::toString[abi:cxx11]() const (/opt/rocm-dev2/llvm/bin/clang+++0x10edcaa)
 #7 0x0000556119c2bdf6 (anonymous namespace)::AMDGPUAsmParser::ParseDirectiveAMDGCNTarget() AMDGPUAsmParser.cpp:0:0
 #8 0x0000556119c3b433 (anonymous namespace)::AMDGPUAsmParser::ParseDirective(llvm::AsmToken) AMDGPUAsmParser.cpp:0:0
 #9 0x000055611ade11ba (anonymous namespace)::AsmParser::parseStatement((anonymous namespace)::ParseStatementInfo&, llvm::MCAsmParserSemaCallback*) AsmParser.cpp:0:0
#10 0x000055611add5462 (anonymous namespace)::AsmParser::Run(bool, bool) AsmParser.cpp:0:0
#11 0x0000556119904763 ExecuteAssemblerImpl((anonymous namespace)::AssemblerInvocation&, clang::DiagnosticsEngine&) cc1as_main.cpp:0:0
#12 0x0000556119905e70 cc1as_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/rocm-dev2/llvm/bin/clang+++0xd6ce70)
#13 0x00005561198f98ef ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#14 0x000055611ba6ce59 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#15 0x000055611b0fe1c7 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/rocm-dev2/llvm/bin/clang+++0x25651c7)
#16 0x000055611ba6d08c clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (.part.0) Job.cpp:0:0
#17 0x000055611ba37efc clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/rocm-dev2/llvm/bin/clang+++0x2e9eefc)
#18 0x000055611ba3883f std::_Function_handler<void (), clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const::'lambda'()>::_M_invoke(std::_Any_data const&) Compilation.cpp:0:0
#19 0x000055611ba3c595 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/opt/rocm-dev2/llvm/bin/clang+++0x2ea3595)
#20 0x000055611ba45ff2 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/opt/rocm-dev2/llvm/bin/clang+++0x2eacff2)
#21 0x000055611986dce8 main (/opt/rocm-dev2/llvm/bin/clang+++0xcd4ce8)
#22 0x00007f64edc0a083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#23 0x00005561198f94ce _start (/opt/rocm-dev2/llvm/bin/clang+++0xd604ce)
Command '['/opt/rocm-dev2/llvm/bin/clang++', '-x', 'assembler', '-target', 'amdgcn-amd-amdhsa', '-mcode-object-version=2', '-mcpu=gfx1030', '-mno-wavefrontsize64', '-c', '-o', '/home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Ailk_Bjlk_SB_GB_MT128x128x16_SN_1LDSB0_APM14gJbgJoOhaj1_r6Jhlc1xJ7NyRUW0jYTyEb_T0l8lis=.o', '/home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Ailk_Bjlk_SB_GB_MT128x128x16_SN_1LDSB0_APM14gJbgJoOhaj1_r6Jhlc1xJ7NyRUW0jYTyEb_T0l8lis=.s']' returned non-zero exit status 1.
clang -cc1as: fatal error: error in backend: AMD GPU code object V2 does not support processor gfx908
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /opt/rocm-dev2/llvm/bin/clang++ -x assembler -target amdgcn-amd-amdhsa -mcode-object-version=2 -mcpu=gfx908 -mwavefrontsize64 -c -o /home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Alik_Bljk_HBH_MT32x32x32_MI16x16x16x1_SE_1L_vhzGP2c1HC2YgvzBSjBmAvz867yIONrb3B4r_mTgXE=.o /home/ubuntu/build/rocBLAS/build/library/src/build_tmp/TENSILE/assembly/Cijk_Alik_Bljk_HBH_MT32x32x32_MI16x16x16x1_SE_1L_vhzGP2c1HC2YgvzBSjBmAvz867yIONrb3B4r_mTgXE=.s
clang -cc1as: fatal error: error in backend: AMD GPU code object V2 does not support processor gfx1030
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
```

**Comment by cgmb** [comment]
I think you probably need `-DTensile_CODE_OBJECT_VERSION=V3`. When using CMake directly, rocBLAS defaults to V2. Most developers use the `install.sh` script, which always passes these parameters explicitly, so the CMake defaults are not often used.

If you're going through all the libraries building from source, you may be interested in [the build script I wrote for Debian](https://gist.github.com/cgmb/7cd9a481c42ce132b5d6420380becef3) a while back. It's not up-to-date for ROCm 5.1, but for most libraries the process will have remained more or less the same.

**Comment by NaveenElumalaiAMD** [comment]
Hi @[dipietrantonio](https://github.com/dipietrantonio), thank you for reporting this bug. In response to this bug, I was able to build rocBLAS by following the steps below:
1.	It is mentioned in your ticket that you are seeing this bug in ROCm-5.1. So, I downloaded the ROCm-5.1 docker from here: https://hub.docker.com/r/rocm/rocm-terminal/tags/ using the command: `docker pull rocm/rocm-terminal:5.1`.
2.	Then, ran the docker using the command: `sudo docker run --device=/dev/dri --device=/dev/kfd --group-add=video --network=host --ipc=host --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -i -t rocm/rocm-terminal:5.1`.
3.	Cloned the branch `release/rocm-rel-5.1` from the rocBLAS repository, using the command: ` git clone -b release/rocm-rel-5.1 https://github.com/ROCmSoftwarePlatform/rocBLAS.git` .
4.	Next, changed the directory using the command `cd rocBLAS` and use the install.sh script to build rocBLAS using the command: `./install.sh -dc -a gfx908:xnack-`. 
Please use the script install.sh in place of directly using cmake. A little bit of info about the command line arguments I used:

      -d = Build and install external dependencies.
      -c = Build the library clients benchmark and gtest.
      -a = Set GPU architecture target. Since you were using MI100, the corresponding GPU architecture name is gfx908.

Following all the above steps, I was able to build rocBLAS successfully in a ROCm-5.1 docker. You can also find further documentation on how to build rocBLAS and information about the install.sh script command line arguments here: https://docs.amd.com/bundle/rocBLAS-User-Guide---rocBLAS-documentation/page/Linux_Install_Guide.html.
Let me know if you have any challenges using the install.sh script, I would be happy to help.
Thanks

**Comment by dipietrantonio** [comment]
Thanks to both of you for your replies. @cgmb your suggestion got me pass that error, but after the kernel generation and compilation phase, I get this other error

```
[ 23%] Building CXX object library/src/CMakeFiles/rocblas.dir/blas3/rocblas_dgmm.cpp.o
/home/ubuntu/rocm-from-source/build/rocBLAS/library/src/tensile_host.cpp:668:37: error: no member named 'LoadLibraryFile' in namespace 'Tensile'
                auto lib = Tensile::LoadLibraryFile<Tensile::ContractionProblem>(path);
                           ~~~~~~~~~^
/home/ubuntu/rocm-from-source/build/rocBLAS/library/src/tensile_host.cpp:668:80: error: expected '(' for function-style cast or type construction
                auto lib = Tensile::LoadLibraryFile<Tensile::ContractionProblem>(path);
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
2 errors generated when compiling for gfx908.
```
@NaveenElumalaiAMD Thank you very much for your detailed instructions. The reason I cannot use the script is that it istalls many dependencies using a packet manager, and we would like to avoid that on a supercomputer, where we would like to have each installation isolated in a custom directory. This allows us for instance, to have multiple versions installed. Would be nice if the script built dependencies from source as well, and allowed to specify a custom installation location.

**Comment by cgmb** [comment]
I'm not sure how you might encounter that error, but I'm not actually a rocBLAS developer. I'll leave you in Naveen's capable hands. Though, there is one thing I wanted to mention before I go...

> The reason I cannot use the script is that it istalls many dependencies using a packet manager, and we would like to avoid that on a supercomputer, where we would like to have each installation isolated in a custom directory. 

I realize this doesn't solve the problem you're reporting, but it's perhaps worth mentioning that AMD contributes build recipes to [Spack](https://spack.readthedocs.io/en/latest/), which exists for the purposes you describe. It compiles all dependencies from source and installs them to isolated directories. It will then [generate module files](https://spack-tutorial.readthedocs.io/en/latest/tutorial_modules.html) to load the packages into your environment.

To build rocblas that way, you would run something like:
```bash
# install dependencies
sudo apt install git build-essential python3
# download spack
git clone https://github.com/spack/spack.git
cd spack
# ensure you're using the same version I am
git checkout 745c191d7362b221875412e640e02db68dedc12d
# load spack into your shell environment
. share/spack/setup-env.sh
# trigger the first-time initialization / query the build plan for rocblas
spack spec rocblas@5.1.0 amdgpu_target=gfx908:xnack- ^mesa~llvm
# build rocblas
spack install rocblas@5.1.0 amdgpu_target=gfx908:xnack- ^mesa~llvm
# load rocblas into your shell environment
spack load rocblas@5.1.0 amdgpu_target=gfx908:xnack- ^mesa~llvm
```

(You might be wondering, "why `^mesa~llvm`?" That's a temporary workaround for [a recent bug](https://github.com/spack/spack/issues/30611).)

**Comment by dipietrantonio** [comment]
@cgmb @NaveenElumalaiAMD In my previous edit I was wrong, I actually hadn't removed `-DTENSILE_USE_MSGPACK=OFF`. Removing that option makes the compilation problem disappear. Probably that compilation path hasn't been followed in a while, @NaveenElumalaiAMD might be worth fixing it.
I almost got to the very end, but still encountering an issue
```
[ 99%] Building CXX object library/src/CMakeFiles/rocblas.dir/check_numerics_matrix.cpp.o
[100%] Linking CXX shared library librocblas.so
Please run this script after at least one build of rocBLAS.
make[2]: *** [library/src/CMakeFiles/rocblas.dir/build.make:3639: library/src/librocblas.so.0.1] Error 1
make[2]: *** Deleting file 'library/src/librocblas.so.0.1'
make[1]: *** [CMakeFiles/Makefile2:204: library/src/CMakeFiles/rocblas.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

@cgmb thanks for the suggestion, we are happy to see AMD contributing directly to Spack. Pawsey Supercomputing Research Centre is adopting Spack for its new supercomputer Setonix. The version of Spack we are testing and building the software stack  is older than the one you use, and support for HIP was still in progress, that is why I started working on this script a while ago. We will use Spack for well established, stable software. We will look into building ROCm with spack in the future too, but for the immediate moment we would like to have more control and less "intermediaries" for several reasons:

1. We learn how ROCm is structured and built
2. With the above knowledge, *should* be easy to fix/adapt a bash install script for any new version / branch. This will allow us to quickly build and test newest versions.
3. We would like to reuse the script to build a custom container.

The "drawback" is that to get to have a full install script takes time and effort. In fact, I am very grateful you helped me with your comment above.

Once we will experiment with the latest Spack, I can contact you to let you know our experience in building rocm with Spack, if you would like!

Best regards
Cristian Di Pietrantonio

**Comment by cgmb** [comment]
Great to see you found the problem! You can disable `header_compilation_tests.sh` by adding `-DRUN_HEADER_TESTING=OFF` or `-DBUILD_TESTING=OFF` to your cmake options.

> we would like to have more control and less "intermediaries"

A man after my own heart. I entirely understand. Supporting a more standard and consistent cmake build experience for power users like yourself has been a matter of discussion recently. The current process is unnecessarily difficult. There's a lot that could be done to improve things, but @NaveenElumalaiAMD, perhaps you could take a look at changing the CMake defaults for [`Tensile_CODE_OBJECT_VERSION`](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/be030feb91fff8d6d2b4409153fe549b81237580/cmake/build-options.cmake#L63) and [`BUILD_TESTING`](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/be030feb91fff8d6d2b4409153fe549b81237580/cmake/build-options.cmake#L35)?

**Comment by NaveenElumalaiAMD** [comment]
Thanks Cory for your prompt response! As we speak, @rkamd is working on changing the CMake defaults and would have a PR to fix this.

**Comment by dipietrantonio** [comment]
@cgmb @NaveenElumalaiAMD  Thank you very much, I was able to go through the build process successfully with your help! When building the rest of the packages I might resort to `ccmake` to see the list of CMake variables I can try to tweak, but as you said, it would be better to improve the Cmake compilation process (which in turn should make it easier for your installer script as well). Also, a list of dependencies would help a lot. 

You can close this issue when you are done. Thanks for the effort put in creating and maintaining ROCm, looking forward to using it.

Kind regards
Cristian Di Pietrantonio

**Comment by NaveenElumalaiAMD** [comment]
@dipietrantonio , a fix for this issue is in the rocBLAS `develop` branch.
I will go ahead and close this ticket. Thanks
