### ISSUE TITLE
[Bug]: Empty variable "python"

### ISSUE THREAD

**Issue by tpkessler** [ROCmSoftwarePlatform/rocBLAS#1254]
### Describe the bug
When trying to build the new ROCm 5.2 release the variable called `python` is not initialized causing `make` to fail right at the beginning:
```
cd [...]/rocBLAS-rocm-5.2.0/library/src && template-proto.py [...]
```
Observe the missing `python` (or `python3`) in front of `template-proto.py`.

I could fix it by adding `-Dpython=python` to the cmake args.

### To Reproduce
1. Call `cmake`
2. followed by `make`

### Expected behavior
`make` finishes without error.

### Log-files
[log.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/9034528/log.txt)

### Environment

| Hardware | description |
|-----|-----|
| CPU | AMD Ryzen 9 5900X 12-Core Processor |
| GPU |  AMD Radeon RX Vega 56|

| Software | version |
|-----|-----|
| rocm-core | v5.2 |
| rocblas | v5.2 |

[environment.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/9034539/environment.txt)

**Comment by cgmb** [comment]
I patched around this in the Spack package, so I might as well upstream my fix.

**Comment by TorreZuk** [comment]
The variable python should always be set by -DCMAKE_TOOLCHAIN_FILE=toolchain-linux.cmake
@tpkessler can you confirm the cmake command you used as I didn't see it in the log.txt.

**Comment by tpkessler** [comment]
Thanks @TorreZuk, I saw that `python` is set in the toolchain file but I didn't know how to include it into the cmake call. Thank you!
