### ISSUE TITLE
Two tile gemm enabling for MI250

### ISSUE THREAD

**Issue by lingjiew93** [ROCmSoftwarePlatform/rocBLAS#1263]
Hi,

Is there a way to make gemm run on two tile of MI250? Seems like only 1 tile is used when running.

**Comment by mahmoodw** [comment]
Hello,

Our MI250 board features 2 Graphics Core Dies (GCDs). If I understand your question correctly, you are interested in running gemm on both GCDs simultaneously?

Currently, rocblas does not support a single gemm call to make use of multiples GCDs. However, you may launch multiple calls on each GCDs manually using separate handles.

The procedure for this is as follows:
1. Make use of [hipSetDevice ](https://rocm-developer-tools.github.io/HIP/group__Device.html#ga43c1e7f15925eeb762195ccb5e063eae)
2. Create handle
3. Make all rocblas calls you'd like on the selected device (This will queue all kernels to the desired device)
4. Repeat steps 1-3 for the second device id

The GCDs use a zero indexing scheme ( 0 and 1 repectively )

Please let me know if you have any other questions.

**Comment by lingjiew** [comment]
Yes, this is the answer I want. Thanks.

**Comment by lingjiew93** [comment]
Yes, this is the answer I want. Thanks. Close this issue.
