### ISSUE TITLE
rocblas_gemm runs very slow at the first time

### ISSUE THREAD

**Issue by MOLOjl** [ROCmSoftwarePlatform/rocBLAS#1270]
An annoying problem occurred to me:
when I use the rocblas_gemm API, it takes more than 20s to return. And if I serially call the same API twice at one program and test the times they cost, the first call will still take more than 20s, but the second one will take less than 0.1s. Furthermore, if I call it a third time or more, the time costs will be similar to the second API call. 
I wonder if there are some warmup processes at the first call that causes the abnormal performance.
If anyone has encountered the same problem, please help me.

**Comment by daineAMD** [comment]
Hi @MOLOjl,

Can you please provide some info on the environment where you're seeing this issue? It would be useful to know which device you're running on, along with the ROCm/rocBLAS version, OS, etc. There's some useful info gathering info in the [bug issue template](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

That being said, there is a startup cost to load gemm kernels, which is what I think the issue you're facing is. You can avoid this startup cost by calling `rocblas_initialize()` outside of time-sensitive portions of your code, there's some documentation a couple of paragraphs down in [the Programmer's Guide](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/docs/source/Programmers_Guide.rst#handle) that might be useful. Also check out some documentation in [rocblas-functions.h](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/library/include/internal/rocblas-functions.h#L18132) regarding `rocblas_initialize()`.

Another note, there have been changes to introduce "lazy loading" of tensile library files which should speed up rocBLAS initialization, see [CHANGELOG.md](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/CHANGELOG.md#added-1). This feature is expected to be in the next release of rocBLAS.

Please let me know if calling `rocblas_initialize()` before calling gemm alleviates your problem, or if you have any further questions.

Thanks,
Daine

**Comment by MOLOjl** [comment]
Thanks a lot！@daineAMD
Calling `rocblas_initialize()` before calling gemm API do works, the startup cost you mentioned transfered to `rocblas_initialize()`.
By the way, the environment I'm using is
```
Device：
[AMD/ATI] Vega 20 [Radeon VII]
System：
ubuntu1~20.04.1
ROCm： 
rocm-core/now 4.5.2.40502-164
rocblas/now 2.41.0.40502-164 amd64
```
I will update my environment when the v2.45 rocblas is released.
Thanks again.
