### ISSUE TITLE
[Bug]: ROCBLAS_LOG_BENCH_PATH env variable broken for rocm 5.2.0

### ISSUE THREAD

**Issue by another-pjohnson** [ROCmSoftwarePlatform/rocBLAS#1272]
### Describe the bug
if ROCBLAS_LOG_BENCH_PATH is set to a value, no file is created and any rocblas-bench outputs are suppressed to std/err streams.

### To Reproduce
Precise version of rocBLAS installed or rocBLAS commit hash if building from source.
1. Install 'rocm' 5.2.0 '...'
2. `ROCBLAS_LOG_BENCH_PATH=rocblas_log_bench.out MIOPEN_ENABLE_LOGGING_CMD=1 ROCBLAS_LAYER=2 AMD_LOG_LEVEL=3 <executable that runs rocblas kernels>`
3. Look for file rocblas_log_bench.out in current directory - directory does not contain file, (or if it already existed it's contents aren't updated)
4. Run same command in `#2` but w/out ROCBLAS_LOG_BENCH_PATH set
5. Observe that the expected rocblas-bench commands appear in std/stderr streams.

### Expected behavior
`rocblas-bench ...` should be output to rocblas_log_bench.out

### Log-files
Add **full** logfiles to help explain your problem.

**Comment by TorreZuk** [comment]
Hello @another-pjohnson can you provide your OS and other information as per the recommendations shown on the new issue template for a bug report as I have to reproduce to advise you?   From MIOPEN_ENABLE_LOGGING_CMD=1 am I to assume you are running MIOpen for this test?  What happens if you just run rocblas-bench does the log file appear where you expect.

**Comment by another-pjohnson** [comment]
OS: Linux, 5.6.13 kernel (with company specific modifications)

GPU ID: 0x740c
PROC: AMD EPYC 7713 64-Core Processor

AFAIK we're not using MIOpen for this test, this was a commandline that someone else from my team was using and I was trying to help them figure out why the rocblas-bench lines were not being emitted. I was able to reproduce the issue with a reduced command line that doesn't include MIOpen:

FAILS (no rocblas_log_bench.out file created, and no rocblas-bench outputs written to console):
```
ROCBLAS_LOG_BENCH_PATH=rocblas_log_bench.out ROCBLAS_LAYER=2 <executable>
```
PASSES (rocblas-bench commands written otu to console)
```
ROCBLAS_LAYER=2 <executable>
```

**Comment by TorreZuk** [comment]
Okay we don't test that OS so we need to dig into this as I just retested with ROCm 5.2 and later builds and it works on Ubuntu and other OS as we actually have a unit test that verifies this system works.
If you are on bash or other can you just export these variables first, e.g. export ROCBLAS_LOG_BENCH_PATH=/tmp/testlog.txt
export ROCBLAS_LAYER=2
Also test you can write first, via "touch /tmp/testFile.txt" or whatever.
Then lets trace and see if the OS didn't like the fopen call, so:
strace ./rocblas-bench -f ger -m 100 --lda 100 -n 100 >& bench_strace.txt   
(again where you have write permission put the strace captured .txt file).
Then look in the trace output and look for the log filename you use and report what you see for the line where it tries to open, something like:
openat(AT_FDCWD, "/tmp/testlog.txt", O_WRONLY|O_CREAT|O_TRUNC|O_APPEND|O_CLOEXEC, 0644) = 8
And then we need to look at the next few lines, failures in setting up the logging system should also report to std::cerr.

**Comment by another-pjohnson** [comment]
Running strace I see the following lines with ROCBLAS_LOG_BENCH_PATH and ROCBLAS_LAYER set via export (prior to strace call):
```
436450 openat(AT_FDCWD, "rocblas_log_bench.out", O_WRONLY|O_CREAT|O_TRUNC|O_APPEND|O_CLOEXEC, 0644) = 7
436451 fstat(7, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
436452 fcntl(7, F_DUPFD_CLOEXEC, 0)            = 8
436453 fcntl(8, F_GETFL)                       = 0x8401 (flags O_WRONLY|O_APPEND|O_LARGEFILE)
436454 rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
436455 clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x145c8c307910, parent_tid=0x145c8c307910, exit_signal=0, stack=0x145c8c107000, stack_size=0x1ff480, tls=0x145c8c307640} => {parent_tid=[563560]}, 88) = 563560
436456 rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
436457 close(7)                                = 0
```

It seems that it is opening the file fine as FD=7, and then is duplicating it to FD=8, then closing FD=7. I do not see any further usages.

The only writes to FD=8 are before the above lines:
```
436300 openat(AT_FDCWD, "/dev/random", O_WRONLY) = 8
436301 write(8, "\360", 1)                     = 1
436302 close(8)                                = 0
436303 openat(AT_FDCWD, "/dev/random", O_WRONLY) = 8
436304 write(8, "\360", 1)                     = 1
436305 close(8)
```

I see no errors written out to stderr that reference roc, amd, or any other related term I could think of.

**Comment by TorreZuk** [comment]
Thanks for the update @another-pjohnson , good to hear that absolute path suffices for you.
