### ISSUE TITLE
Did rocBLAS/Tensile GEMM take advantage of matrix core (like NV's tensor core) on MI200?

### ISSUE THREAD

**Issue by tingxingdong** [ROCmSoftwarePlatform/rocBLAS#1276]

**Comment by NaveenElumalaiAMD** [comment]
Hi @tingxingdong, yes, rocBLAS/Tensile GEMM uses matrix arithmetic instructions on MI200

**Comment by NaveenElumalaiAMD** [comment]
Hi @tingxingdong, I will go ahead and close this issue and feel free to reopen it if you have any further questions.
