### ISSUE TITLE
[Bug]: building client fails because clang-15 cannot find ROCm device library

### ISSUE THREAD

**Issue by alexschroeter** [ROCmSoftwarePlatform/rocBLAS#1280]
### Describe the bug
I am trying to build rocBLAS client to run some benchmarks but when trying to build with `./install.sh -c` I get the following error message:

```
-- Check for working CXX compiler: /opt/rocm/bin/hipcc - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
  The C++ compiler

    "/opt/rocm/bin/hipcc"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/aschroeter/rocBLAS/build/release/CMakeFiles/CMakeTmp

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_5f78f/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_5f78f.dir/build.make CMakeFiles/cmTC_5f78f.dir/build
    gmake[1]: Entering directory '/home/aschroeter/rocBLAS/build/release/CMakeFiles/CMakeTmp'
    Building CXX object CMakeFiles/cmTC_5f78f.dir/testCXXCompiler.cxx.o
    /opt/rocm/bin/hipcc    -o CMakeFiles/cmTC_5f78f.dir/testCXXCompiler.cxx.o -c /home/aschroeter/rocBLAS/build/release/CMakeFiles/CMakeTmp/testCXXCompiler.cxx
    clang-15: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library
    clang-15: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library
    clang-15: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library
    gmake[1]: *** [CMakeFiles/cmTC_5f78f.dir/build.make:78: CMakeFiles/cmTC_5f78f.dir/testCXXCompiler.cxx.o] Error 1
    gmake[1]: Leaving directory '/home/aschroeter/rocBLAS/build/release/CMakeFiles/CMakeTmp'
    gmake: *** [Makefile:127: cmTC_5f78f/fast] Error 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:35 (project)


-- Configuring incomplete, errors occurred!
```

To the best of my knowledge I have working installation of ROCm and don't understand why clang (which should be the one that comes with ROCm) is unable to find the libraries.

### To Reproduce
New OS Ubuntu 22.04.1 LTS
ROCm 5.3.2 installation
git clone rocBLAS
./install.sh -c

### Expected behavior
Building the benchmarking tools.

### Environment
```
Package: rocm-core
Version: 5.3.2.50302-96~22.04
Priority: optional
Section: devel
Maintainer: ROCm Dev Support <rocm-dev.support@amd.com>
Installed-Size: 87.0 kB
Homepage: https://github.com/RadeonOpenCompute/ROCm
Download-Size: 6,114 B
APT-Sources: https://repo.radeon.com/rocm/apt/5.3.2 jammy/main amd64 Packages
Description: Radeon Open Compute (ROCm) Runtime software stack

Package: rocblas
Version: 2.45.0.50302-96~22.04
Priority: optional
Section: devel
Maintainer: rocBLAS Maintainer <rocblas-maintainer@amd.com>
Installed-Size: 1,913 MB
Depends: hip-rocclr (>= 4.0.0), rocm-core
Recommends: rocblas-dev (>=2.45.0.50302)
Download-Size: 43.0 MB
APT-Sources: https://repo.radeon.com/rocm/apt/5.3.2 jammy/main amd64 Packages
Description: rocBLAS is AMD's library for BLAS on ROCm. It is implemented in HIP and optimized for AMD GPUs.
```

[environment.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/9989812/environment.txt)

**Comment by NaveenElumalaiAMD** [comment]
Hi [alexschroeter](https://github.com/alexschroeter), Thank you for reporting a bug. I was able to build rocBLAS successfully in Ubuntu 22.04.1 LTS with ROCm 5.3.2. I was using a docker container not a bare metal. Let me share the steps on how I did it: -
1.	First, downloaded the Ubuntu22.04.1 LTS docker using the command: 
_docker pull ubuntu:22.04_

2.	Then, run the docker image using the command: 
_docker run --device=/dev/dri --device=/dev/kfd --group-add=video --network=host --ipc=host --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v /home/WORKSPACE/:/var/tmp  -i -t ubuntu:22.04 bash_

3.	Followed the instructions here: [how to install ROCm](https://docs.amd.com/bundle/ROCm-Installation-Guide-v5.3.2/page/How_to_Install_ROCm.html) to download and install the ROCm-5.3.2. These are the commands I used:
_sudo apt-get update_

    _wget https://repo.radeon.com/amdgpu-install/5.3.2/ubuntu/jammy/amdgpu-install_5.3.50302-1_all.deb_

    _sudo apt-get install ./amdgpu-install_5.3.50302-1_all.deb_

    _sudo amdgpu-install --usecase=rocm_

4.	Then, cloned the rocBLAS repo using the command: 
_git clone https://github.com/ROCmSoftwarePlatform/rocBLAS.git_

       _cd rocBLAS_

5.	Finally, built rocBLAS using the command:
_./install.sh -dc -a gfx906:xnack-_

      Were, 
      d: Build and install external dependencies
      c: build the rocBLAS-clients
      a: Set GPU architectures

Let me know if you have any questions regarding the above steps I followed, or can clarify how your steps differ, and I would be happy to assist you further.


One more observation is when going through the environment.txt that you have attached, your output to the hipconfig command looks like this:

== hipconfig
HIP_PATH: /opt/rocm-5.3.2
ROCM_PATH: /opt/rocm

This is what hipconfig shows for me:
== hipconfig
HIP_PATH : /opt/rocm-5.3.2
ROCM_PATH : /opt/rocm-5.3.2 

My question here is /opt/rocm a symlink to /opt/rocm-5.3.2? The reason I ask this question is to understand if this ROCm version was installed over a previous version of ROCm or if it was a clean install.

Thanks,
Naveen

**Comment by NaveenElumalaiAMD** [comment]
Hi @alexschroeter, I am glad that you got rocBLAS working from your side, and thank you for closing this issue. It would be nice if you could share with us the original installation process that did not work, So that it would help us to see if we need a fix from our side. Thank you

**Comment by alexschroeter** [comment]
Sure. I manually added the rocm and amdgpu repositories.

```
echo 'deb [arch=amd64] https://repo.radeon.com/amdgpu/5.3.2/ubuntu jammy main' | sudo tee /etc/apt/sources.list.d/amdgpu.list
echo 'deb [arch=amd64] https://repo.radeon.com/rocm/apt/5.3.2 jammy main' | sudo tee /etc/apt/sources.list.d/rocm.list
```
Added the repo keys and installed with

```
sudo apt install rocm-core5.3.2 rocm-hip-libraries5.3.2 rocm-utils5.3.2 rocm-validation-suite5.3.2 rocm-opencl5.3.2 rocm-ml-libraries5.3.2 rocminfo5.3.2 rocm-cmake5.3.2 rocm-developer-tools5.3.2 rocblas5.3.2 rocblas5.3.2-dev rocm-hip-runtime5.3.2 rocm-hip-libraries5.3.2
```

After that followed the instructions on how to build the rocblas client `./install -c`. I believe the packages that fixed the issue were `apt install rocm-hip-sdk5.3.2 rocm-dev5.3.2` which I believe had rocm-device-libs as a dependency and is very much in line with the error message `clang-15: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library`.

Cheers,
Alex
