### ISSUE TITLE
[HIPIFY][ROC][question] Is typecasting of `int` to `rocblas_int` needed?

### ISSUE THREAD

**Issue by emankov** [ROCmSoftwarePlatform/rocBLAS#1281]
There are a lot of rocblas_* functions with `rocblas_int` arguments, while in the corresponding `cuBLAS` functions `int` type is used for the same arguments.

**Should we cast the argument values in the `cuBLAS` functions hipified to `rocBLAS`?**

For instance, consider a hipification of `cublasSetVector` function call to `rocblas_set_vector` function call. Their declarations are as follows:

```cpp
cublasStatus_t CUBLASWINAPI cublasGetVector(int n, int elemSize, const void* x, int incx, void* y, int incy);
ROCBLAS_EXPORT rocblas_status rocblas_get_vector(rocblas_int n, rocblas_int elem_size, const void* x, rocblas_int incx, void* y, rocblas_int incy);
```
Here is a synthetic usage example:
```cpp
int n = 5, num = 1, incx = 3, incy = 3;
void* pX = nullptr;
void* pY = nullptr;
cublasStatus blasStatus;
blasStatus = cublasSetVector(n, num, pX, incx, pY, incy);
```
Here are possible ROC analogues:
1. Without casting:
```cpp
int n = 5, num = 1, incx = 3, incy = 3;
void* pX = nullptr;
void* pY = nullptr;
rocblas_status blasStatus;
blasStatus = rocblas_set_vector(n, num, pX, incx, pY, incy);
```
2. With a C-style casting:
```cpp
int n = 5, num = 1, incx = 3, incy = 3;
void* pX = nullptr;
void* pY = nullptr;
rocblas_status blasStatus;
blasStatus = rocblas_set_vector((rocblas_int)n, (rocblas_int)num, pX, (rocblas_int)incx, pY, (rocblas_int)incy);
```
3. With a functional notation casting:
```cpp
int n = 5, num = 1, incx = 3, incy = 3;
void* pX = nullptr;
void* pY = nullptr;
rocblas_status blasStatus;
blasStatus = rocblas_set_vector(rocblas_int(n), rocblas_int(num), pX, rocblas_int(incx), pY, rocblas_int(incy));
```
I believe (1) is erroneous, so **what do you think about (2) and (3)?**

P.S.
Of course, the following type definition will be taken into account in the output source hipified to roc*, as the corresponding include of `rocblas-types.h` will be in it.
```cpp
#if defined(rocblas_ILP64)
typedef int64_t rocblas_int;
#else
typedef int32_t rocblas_int;
#endif
```

**Comment by TorreZuk** [comment]
rocblas_ILP64 is never defined for any of our standard builds so far, so the 32bit rocblas_int is the same as the int going into cublas.   Even future proofing if you were to use a custom rocblas_ILP64 build the 32 bit int gets promoted by the compiler without information loss.  I don't see any value in adding the casts to rocblas_int but that is just my opinion. 
If you want casts to clearly expose the type name differences and to stay the same for both C and C++ example code then simple enough to use the C style casts for both.

Other parameters do require casts or other translation between rocBLAS and cublas  and that is the purpose of the hipBLAS library to swap between rocblas and cublas with a standardized API.    This sounds like you want to bypass hipBLAS is that a requirement?  hipBLAS has it's own types.

**Comment by emankov** [comment]
Hello @TorreZuk,
And what if `rocblas_ILP64` is defined by the user, or is it impossible due to `rocblas` implementation?
>This sounds like you want to bypass hipBLAS is that a requirement?

Yes, there is a target for hipification directly to rocBLAS as well as to hipBLAS (exclusively). Actually, cuBLAS2rocBLAS is mostly implemented, we're just implementing tests for full coverage.

**Comment by TorreZuk** [comment]
It requires an entire rebuild from source you want to use rocblas_ILP64, so not advised as is not tested.   To say this differently it is NOT for use as an API reinterpretation define.   If user defined it without a private rebuild you would get unresolved symbols and linking error I think.   

Otherwise the cuBLAS2rocBLAS sounds interesting I'll watch for it.

**Comment by emankov** [comment]
Thank you, @TorreZuk, for your explanations. 

Please, let us know if `rocblas_ILP64` becomes alive in the future. 

Nonetheless, the current absence of `int64_t rocblas_int` doesn't cancel type casting during hipification, as `rocblas_int` is syntactically another type, and in the future it might also be semantically different.

Closing the ticket as answered.

**Comment by cgmb** [comment]
> I believe (1) is erroneous, so what do you think about (2) and (3)?

Can you describe a case in which (1) would have incorrect results? To me, it seems like the best option of the three. If you add an explicit cast, then it's no longer possible to discover dangerous narrowing conversions using the `-Wconversion` compiler flag.
