### ISSUE TITLE
[Bug]: pre_checkin_blas1_nan_check failed on Radeon 6700XT

### ISSUE THREAD

**Issue by littlewu2508** [ROCmSoftwarePlatform/rocBLAS#1287]
### Describe the bug
Running `rocblas-test` failed 24=3 * 2 * 4 tests, all belong to pre_checkin_blas1_nan_check: 3 groups (normal, batched, strided_batched), 2 precision (f32_r, f64_r), 4 configurations (1_1_1_1_3, 1_1_1_1_3_t2, 1_1_1_1_3_t3, 1_1_1_1_3_t4)

### To Reproduce
This resultcomes from running `src_test`  in Gentoo `sc-libs/rocBLAS-5.4.2` package. Currently the package is in [this PR](https://github.com/gentoo/gentoo/pull/29319)

In Gentoo system, after merging this PR to gentoo ebuild master tree, run:

```bash
echo 'ACCEPT_KEYWORDS="~amd64"' > /etc/portage/package.accept_keywords
mkdir -p /etc/portage/env /etc/portage/package.use
echo 'FEATURES=test' > /etc/portage/env/test.conf
echo 'sci-libs/rocBLAS test.conf' >> /etc/portage/package.env
echo 'sci-libs/rocBLAS AMDGPU_TARGETS: gfx1031 -gfx90a -gfx908 -gfx906 -gfx1030' > /etc/portage/package.use/99-rocBLAS
emerge sci-libs/rocBLAS
```

### Expected behavior
All tests pass.

### Log-files
The complete build-and-test log is 
[build.log.gz](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/10529198/build.log.gz)

### Environment

| Hardware | description |
|-----|-----|
| CPU | Ryzen 9 5950X |
| GPU |Radeon RX 6700XT |

| Software | version |
|-----|-----|
|kernel| linux 6.1.4|
| llvm/clang| 15.0.6 |
| rocm-core | rocm-5.3.3 |
| rocblas | rocm-5.4.2 |

[environment.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/10529199/environment.txt)

**Comment by amcamd** [comment]
Thank you for reporting this error. The 24 failing rotg tests are corner cases where input scalars a and b are set to NaN. I am working on a fix that improves the rotg tests and removes these failures.

**Comment by amcamd** [comment]
New rotg tests and code are in rocBLAS commit e56d991 . This commit should remove the 24 failing rotg tests.
