### ISSUE TITLE
[Feature]: clarify the supported devices

### ISSUE THREAD

**Issue by jinz2014** [ROCmSoftwarePlatform/rocBLAS#1337]
After building the library with the install.sh, I find the list of available TensileLibrary Files:

gfx803, 900, 906, 908, 90a, 1030, 1100, 1101, 1102. 

Can you please mention that in the install guide for clarity ?

**Comment by rkamd** [comment]
@jinz2014 , 
Information about the supported GPUs, Operating systems etc are provided in [AMD ROCm documentation](https://docs.amd.com/). 
rocBLAS documentation (https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/3356c8063197c4800227ecb716aadc1a7472ff36) has cross-reference to the above link.

**Comment by jinz2014** [comment]
Thanks for your reply.
