### ISSUE TITLE
atomics_allowed always true

### ISSUE THREAD

**Issue by dnikolaev-amd** [ROCmSoftwarePlatform/rocBLAS#1365]
https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/5707660c2b045bf02a098cc1f7a8538b9d94398e/clients/benchmarks/client.cpp#L1697

**Comment by amcamd** [comment]
@dnikolaev-amd   Please try `rocblas-bench --atomics_not_allowed`. The `--atomics_not_allowed` option was added in commit https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/ac81a7df788b803f5f147af41f8b6fa676350a1f .
