### ISSUE TITLE
[Feature]: licensing, use a SPDX license

### ISSUE THREAD

**Issue by bioinfornatics** [ROCmSoftwarePlatform/rocBLAS#1377]
Dear rocblas team,

Thanks for your amazing works.
The license used seems to be a permissive one ( ~ MIT) but not formerly described .
I think that will help everybody to choose one of most known license describe here: https://spdx.org/licenses/
And also help to its usage developer and organization are not expert and the adoption by those people can be higher by using a known license.

Thanks again, have a nice day

**Comment by cgmb** [comment]
The rocBLAS project code is primarily licensed [MIT](https://spdx.org/licenses/MIT.html). The project also contains some code that is licensed [BSD-3-Clause](https://spdx.org/licenses/BSD-3-Clause.html). LICENSE.md merely lists all the licenses used by various files in the project.

**Comment by TorreZuk** [comment]
@bioinfornatics so given that rocBLAS is licensed under MIT license (SPDX = MIT) for which the repo file LICENSE.md details particulars do you need further specifics for your usage or can we close this issue?

**Comment by bioinfornatics** [comment]
Thanks for this  clarification.
We can close the issue, indeed the license file was confusing to me. 
Did you think we can ehance the repo by explicitly list each licensing use for which part? 
Also the icon use by github for licensing is unable to point to the MIT licence 

Anyway thanks for your work.

I wish you a good day

**Comment by TorreZuk** [comment]
Source code files will also include specific copyrights where applicable to help track where individual components had attribution.   We can consider in the future whether we try and summarize this again within the license file.  For now please consider the overall license file first as applicable to the entire library and specific file copyright notices within a file if you wish to research into an attributee.   I'll close this issue but you can reply further if you have further questions on this topic.
