### ISSUE TITLE
Cmake compiler rocBLAS errorr[Feature]: 

### ISSUE THREAD

**Issue by xiaobo1025** [ROCmSoftwarePlatform/rocBLAS#1389]
### Is your feature request related to a problem? Please describe.
First of all, this is the wrong report.
A clear and concise description of what the problem is.
-- OS detected is ubuntu
/usr/bin/python3.8 -m venv /root/workspace/rocBLAS/build/virtualenv --system-site-packages --clear
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt install python3.8-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/root/workspace/rocBLAS/build/virtualenv/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']

CMake Error at cmake/virtualenv.cmake:23 (message):
  1
Call Stack (most recent call first):
  cmake/virtualenv.cmake:49 (virtualenv_create)
  CMakeLists.txt:139 (virtualenv_install)

-- Configuring incomplete, errors occurred!
Then, I use the. 
apt update. 
apt install python3.8-venv. 
Update and install
Fetched 5452 B in 1s (3877 B/s)          
Selecting previously unselected package python3.8-venv.
(Reading database ... 49445 files and directories currently installed.)
Preparing to unpack .../python3.8-venv_3.8.10-0ubuntu1~20.04.9_amd64.deb ...
Unpacking python3.8-venv (3.8.10-0ubuntu1~20.04.9) ...
Setting up python3.8-venv (3.8.10-0ubuntu1~20.04.9) ...
And then, the error is as follows：
raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (setuptools 44.0.0 (/root/workspace/rocBLAS/build/virtualenv/lib/python3.8/site-packages), Requirement.parse('setuptools>=62.4'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
CMake Error at cmake/virtualenv.cmake:68 (message):
  1
Call Stack (most recent call first):
  CMakeLists.txt:139 (virtualenv_install)
Then I use pip install-- upgrade setuptools. 
Update
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 69.0.2
    Uninstalling setuptools-69.0.2:
      Successfully uninstalled setuptools-69.0.2
Successfully installed setuptools-69.0.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: python3 -m pip install --upgrade pip
But,then still report the same error:
 raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (setuptools 44.0.0 (/root/workspace/rocBLAS/build/virtualenv/lib/python3.8/site-packages), Requirement.parse('setuptools>=62.4'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
CMake Error at cmake/virtualenv.cmake:68 (message):
  1
Call Stack (most recent call first):
  CMakeLists.txt:139 (virtualenv_install)
### Library context
| Software | version |
|-----|-----|
| rocblas | v0.0 |

The above Table information can be queried with:
```
Ubuntu/Debian:
dpkg -s rocblas | grep Version
Centos/RHEL:
rpm -qa | grep rocblas
SLES:
zypper se -s | grep rocblas
```

**Comment by rkamd** [comment]
@xiaobo1025,
Thanks for reaching out. Looking at the description, this should have been a bug ticket. 
rocBLAS bug report template provides user to input some key information such as ROCm versions, rocBLAS versions, steps to reproduce etc. to debug an error.

I have tried to compile rocBLAS on a ubuntu and never noticed such version conflict error. Please provide us the steps to reproduce the error, along with environment information. If possible, could you please re-open this as a bug report.

**Comment by xiaobo1025** [comment]
@rkamd Thank you very much for replying to me. I will provide you with complete error information as soon as possible. Thank you very much.

**Comment by rkamd** [comment]
Closing this ticket. If you still have issues, please re-open it as a bug report ticket. Thanks
