### ISSUE TITLE
gfx90c

### ISSUE THREAD

**Issue by hkfuertes** [ROCmSoftwarePlatform/rocBLAS#1398]
Hello, Im trying to run ollama through the gpu but I get this error:
```
rocBLAS error: Cannot read /opt/rocm/lib/rocblas/library/TensileLibrary.dat: Illegal seek for GPU arch : gfx90c
```

Is my card not supported?
Thank you in advance.

PS: Ryzen 7 APU (5800H) Mini PC

**Comment by daineAMD** [comment]
Hi @hkfuertes,

Unfortunately your APU (gfx90c) is not currently supported in ROCm. You can take a look at the supported GPUs in the [ROCM 6.0.2 Documentation](https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.0.2/reference/system-requirements.html#supported-gpus).

[Some people have had some success](https://github.com/ROCm/ROCm/issues/1743#issuecomment-1149902796) using the environment variable `export HSA_OVERRIDE_GFX_VERSION=9.0.0` on similar devices, although running your card with this isn't officially supported.

I hope this helps, let me know if you have further questisons.
Daine

**Comment by hkfuertes** [comment]
Hello, oooh, thank you! I tested it and ollama gives me answers... I need to test if this is faster than CPU, but is a start :)

Thank you for the help, and I understand that this usecase is more suitable for a discrete graphic card.

**Comment by vhbui02** [comment]
@hkfuertes Hi, sorry to necro this post, I am trying to do the same but this workaround doesn't apply to me. I've some speculations but I need your help to confirm it:
- Can you install and run `rocminfo | grep 'Name:'` and show me the name of your architecture? Is it `gfx90c:xnack+` or `gfx90c:xnack-`?
- Are you installing Ollama via Docker with ROCm supported [as specified on Offical Ollama docs](https://github.com/ollama/ollama/blob/main/docs/docker.md#amd-gpu)? Or you install directly into system environment?
- Do you need to install [ROCm for Linux](https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.3.0/install/quick-start.html)?
- Did `HSA_OVERRIDE_GFX_VERSION=9.0.0` the only environment variable you use?

Thank you very much.

**Comment by esohns** [comment]
Hi. I have a similar gfx card (`gfx90c`) and am facing a similar issue.
Using `rocminfo` gives `gfx90c:xnack+`.
I also tried `HSA_OVERRIDE_GFX_VERSION=9.0.6` (because `gfx906` is supposedly supported by ROCm), but that results in
```
ROCm error: CUBLAS_STATUS_INTERNAL_ERROR
  current device: 0, in function ggml_cuda_mul_mat_batched_cublas_impl at /mnt/win_e/lib/whisper.cpp/ggml/src/ggml-cuda/ggml-cuda.cu:1920
  hipblasGemmStridedBatchedEx(ctx.cublas_handle(), HIPBLAS_OP_T, HIPBLAS_OP_N, ne01, ne11, ne10, alpha, src0_ptr, cu_data_type_a, nb01/nb00, sma, src1_ptr, cu_data_type_b, s11, smb, beta, dst_t, cu_data_type, ne0, ne1*ne0, ne12*ne13, cu_compute_type, HIPBLAS_GEMM_DEFAULT)
```
Any ideas ?

**Comment by IMbackK** [comment]
gfx90c can execute code from gfx900 but not gfx906 as gfx906 has lots of instructions gfx90c dosent have. gfx906 is also usually compiled in xnack- mode which wont work on a devices in xnack+ mode. gfx900 on the other hand is usually compiled in xnack any mode which will work regardless of whether it the device is in xnack+ or xnack- mode.

For current versions of rocm amd no longer builds for gfx900 or gfx906, but the code still supports both. To make it work you will thus have to compile rocm yourself (see the rock) or use the rocm packages build by distribution vendors. At least debian, fedora, and arch linux include rocm in their official repository - i would recommend arch.

The simplest way would thus be to just install arch linux install the rocm-hip-sdk package via `pacman -S rocm-hip-sdk` and then run whatever you want with `HSA_OVERRIDE_GFX_VERSION=9.0.0`

**Comment by esohns** [comment]
Hi @IMbackK, thanks for your input.
I managed to get whisper.cpp to run with ROCm support by compiling it for `gfx900` and then running the executable with `HSA_OVERRIDE_GFX_VERSION=9.0.0`. I had to set some variables in the cmake configuration (like e.g.: `CMAKE_HIP_FLAGS=--offload-arch=gfx900` and so on), but now it's running without crashes (as long as I use a `small` model). My GPU only has 512Mb of VRAM and if you load larger models it seems to crash my entire system (Fedora 42). Note that I left GGML_HIP_NO_VMM enabled (that was the default).

**Comment by umpaumpa** [comment]
> Hi [@IMbackK](https://github.com/IMbackK), thanks for your input. I managed to get whisper.cpp to run with ROCm support by compiling it for `gfx900` and then running the executable with `HSA_OVERRIDE_GFX_VERSION=9.0.0`. I had to set some variables in the cmake configuration (like e.g.: `CMAKE_HIP_FLAGS=--offload-arch=gfx900` and so on), but now it's running without crashes (as long as I use a `small` model). My GPU only has 512Mb of VRAM and if you load larger models it seems to crash my entire system (Fedora 42). Note that I left GGML_HIP_NO_VMM enabled (that was the default).

If u have Ryzen(as i have 5700g) with APU u can easy up VRAM to 16GB in BIOS(my BIOS differs from the author of the video, but I still did it successfully,just look for the similar option).
https://youtu.be/H9oaNZNJdrw

**Comment by esohns** [comment]
> > Hi [@IMbackK](https://github.com/IMbackK), thanks for your input. I managed to get whisper.cpp to run with ROCm support by compiling it for `gfx900` and then running the executable with `HSA_OVERRIDE_GFX_VERSION=9.0.0`. I had to set some variables in the cmake configuration (like e.g.: `CMAKE_HIP_FLAGS=--offload-arch=gfx900` and so on), but now it's running without crashes (as long as I use a `small` model). My GPU only has 512Mb of VRAM and if you load larger models it seems to crash my entire system (Fedora 42). Note that I left GGML_HIP_NO_VMM enabled (that was the default).
> 
> If u have Ryzen(as i have 5700g) with APU u can easy up VRAM to 16GB in BIOS(my BIOS differs from the author of the video, but I still did it successfully,just look for the similar option). https://youtu.be/H9oaNZNJdrw

I have a "AMD Ryzen 7 7730U with Radeon Graphics". This is in an ASUS Vivobook Laptop. Unfortunately, the BIOS does not allow me to adjust the VRAM allocated to the GPU.
