### ISSUE TITLE
[Bug]: Unable to build rocBLAS 6.0.2 from source

### ISSUE THREAD

**Issue by RandUser123sa** [ROCmSoftwarePlatform/rocBLAS#1414]
Hello,

I download the source of package and after extract I run the cmake command for configure:

CXX=/opt/rocm-6.0.2/bin/hipcc cmake \
    -DROCM_PATH=/opt/rocm-6.0.2 \
    -DTensile_LOGIC=asm_full \
    -DTensile_ARCHITECTURE=all \
    -DTensile_CODE_OBJECT_VERSION=default \
    -DCMAKE_BUILD_TYPE=Release \
    -DTensile_LIBRARY_FORMAT=yaml \
    -DRUN_HEADER_TESTING=OFF \
    -DTensile_COMPILER=hipcc \
    -DCPACK_SET_DESTDIR=OFF \
    -DCMAKE_INSTALL_PREFIX=rocblas-install \
    -DCPACK_PACKAGING_INSTALL_PREFIX=/opt/rocm-6.0.2 \
    -DCPACK_GENERATOR=TGZ \
    -G "Unix Makefiles" \
    ..

And receive the following error:

[|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||] 100% (9.8 secs elapsed)
-- *** NOTE: blas2/rocblas_ger_kernels.cpp is compiled with the verbose flag -v for QC purposes.
-- Configuring done (134.5s)
CMake Error in virtualenv/lib64/python3.11/site-packages/Tensile/Source/lib/CMakeLists.txt:
  Imported target "hip::device" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in library/src/CMakeLists.txt:
  Imported target "hip::device" includes non-existent path

    "/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

Any suggestion how to fix this error ?

Thanks,
Chris

**Comment by RandUser123sa** [comment]
I figured it out.

**Comment by amcamd** [comment]
Thanks   @RandUser123sa ,  I was going to suggest following build instructions here: https://rocm.docs.amd.com/projects/rocBLAS/en/latest/Linux_Install_Guide.html#build-library-dependencies-client-dependencies-library-client . Did you use the command `install.sh -cd` ?

**Comment by RandUser123sa** [comment]
The problem was the missing PATH to /include directory nothing related to install.sh -cd

**Comment by amcamd** [comment]
Thank you for explanation.
