### ISSUE TITLE
[Feature]: Support for gfx1036

### ISSUE THREAD

**Issue by bitozoid** [ROCmSoftwarePlatform/rocBLAS#1415]
### Is your feature request related to a problem? Please describe.

My GPU is not supported and that is a problem for me. RocBLAS support seems to be required for hipBLAS which is needed for [ollama](https://github.com/ollama/ollama) compilation.

### Describe the solution you'd like

I'd like support for Ryzen 7 7700 (gfx1036).

### Describe alternatives you've considered

None. I can't do that by myself.

### Additional context

```
$ rocminfo
...
*******
Agent 2
*******
  Name:                    gfx1036
  Uuid:                    GPU-XX
  Marketing Name:          AMD Radeon Graphics
  Vendor Name:             AMD
```

### Library context

I'm compiling from source rocBLAS with tag `rocm-6.0.2`, as downloaded from [ROCm suite](https://github.com/ROCm/ROCm). Anyway, I can't find gfx1036 in master or develop branches.

**Comment by amcamd** [comment]
Hello @bitozoid,

Ryzen 7 7700 (gfx1036) is not officially supported by AMD. Please refer to the System Requirement link https://rocm.docs.amd.com/projects/install-on-linux/en/latest/reference/system-requirements.html

Unofficially some people have a workaround by setting environment variable HSA_OVERRIDE_GFX_VERSION=10.3.0 This is not supported by AMD but some have had success with it.

Hope this helps, Andrew

**Comment by cgmb** [comment]
The integrated GPU in the Ryzen 7 7700 has only two compute units. It's really not meant for intense compute workloads. On your hardware, I suspect that the openblas CPU backend for llama-cpp / ollama will provide better performance than the rocblas GPU backend.

**Comment by bitozoid** [comment]
Thank you very much for your comments and your clarification.

It's a pity, I think it would be a starting point to play with ROCm.
