### ISSUE TITLE
Documentation clarification about non-default stream switching

### ISSUE THREAD

**Issue by ye-luo** [ROCmSoftwarePlatform/rocBLAS#1449]
https://rocblas.readthedocs.io/en/master/Programmers_Guide.html#handle says "When a user changes the stream from one non-default stream to another non-default stream, it is the user’s responsibility to synchronize the old stream before setting the new stream."

If the old stream has running kernels unrelated to rocblas and I guarantee all the previous rocblas calls has been followed by hipStreamSynchronize, do I still need to synchronize the stream the old stream before setting a new stream?

Should it be "When a user changes the stream from one non-default stream to another non-default stream, it is the user’s responsibility to complete all the rocblas operations previously submitted using this handle on the old stream before setting the new stream."?

**Comment by rkamd** [comment]
@ye-luo ,
Thank you. We have revised our documentation to include your recommendations. 
commit Id : https://github.com/ROCm/rocBLAS/commit/59663615802cfc31392965e200d294bf72a05ff0
