### ISSUE TITLE
[Feature]: Two tile gemm enabling for MI250

### ISSUE THREAD

**Issue by Alice1069** [ROCmSoftwarePlatform/rocBLAS#1453]
hi, I noticed there is a question ask about 2 years ago? Is it implemented now?
[Two tile gemm enabling for MI250](https://github.com/ROCm/rocBLAS/issues/1263)

"Is there a way to make gemm run on two tile of MI250? Seems like only 1 tile is used when running."

**Comment by TorreZuk** [comment]
@Alice1069 that question was answered and closed by reporter.   The same answer holds true today.   Please clarify your feature request, e.g. are you asking for automatic partitioning of a single GEMM across devices?  That is not currently implemented in rocBLAS and likely would be implemented in another library.

**Comment by Alice1069** [comment]
Thank you very much for your reply, Mi250 has 2 tiles, I mean automatic partitioning of a single GEMM across these 2 tiles, seems your answer is no. so i am good.
