### ISSUE TITLE
rocBLAS_sgemm -- CreateKernel(): Unable to create kernel 

### ISSUE THREAD

**Issue by parallelo** [ROCmSoftwarePlatform/rocBLAS#147]
### What is the expected behavior
-  Caffe runs without error

### What actually happens
```
I1010 17:49:43.093858  1775 caffe.cpp:251] Starting Optimization
I1010 17:49:43.093892  1775 solver.cpp:279] Solving CIFAR10_quick
I1010 17:49:43.093900  1775 solver.cpp:280] Learning Rate Policy: fixed
I1010 17:49:43.094336  1775 solver.cpp:337] Iteration 0, Testing net (#0)

Backtrace:
0x00007fc35b16219d:	Kalmar::HSADevice::CreateKernel(char const*, Kalmar::KalmarQueue*) + 0x1a7d
0x00007fc373246909:	hc::completion_future hc::parallel_for_each<Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08(float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, ihipStream_t*, unsigned int, ihipEvent_t**, ihipEvent_t**)::HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_nam0x00007fc37322f130:	Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08(float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, ihipStream_t*, unsigned int, ihipEvent_t**, ihipEvent_t**) + 0x1e0
0x00007fc373197dd9:	rocblas_sgemm + 0x209
0x00007fc3793202ad:	hipblasSgemm + 0x3d
0x00000000006d35e6:	void caffe::caffe_gpu_gemm<float>(CBLAS_TRANSPOSE, CBLAS_TRANSPOSE, int, int, int, float, float const*, float const*, float, float*) + 0x96
0x0000000000667cd5:	caffe::InnerProductLayer<float>::Forward_gpu(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) + 0x105
0x0000000000438727:	caffe::Layer<float>::Forward(std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&, std::vector<caffe::Blob<float>*, std::allocator<caffe::Blob<float>*> > const&) + 0x2f7
0x0000000000708647:	caffe::Net<float>::ForwardFromTo(int, int) + 0xb7
0x0000000000708570:	caffe::Net<float>::Forward(float*) + 0x20
0x000000000080cb4a:	caffe::Solver<float>::Test(int) + 0x21a
0x000000000080b7d8:	caffe::Solver<float>::Step(int) + 0x3d8
0x000000000080b043:	caffe::Solver<float>::Solve(char const*) + 0x153
0x0000000000435903:	train() + 0x853
0x0000000000439022:	main + 0x1b2
0x00007fc3742cf830:	__libc_start_main + 0xf0
0x0000000000859af9:	_start + 0x29

HSADevice::CreateKernel(): Unable to create kernel Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08 
  CreateKernel_raw=  _ZZ94Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08PfPKfS1_ffjjjjjjjjjjjjjP12ihipStream_tjPP11ihipEvent_tS6_EN67HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_819__cxxamp_trampolineES_jjjjjj
  CreateKernel_demangled=  Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08(float*, float const*, float const*, float, float, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, ihipStream_t*, unsigned int, ihipEvent_t**, ihipEvent_t**)::HIP_kernel_functor_name_begin_unnamed_HIP_kernel_functor_name_end_8::__cxxamp_trampoline(float*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int)
*** Aborted at 1507657783 (unix time) try "date -d @1507657783" if you are using GNU date ***
PC: @     0x7fc3742e4428 gsignal
*** SIGABRT (@0x6ef) received by PID 1775 (TID 0x7fc37b42ab80) from PID 1775; stack trace: ***
    @     0x7fc37a52e390 (unknown)
    @     0x7fc3742e4428 gsignal
    @     0x7fc3742e602a abort
    @     0x7fc35b1622ce Kalmar::HSADevice::CreateKernel()
    @     0x7fc373246909 hc::parallel_for_each<>()
    @     0x7fc37322f130 Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08()
    @     0x7fc373197dd9 rocblas_sgemm
    @     0x7fc3793202ad hipblasSgemm
    @           0x6d35e6 caffe::caffe_gpu_gemm<>()
    @           0x667cd5 caffe::InnerProductLayer<>::Forward_gpu()
    @           0x438727 caffe::Layer<>::Forward()
    @           0x708647 caffe::Net<>::ForwardFromTo()
    @           0x708570 caffe::Net<>::Forward()
    @           0x80cb4a caffe::Solver<>::Test()
    @           0x80b7d8 caffe::Solver<>::Step()
    @           0x80b043 caffe::Solver<>::Solve()
    @           0x435903 train()
    @           0x439022 main
    @     0x7fc3742cf830 __libc_start_main
    @           0x859af9 _start
    @                0x0 (unknown)
Aborted (core dumped)
```

### How to reproduce

In the most recently built hipCaffe image, run this:  
```
./data/cifar10/get_cifar10.sh
./examples/cifar10/create_cifar10.sh
time ./build/tools/caffe train --solver=examples/cifar10/cifar10_quick_solver.prototxt
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | gfx900 |
| CPU |   |

| Software | version |
|-----|-----|
| ROCK |  4.11.0-kfd-compute-rocm-rel-1.6-175 |
| ROCR | 1.1.6-83-g8b72125 |
| HCC | 1.0.17412 |
| Library | 0.7.0.0 |

**Comment by kknox** [comment]
Did you clone this today or yesterday?  We just bumped the version to v0.7.1, but we had a checkin late last night that might have affected this result

**Comment by parallelo** [comment]
This morning.  Grabbed rocblas from the ROCm compute-artifactory site.

**Comment by kknox** [comment]
@guacamoleo 
If he cloned this morning, then I think your PR #145 could be suspect.  Could you do the initial triage.

**Comment by guacamoleo** [comment]
If its from Compute artifactory, wouldn't it be a prior build?

David E. Tanner
_________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

________________________________

**Comment by parallelo** [comment]
Hi @guacamoleo - My previous statement was incorrect.  I actually built all hipCaffe dependencies from source yesterday morning.  Let me kick off another docker-build just to triple-check.

**Comment by guacamoleo** [comment]
We just released a new version of rocBLAS, v0.7.1.0 up from v0.7.0.0. This new release uses assembly kernels for sgemm. However, the complaint is from HSA:CreateKernel() and the kernel name is Cijk_Alik_Bljk_SB_MT016x016x16_GSU08_KLS_NLCA01_NLCB01_PGR1_PLR1_TT04_04_VW01_WG04_04_08_WGM08

the string “KLS” means Kernel_Language=Source, i.e. HIP; and it means you are using the latest rocBLAS; good. So this is a kernel written in HIP and HSA is complaining about “Creating” it. The kernel gets launched using

hipLaunchKernel( HIP_KERNEL_NAME(Cijk_..._WGM08), dim3, dim3, …);

My first guess is that something in the HIP layer or ROCm layer changed.

Kent,
Is this be old kernel launching syntax? Could it have actually been deprecated already in Jeff’s environment?
Could this be an issue with how hipBLAS links in rocBLAS versus how rocBLAS’s own client link in rocBLAS?

Jeff,
Is there anything new or special about your ROCm version?  It ran fine on my maching running 1.6-169 and it ran fine on Jenkins. I think we hard-code in that the library should be compiled for gfx803 and gfx900, I assume you’re using one of those two?

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by parallelo** [comment]
Hi David, 

Just double checked in the docker container -- here was the last commit in the rocBLAS repo:  
```
commit 08e82dc9fc6f957df8858431f1d86175137ec910
Merge: 7815cf7 13ebc11
Author: David Tanner <david.tanner@amd.com>
Date:   Tue Oct 10 09:05:21 2017 -0500

    Merge pull request #145 from guacamoleo/develop
    
    using Tensile v3.2.0 sgemm assembly kernels for gfx803 and gfx900
```
And here are the HIP/HCC details:  
```
# hipconfig --full
HIP version  : 1.4.17405

== hipconfig
HIP_PATH     : /opt/rocm/hip
HIP_PLATFORM : hcc
CPP_CONFIG   :  -D__HIP_PLATFORM_HCC__=   -I/opt/rocm/hip/include -I/opt/rocm/hcc/include

== hcc
HSA_PATH     : /opt/rocm/hsa
HCC_HOME     : /opt/rocm/hcc
HCC clang version 6.0.0 (https://github.com/RadeonOpenCompute/hcc-clang-upgrade.git 86361480a2793cc2e182f55ff28ddaa5a10afc34) (https://github.com/RadeonOpenCompute/llvm.git 6418c1caaf2b99d02ce92a356dbf87765db602ec) (based on HCC 1.0.17412-84a2986-8636148-6418c1c )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
Can't exec "/opt/rocm/hcc/compiler/bin/llc": No such file or directory at /opt/rocm/bin/hipconfig line 132.
HCC-cxxflags :  -hc -std=c++amp -I/opt/rocm/hcc/includeHCC-ldflags  :  -hc -std=c++amp -L/opt/rocm/hcc/lib -Wl,--rpath=/opt/rocm/hcc/lib -ldl -lm -lpthread -lunwind -Wl,--whole-archive -lmcwamp -Wl,--no-whole-archive

=== Environment Variables
PATH=/opt/rocm/opencl/bin:/opt/rocm/bin:/opt/rocm/hcc/bin:/opt/rocm/hip/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HIP_PATH=/opt/rocm/hip
HCC_HOME=/opt/rocm/hcc

== Linux Kernel
Hostname     : c2e40ea41e1f
Linux c2e40ea41e1f 4.11.0-kfd-compute-rocm-rel-1.6-175 #1 SMP Wed Oct 4 00:12:36 CDT 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by guacamoleo** [comment]
Yeah, the rocBLAS portion looks right. So, we have a new rocBLAS running on a new ROCm 1.6-175. If we could try the old rocBLAS (0.7.0.0) on rocm 1.6-175 that would be a great check or run the new rocBLAS on the old rocm (this is what I’ve done and rocBLAS 0.7.1 runs fine on rocm 1.6-169).

Could you try running the old rocBLAS, and seeing if it works?

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by parallelo** [comment]
Hi David, 

Can you suggest a commit to use for the "old" rocBLAS?  I see some older git tags but nothing specifically for 0.7.x.  

Thanks, 

Jeff

**Comment by guacamoleo** [comment]
Oh, snap. We didn’t tag it?

Andrew, can you create a rocBLAS tag for the checkin right before Tensile 3.2 got merged in? Jeff is trying to check why kernel compilation is failing and we want him to check “old” rocBLAS.

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by guacamoleo** [comment]
We have only been tagging the master branch.

Can you use the shar     0ebaedc337ecd431ddd5573f70eb084ea3438058   ? This is for the develop branch just before merging Tensile 3.2

I would like to avoid tagging the develop branch.

Alternatively, use the master branch tag v0.6.0.0. This is the most recent master branch tag, and it is before merging Tensile 3.2.

From: Tanner, David
Sent: Wednesday, October 11, 2017 12:58 PM
To: ROCmSoftwarePlatform/rocBLAS <reply@reply.github.com>; ROCmSoftwarePlatform/rocBLAS <rocBLAS@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Chapman, Andrew <Andrew.Chapman@amd.com>
Subject: RE: [ROCmSoftwarePlatform/rocBLAS] rocBLAS_sgemm -- CreateKernel(): Unable to create kernel (#147)

Oh, snap. We didn’t tag it?

Andrew, can you create a rocBLAS tag for the checkin right before Tensile 3.2 got merged in? Jeff is trying to check why kernel compilation is failing and we want him to check “old” rocBLAS.

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by guacamoleo** [comment]
Is there any difference between rocBLAS 0.6 and 0.7 in terms of gemm?

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

From: Chapman, Andrew
Sent: Wednesday, October 11, 2017 1:13 PM
To: Tanner, David <David.Tanner@amd.com>; ROCmSoftwarePlatform/rocBLAS <reply@reply.github.com>; ROCmSoftwarePlatform/rocBLAS <rocBLAS@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ROCmSoftwarePlatform/rocBLAS] rocBLAS_sgemm -- CreateKernel(): Unable to create kernel (#147)

We have only been tagging the master branch.

Can you use the shar     0ebaedc337ecd431ddd5573f70eb084ea3438058   ? This is for the develop branch just before merging Tensile 3.2

I would like to avoid tagging the develop branch.

Alternatively, use the master branch tag v0.6.0.0. This is the most recent master branch tag, and it is before merging Tensile 3.2.

From: Tanner, David
Sent: Wednesday, October 11, 2017 12:58 PM
To: ROCmSoftwarePlatform/rocBLAS <reply@reply.github.com>; ROCmSoftwarePlatform/rocBLAS <rocBLAS@noreply.github.com<mailto:rocBLAS@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Chapman, Andrew <Andrew.Chapman@amd.com<mailto:Andrew.Chapman@amd.com>>
Subject: RE: [ROCmSoftwarePlatform/rocBLAS] rocBLAS_sgemm -- CreateKernel(): Unable to create kernel (#147)

Oh, snap. We didn’t tag it?

Andrew, can you create a rocBLAS tag for the checkin right before Tensile 3.2 got merged in? Jeff is trying to check why kernel compilation is failing and we want him to check “old” rocBLAS.

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by guacamoleo** [comment]
The highest tag is v0.6.0.0.

There is no difference in the gemm code between commit   0ebaedc337ecd431ddd5573f70eb084ea3438058   and tag v0.6.0.0.  You can check the commits in the link below:

https://github.com/ROCmSoftwarePlatform/rocBLAS/commits/develop


From: Tanner, David
Sent: Wednesday, October 11, 2017 1:52 PM
To: Chapman, Andrew <Andrew.Chapman@amd.com>; ROCmSoftwarePlatform/rocBLAS <reply@reply.github.com>; ROCmSoftwarePlatform/rocBLAS <rocBLAS@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [ROCmSoftwarePlatform/rocBLAS] rocBLAS_sgemm -- CreateKernel(): Unable to create kernel (#147)

Is there any difference between rocBLAS 0.6 and 0.7 in terms of gemm?

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

From: Chapman, Andrew
Sent: Wednesday, October 11, 2017 1:13 PM
To: Tanner, David <David.Tanner@amd.com<mailto:David.Tanner@amd.com>>; ROCmSoftwarePlatform/rocBLAS <reply@reply.github.com>; ROCmSoftwarePlatform/rocBLAS <rocBLAS@noreply.github.com<mailto:rocBLAS@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [ROCmSoftwarePlatform/rocBLAS] rocBLAS_sgemm -- CreateKernel(): Unable to create kernel (#147)

We have only been tagging the master branch.

Can you use the shar     0ebaedc337ecd431ddd5573f70eb084ea3438058   ? This is for the develop branch just before merging Tensile 3.2

I would like to avoid tagging the develop branch.

Alternatively, use the master branch tag v0.6.0.0. This is the most recent master branch tag, and it is before merging Tensile 3.2.

From: Tanner, David
Sent: Wednesday, October 11, 2017 12:58 PM
To: ROCmSoftwarePlatform/rocBLAS <reply@reply.github.com>; ROCmSoftwarePlatform/rocBLAS <rocBLAS@noreply.github.com<mailto:rocBLAS@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Chapman, Andrew <Andrew.Chapman@amd.com<mailto:Andrew.Chapman@amd.com>>
Subject: RE: [ROCmSoftwarePlatform/rocBLAS] rocBLAS_sgemm -- CreateKernel(): Unable to create kernel (#147)

Oh, snap. We didn’t tag it?

Andrew, can you create a rocBLAS tag for the checkin right before Tensile 3.2 got merged in? Jeff is trying to check why kernel compilation is failing and we want him to check “old” rocBLAS.

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by parallelo** [comment]
Just rebuilt with that specific commit, reinstalled, and hit the same type of error.  Other suggestions?

**Comment by guacamoleo** [comment]
That’s terrific; it suggests there’s a problem with rocm 1.6-175 and not with any rocBLAS source code.
The next suggestion is to roll back your rocm version, perhaps to a public released version from repo.radeon.com

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by parallelo** [comment]
Update -- Looks like this is probably related to newer (post-1.6.4) versions of HIP/HCC and how they work with rocBLAS.  I have docker images that might help pinpoint those differences.  

My initial high-priority concern was with the 1.6.4 release, but that doesn't look like an issue.

**Comment by kknox** [comment]
I'm going to close this one, as on the surface it does not appear related to rocblas.  Reopen if the situation changes.
