### ISSUE TITLE
[Bug]: rocblas taking over an hour to install, roclas-bench unavailable after installation

### ISSUE THREAD

**Issue by obhalerao97** [ROCmSoftwarePlatform/rocBLAS#1516]
### Describe the bug
Issue 1: Installing rocblas is taking over an hour on MI300. When running `./install -d`, it gets stuck here for over an hour. 
<img width="631" alt="image" src="https://github.com/user-attachments/assets/105d2c66-67f8-4723-a614-d7dd446d5293">

Issue 2: Once installation is complete and when I run `rocBLAS/scripts/performance/shakespeare.sh`, error thrown: `./rocblas-bench: No such file or directory`
I have tried to locate `rocblas-bench` in `build/release/clients/staging/`, but after installation this is what the folder looks like:
<img width="541" alt="image" src="https://github.com/user-attachments/assets/fb08f7df-9b39-4898-9922-e436d49c54a4">

### To Reproduce
1) Pull container: https://github.com/powderluv/vllm-docs
2) exec into container
3) git clone https://github.com/ROCm/rocBLAS.git
4) cd rocBLAS
5) ./install.sh -d

Tried running it without the container too, but installation fails. 

Issue: rocblas-bench not found anywhere, and it takes over an hour to install.

### Expected behavior
1) I expected the installation to take less than an hour
2) I expected to find the rocblas-bench binary in order to run shakespeare.sh

### Environment
Hardware used: AMD MI300 8 GPUS

<img width="428" alt="image" src="https://github.com/user-attachments/assets/21f5e670-f890-404c-a200-c1c9198cba0d">

| Software | version |
|-----|-----|
| rocm-core | 6.2.0.60200-66~20.04 |
| rocblas | 4.2.0.60200-66~20.04 |

[environment.txt](https://github.com/user-attachments/files/17670374/environment.txt)

**Comment by TorreZuk** [comment]
Hopefully we can solve your problem, but just need to clarify your goals.
Do you really need to build from source, and can't install the pre-built packages?
sudo apt install rocblas
sudo apt install rocblas-clients
See some more details for what you are doing:
https://rocm.docs.amd.com/projects/rocBLAS/en/latest/install/Linux_Install_Guide.html#linux-install

If you need to build and install from source you need the -c for the clients including rocblas-bench.
Use -a gfx942 to cut your rebuild time down significantly if you only want to run on the node for which you provided details.
./install.sh -d -c -a gfx942

**Comment by obhalerao97** [comment]
@TorreZuk , thanks for your prompt response! My main goal is to be able to do: `rocblas-bench -f gemm -r s -m 4000 -n 4000 -k 4000 --lda 4000 --ldb 4000 --ldc 4000 --transposeA N \
  --transposeB T`

with varying precisions and gemm sizes. But it seems like I'm unable to install rocblas-bench in any way.

**Comment by TorreZuk** [comment]
Try the command I mention and let us know how it goes.  It will build rocblas-bench:
./install.sh -d -c -a gfx942

**Comment by TorreZuk** [comment]
Provided information to install pre-built packages and also way to build with significantly lower compute load so I will close issue later this week unless reporter provides feedback.

**Comment by TorreZuk** [comment]
Instructions provided so closing issue

**Comment by shaunpamd** [comment]
Docker image had a conflicting version of GTest.  "GTest_DIR" env var can be use to resolve this.  For example:
GTest_DIR="/usr/local/lib/cmake/GTest/" ./install.sh -d -c -a gfx942

**Comment by shaunclimbon** [comment]
Docker image had a conflicting version of GTest. "GTest_DIR" env var can be use to resolve this. For example:
GTest_DIR="/usr/local/lib/cmake/GTest/" ./install.sh -d -c -a gfx942
