### ISSUE TITLE
find GTest package only if BUILD_CLIENT_TESTS is set to ON

### ISSUE THREAD

**Issue by srinivamd** [ROCmSoftwarePlatform/rocBLAS#1524]
https://github.com/ROCm/rocBLAS/blob/9c5c53cfe6993339e07f9cd6cf824ddcc5695ebf/clients/CMakeLists.txt#L188

Looks like the the above unconditional find package was introduced in `rocm-6.3.0` and it causes cmake failure when trying to build clients with `BUILD_CLIENTS_TESTS OFF`
```
set( BUILD_CLIENTS_TESTS OFF )
```
It would be good to surround it with `if( BUILD_CLIENTS_TESTS ) ...endif()` so it is required only when building tests.

**Comment by TorreZuk** [comment]
Did you find a work around?   We have changed the bench and test clients to reuse a common object files (so we compile once) to speed up the build so it could be selective building now causes trouble.  If you get error again please provide cmake or other build command and error messages and we can consider revisions.
