### ISSUE TITLE
[Compilation issue] Version 6.3 Failed to verify all files in manifest

### ISSUE THREAD

**Issue by RandUser123sa** [ROCmSoftwarePlatform/rocBLAS#1528]
### Describe the bug
I'm trying to compile rocBLAS release version 6.3 and receive error: Failed to verify all files in manifest

### To Reproduce
Try to compile it with following params:
cmake \
    -Wno-dev \
    -D CMAKE_BUILD_TYPE=Release \
    -D CMAKE_CXX_COMPILER=/opt/rocm/llvm/bin/amdclang \
    -D CMAKE_C_COMPILER=/opt/rocm/llvm/bin/amdclang \
    -D CMAKE_TOOLCHAIN_FILE=toolchain-linux.cmake \
    -D CMAKE_INSTALL_PREFIX=/opt/rocm \
    -D CMAKE_PREFIX_PATH=/opt/rocm/llvm/lib/cmake/llvm \
    -D amd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr \
    -D BUILD_WITH_TENSILE=ON \
    -D TENSILE_USE_HIP=ON \
    -D TENSILE_USE_LLVM=ON \
    -D TENSILE_USE_MSGPACK=OFF \
    -D TENSILE_USE_OPENMP=ON \
    -D TENSILE_VENV_UPGRADE_PIP=ON \
    -D Tensile_LIBRARY_FORMAT=yaml \
    -D Tensile_TEST_LOCAL_PATH="/mnt/arch/rocm/rocm-build/build/rocblas/Tensile" \
    -D TENSILE_GPU_ARCHS="gfx803;gfx900;gfx906;gfx908;gfx90a;gfx1010;gfx1011;gfx1012;gfx1030;gfx1031;gfx1032;gfx1034;gfx1035;" \
    -D Tensile_ARCHITECTURE="gfx900;gfx906:xnack-;gfx908:xnack-;gfx90a;gfx1010;gfx1012;gfx1030;gfx1151;" \
    -G "Unix Makefiles" \
    ..

### Expected behavior
The project to be compiled

### Log-files
[compile.txt](https://github.com/user-attachments/files/18107853/compile.txt)

### Environment
```
  Marketing Name:          AMD Ryzen 7 3800X 8-Core Processor 
  Marketing Name:          AMD Radeon RX 7900 XTX
```

| Software | version |
|-----|-----|
| rocm-core | v6.3.0 |
| rocblas | v6.3.0 |

Make sure that ROCm is correctly installed and to capture detailed environment information run the following command:
```
printf '=== environment\n' > environment.txt &&
printf '\n\n=== date\n' >> environment.txt && date >> environment.txt &&
printf '\n\n=== Linux Kernel\n' >> environment.txt && uname -a  >> environment.txt &&
printf '\n\n=== rocm-smi' >> environment.txt && rocm-smi  >> environment.txt &&
printf '\n\n' >> environment.txt && hipconfig  >> environment.txt &&
printf '\n\n=== rocminfo\n' >> environment.txt && rocminfo  >> environment.txt &&
printf '\n\n=== lspci VGA\n' >> environment.txt && lspci | grep -i vga >> environment.txt
```

Attach `environment.txt`
[environment.txt](https://github.com/user-attachments/files/18107849/environment.txt)

**Comment by RandUser123sa** [comment]
It's seems the problem are in Tensile, without it it's compiled successful. I report the problem to Tensile repo you can close the issue if you decide is closed.

**Comment by TorreZuk** [comment]
We had a glitch with Tensile branch promotion so I would ensure you use the matching 6.3 rocblas tensile commit as set in tensile_tag.txt.  So checkout commit aca95d1743c243dd0dd0c8b924608bc915ce1ae7 in the Tensile repo and test again.   There is a Tensile issue already for this and hopefully it will be fixed shortly.

**Comment by RandUser123sa** [comment]
It's not working, the same result:

[  0%] Verifying files in /mnt/arch/rocm/rocm-build/build/rocblas/Tensile/library/TensileManifest.txt were generated
UserWarning: HardwareMonitor currently disabled for gfx941, gfx942, gfx1100, gfx1101, gfx1102, gfx1200, gfx1201
Failed to verify all files in manifest
make[2]: *** [library/src/CMakeFiles/TENSILE_LIBRARY_TARGET.dir/build.make:71: library/src/CMakeFiles/TENSILE_LIBRARY_TARGET] Error 255
make[1]: *** [CMakeFiles/Makefile2:427: library/src/CMakeFiles/TENSILE_LIBRARY_TARGET.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

You could close the case if you decide is resolved. I remove the line from Tensile which verify files and rocBLAS was compiled with no errors.

**Comment by TorreZuk** [comment]
So the release/rocm-rel-6.3 branch was corrected as it didn't match the official release commit in rocblas repo set in tensile_tag.txt.  However as it didn't help you, I think the Tensile issue you made https://github.com/ROCm/Tensile/issues/2063 is the best place for this investigation to continue as it is a Tensile side problem and not rocblas one.  Thus I'll close this issue. Thanks for your feedback!

**Comment by RandUser123sa** [comment]
Just to update, I found what causing the error. I was start own virtual environment for python before start build rocBLAS and rocBLAS also start the second virtualenv and they are mixed and causing the error.

**Comment by TorreZuk** [comment]
Thanks for letting us know
