### ISSUE TITLE
Wiki problem - Example C code calling rocBLAS routine

### ISSUE THREAD

**Issue by Dekken** [ROCmSoftwarePlatform/rocBLAS#160]
The links for:

    "Example C code calling rocBLAS routine"

Don't go anywhere but let the "clickee" write the page themselves - perhaps not what was desired.

**Comment by kknox** [comment]
Fixed. Thanks for the heads up.

**Comment by tingxingdong** [comment]
@Dekken , I do not understand what you are trying to say.
