### ISSUE TITLE
Issue: “Error: There is no device can be used to do the computation”, while executing MXNet tests on HIP/CUDA path after integrating rocBLAS

### ISSUE THREAD

**Issue by sriharikarnam** [ROCmSoftwarePlatform/rocBLAS#185]
**Issue Summary**
Facing runtime issues on integrating rocBLAS to MXNet library--“error: There is no device can be used to do the computation”.  (Test cases terminate after throwing this error)
Tests are executed on HIP/CUDA (NVCC path).
If we use cuBLAS in place of rocBLAS, this issue doesn't appear.

**Steps to reproduce:** 
1)clone mxnet 
$  git clone --recursive https://github.com/ROCmSoftwarePlatform/mxnet 

2)steps to build mxnet 
    $ cd mxnet
    $ export HIP_PLATFORM=nvcc
    $ make -j(nproc)

3) Install Mxnet 
    $ cd python 
    $ sudo python setup.py

4) Test case to run
     $ cd ../example/adversary
     $ python adversary_generation.py

**Error Log:**
[13:07:58] src/io/iter_mnist.cc:94: MNISTIter: load 60000 images, shuffle=1, shape=(100,1,28,28) 
[13:07:58] src/io/iter_mnist.cc:94: MNISTIter: load 10000 images, shuffle=1, shape=(100,1,28,28) 
There is no device can be used to do the computation

**Analysis:** Though the error indicates absence of device, the gpu is being detected. The image of nvidia-smi log has been attached. 
![nvidia-smi](https://user-images.githubusercontent.com/25496668/34143878-f117eebc-e4b4-11e7-98b3-7c8ec4c2054e.png)

**Comment by guacamoleo** [comment]
rocBLAS doesn’t run on nvidia devices; it only runs on AMD devices. I don’t know who’s printing out “There is no device can be used to do the computation” but I do know that recent rocBLAS only has amd assembly kernel, so that certainly wouldn’t run on nvidia.

David E. Tanner
_________________________________________________________________________________
MTS Software Engineer  |   Radeon Technologies Group – Open Compute

**Comment by kknox** [comment]
@sriharikarnam 
There has been work to get rocBLAS to work with a CUDA backend, but it is incomplete.  The cmake build infrastructure is upgraded, but our kernel architecture needs more work.  

Did you install rocblas from a .deb?  The AMD or CUDA backend is chosen at compile time, and I'm sure that if you installed from a debian it was pre-compiled for an AMD backend.

I would recommend using [hipBLAS](https://github.com/ROCmSoftwarePlatform/hipBLAS) instead for now.  It's a marshaling library, meaning it marshals inputs and outputs from either cuBLAS or rocBLAS, which does the real work.  It's a thin layer, adds essentially 0 overhead, and you get the vendor optimized performance underneath for each respective platform.
