### ISSUE TITLE
Build on internal version of ROCm?

### ISSUE THREAD

**Issue by QWU-AMD** [ROCmSoftwarePlatform/rocBLAS#214]
Hi,

Our team is trying to build the rocBLAS on our machines with the internal ROCm version installed. Because the internal ROCm version is not signed, the current rocBLAS install.sh will exit non-zero on 'sudo apt update'. I wonder if it is possible we can build the rocBLAS on the latest ROCm bits?'

Thanks,
Qiyu

**Comment by Dekken** [comment]
Pretty sure it is now

**Comment by gstoner** [comment]
For the internal ROCm build, issues you contact ROCm team The team sit under Ajit Mathews
