### ISSUE TITLE
How the max theory peak can be achieved of rocBlas or MIOpenGEMM?

### ISSUE THREAD

**Issue by XiuYuLi** [ROCmSoftwarePlatform/rocBLAS#245]
This my gemm library optimizated for vega-gpu : https://github.com/XiuYuLi/vgemm

**Comment by bragadeesh** [comment]
Hello,
Thank you for reaching out to us. Your repo has content in Chinese that I cannot follow. Do you have performance graphs showing your claim?

**Comment by XiuYuLi** [comment]
My english is bad :)

This my some test,I found the performance is similar the VALUBusy(about -%1+ drop).
Some routines not yet optimizated finally,I'll going to do that later.
Some routines of current vgemm version need to padding with column for max performance,but i will try eliminate this restrict.

Notes:
    1   The mixed and half precision using packed column/row(two column or two row packed to one), 
    if no packed the half precision version will be faster than the packed version;
    the reason for this is to effective support for convolution later; In fact.

    2   In the AMD OpenCL Optimization Guide, said that can be achieved max performance of LDS if each iterm access 8bytes,but in the
    case of gemm is not this for some routines, e.g:sgemm*_128x128, because the max offset of ds_read2_b64 and ds_write2_b64 is 256 and
    need more xor and add instrcutions and drop the performance.I test the other routines, use 8byte access or not use no differencts.

Question: How much memory channels in vega64? There`s no information can be found.

8192x8192:
sgemmcr_128x128                            : VALU Utility:100%,  VALUBusy:96.50% (some sizes can be achieved 96.60% and some actualizing with specific conditional constraint can be achieved 97+%)
xgemmcr_128x128                            : VALU Utility:100%,  VALUBusy:98.05%
xgemmcr_64x64                                : VALU Utility:100%,  VALUBusy:97.78%
xgemmcc_64x64(padding  64bytes)   : VALU Utility:100%,  VALUBusy:97.14%
hgemmcr_64x64(padding 128bytes)  : VALU Utility:100%,  VALUBusy:95.62%
hgemmcc_64x64(padding  64bytes)   : VALU Utility:100%,  VALUBusy:95.14%
hgemmcr_128x128                            : VALU Utility:100%,  VALUBusy:96.20%
hgemmcr_256x128                            : VALU Utility:100%,  VALUBusy:96.53%

6144x6144:
sgemmcr_128x128                           : VALU Utility:100%,  VALUBusy:96.27%
xgemmcr_128x128                           : VALU Utility:100%,  VALUBusy:97.79%
xgemmcr_64x64                               : VALU Utility:100%,  VALUBusy:97.50%
xgemmcc_64x64(padding  64bytes)  : VALU Utility:100%,  VALUBusy:96.86%
hgemmcr_64x64(padding  64bytes)  : VALU Utility:100%,  VALUBusy:94.92%
hgemmcc_64x64(padding  64bytes)  : VALU Utility:100%,  VALUBusy:95.14%
hgemmcr_128x128                           : VALU Utility:100%,  VALUBusy:95.10%
hgemmcr_256x128                           : VALU Utility:100%,  VALUBusy:96.00%

4096x4096:
sgemmcr_128x128                           : VALU Utility:100%  ,  VALUBusy:95.44%
xgemmcr_128x128                           : VALU Utility:100%  ,  VALUBusy:97.16%
xgemmcr_64x64                               : VALU Utility:100%  ,  VALUBusy:96.68%
xgemmcc_64x64(padding  64bytes)  : VALU Utility:99.99%,  VALUBusy:96.05%
hgemmcr_64x64                               : VALU Utility:100%  ,  VALUBusy:94.42%
hgemmcc_64x64(padding  64bytes)  : VALU Utility:100%  ,  VALUBusy:93.90%
hgemmcr_128x128                           : VALU Utility:100%  ,  VALUBusy:91.92%
hgemmcr_256x128                           : VALU Utility:100%  ,  VALUBusy:94.55%
