### ISSUE TITLE
Installing rocBLAS

### ISSUE THREAD

**Issue by justxi** [ROCmSoftwarePlatform/rocBLAS#359]
### What is the expected behavior
Complete configuration and build of rocBLAS

### What actually happens
1) Python2.7 is not detected on a system where Python3.x is default.
2) Header files are missing while build: Tensile.h, etc. in "build/release/Tensile"

### How to reproduce
Checkout rocBLAS and follow these instruction: https://github.com/ROCmSoftwarePlatform/rocBLAS/wiki/1.Build#build-dependencies--library-using-individual-commands

### Environment
| Hardware | description |
|-----|-----|
| GPU | Ryzen7 1800x |
| CPU | Radeon RX 560 |

| Software | version |
|-----|-----|
| ROCK | v1.9 |
| ROCR | v1.9 |
| HCC | v1.9 |
| rocBLAS | development branch |

My solution:
1) I installed "Tensile" but it is not detected, is there an envirment variable needed?
In the mean time I modified "cmake/virtualenv.cmake":
```
-# find_package(PythonInterp)
+find_package(PythonInterp 2.7 REQUIRED)
 # # TODO: Check PYTHON_VERSION_MAJOR
 
-find_program(VIRTUALENV_PYTHON_EXE python)
+find_program(VIRTUALENV_PYTHON_EXE python2.7)

```
2) add the path:
```
   set( Tensile_INC
     ${CMAKE_CURRENT_SOURCE_DIR}/blas3/Tensile
+    ${CMAKE_BINARY_DIR}/Tensile
   )
 endif( )

```
With these changes I can configure and build rocBLAS.

**Comment by iChant** [comment]
Same problem. Thanks a lot for your solution!

**Comment by justxi** [comment]
This seems not to be necessary in the latest ROCm  branches.

**Comment by justxi** [comment]
This issue seems to be applied.
