### ISSUE TITLE
Using cmake find_package(rocblas) does not report the library

### ISSUE THREAD

**Issue by justxi** [ROCmSoftwarePlatform/rocBLAS#364]
### What is the expected behavior
-  Using the CMakeLists.txt:
cmake_minimum_required(VERSION 3.9)
find_package( rocblas )
message( ${rocblas_INCLUDE_DIRS} )
message( ${rocblas_LIBRARIES} )

should report include directories and libraries

### What actually happens
-  "cmake" gives the following output:

/usr/rocblas/include
rocblas-targets

### How to reproduce
- Run a cmake configuration with find_package(rocblas)  

| Software | version |
|-----|-----|
| ROCK | v1.9 |
| ROCR | v1.9 |
| HCC | v1.9 |
| rocBLAS | development branch |

**Comment by pfultz2** [comment]
Thats because this line [here](https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/library/src/CMakeLists.txt#L199) needs to list the exported targets(ie `roc::rocblas`) and not the target file.

I should probably add some extra checks in rocm-cmake for this.

**Comment by justxi** [comment]
Now it reports "roc::rocblas" instead of "rocblas-targets" is this correct?

**Comment by justxi** [comment]
My fault, must be something like this:

get_target_property(var roc::rocblas INTERFACE_INCLUDE_DIRECTORIES)
message("INTERFACE_INCLUDE_DIRECTORIES:")
foreach(line IN LISTS var)
    message("${line}")
endforeach()
