### ISSUE TITLE
No complex double supoort

### ISSUE THREAD

**Issue by chentianran** [ROCmSoftwarePlatform/rocBLAS#367]
### What is the expected behavior
-  Export complex double functions

### What actually happens
-  No complex double support in v1.9

**Comment by toxa81** [comment]
also discovered this today

**Comment by eadren** [comment]
> ### What is the expected behavior
> * Export complex double functions
> 
> ### What actually happens
> * No complex double support in v1.9

Could you show a complex single demo yaml config ?

**Comment by ye-luo** [comment]
Need complex float and double support. Particularly gemv, ger, gemm and batched versions.
