### ISSUE TITLE
rocBlas might select underperforming blas kernels

### ISSUE THREAD

**Issue by Delaunay** [ROCmSoftwarePlatform/rocBLAS#579]
I found the error when comparing a MI50 using rocm2.5 and a RadeonVII using rocm2.4.
The RadeonVII had much better performance under rocm2.4.
Using the rocm-profiler I found the both GPUs were calling a different blas kernel.
RadeonVII was calling a much faster one (7x faster).
When upgrading to rocm2.5 the RadeonVII started calling the slower kernel.

### How to reproduce
- using pytorch provided [example][1] using `batch_size=256` line 33. The batch size is important the issue disappears with batch-size=2048.
-  `python main.py`

The script makes two calls to rocblas. The first call is the offending one.
- `./rocblas-bench -f gemm -r f32_r --transposeA T --transposeB N -m 256 -n 1 -k 4 --alpha 1 --lda 4 --ldb 4 --beta 1 --ldc 256`
- `./rocblas-bench -f gemm -r f32_r --transposeA N --transposeB N -m 4 -n 1 -k 256 --alpha 1 --lda 4 --ldb 256 --beta 0 --ldc 4`

On a RadeonVII with rocm2.4 the first one will translate to
- `Cijk_Ailk_Bljk_SB_MT16x16x16_SE_APM1_AF0EM1_AF1EM1_AMAS1_ASEM1_BL1_DTL0_EPS1_FL0_GRVW2_GSU4_ISA906_IU1_K1_KLA_LPA0_LPB0_LDL1_MGWVW1_NLCA1_NLCB1_PK0_PGR1_PLR1_RK0_SU32_SNLL0_TT2_2_USFGRO1_VAW1_VW2_WG8_8_4_WGM1`
- NB: **`ISA906`**

While on MI50 with rocm2.5 it will translate to

- `Cijk_Ailk_Bljk_SB_MT32x32x2_SE_APM1_AF0EM1_AF1EM1_AMAS2_ASEM1_BL0_DTL0_EPS0_FL0_GRVW4_GSU1_ISA000_IU1_K1_KLS_LPA0_LPB0_LDL1_MGWVW1_NLCA1_NLCB1_PK0_PGR1_PLR1_RK0_SU32_SNLL0_TT4_4_USFGRO0_VAW1_VW4_WG8_8_1_WGM1`
- NB: **`ISA000`**

Unfortunately I was not able to compile rocblas-bench but using the profiler I found
the performance values below for the offending kernel.

| GPU | DurationNs |  ROCBlas Version |
|--------|-----------------|------------|
| MI50  - gfx906         | 59363.84  | 2.2.6 d8417e9-dirty |
| Radeon VII - gfx906 |  8589.28   | 2.2.5 49ec204-dirty |
| Radeon VII - gfx906 |  57458.24   | 2.2.6 d8417e9-dirty  |

More details here
[merged_rocprof.xlsx](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/3272625/merged_rocprof.xlsx)

#### MI50 Machine
 
Package | OS | OS_version | package_version | arch 
-- | -- | -- | -- | --
rocblas | Ubuntu | 16.04,now | 2.2.6.0 | amd64
rock-dkms | Ubuntu | 16.04,now | 2.5-27 | all
rocm-clang-ocl | Ubuntu | 16.04,now | 0.4.0-7ce124f | amd64
rocm-dev | Ubuntu | 16.04,now | 2.5.27 | amd64
rocm-device-libs | Ubuntu | 16.04,now | 0.0.1 | amd64
rocm-dkms | Ubuntu | 16.04,now | 2.5.27 | amd64
rocm-libs | Ubuntu | 16.04,now | 2.5.27 | amd64
rocm-opencl | Ubuntu | 16.04,now | 1.2.0-2019060327 | amd64
rocm-opencl-dev | Ubuntu | 16.04,now | 1.2.0-2019060327 | amd64
rocm-utils | Ubuntu | 16.04,now | 2.5.27 | amd64

[1]: https://github.com/pytorch/examples/blob/master/regression/main.py

**Comment by Delaunay** [comment]
This is related to https://github.com/ROCmSoftwarePlatform/pytorch/issues/398 in particular https://github.com/ROCmSoftwarePlatform/pytorch/issues/398#issuecomment-500838355 which highlights that ROCm 2.5 worsen the performance for a class of dgemm problems

**Comment by Delaunay** [comment]
Pretty much the same numbers with ROCm2.9.
The performance comparison can be found [here][1].
with the configuration below losing all the performance gain from 2.5.

[1]: https://docs.google.com/spreadsheets/d/1dYD7Cys4FOVEaCeRu1XRxuEHPOye518WCmrXC6-xsuE/edit#gid=0

b | h | o
-- | -- | --
35 | 8457 | 1760
35 | 8457 | 2048
35 | 8457 | 2560
35 | 8457 | 4096
64 | 1 | 1216
128 | 1 | 1024
128 | 1 | 1408

**Comment by amdkila** [comment]
Hi @Delaunay, first of all apologies for the lengthy delay. I am looking into this now. Your results seem to be somewhat similar to the performance difference that I've seen between MI-50 and MI-60 GPUs, with MI-60 choosing a faster kernel.  I chalked that up to the additional CUs, but MI-50 and Radeon 7 both have 60 CUs, so it sounds like selecting a slower solution like you mentioned. 

I've not compared performance dips over rocm versions, however. There's a bug that others have reported that prevent rocblas-bench from being built using rocm2.6 or lower, so that will be a bit tricky to reproduce. I'll try to improve the performance for your kernels in rocm2.9. Is it just the 2 rocblas-bench calls that you highlighted above?

**Comment by Delaunay** [comment]
IIRC, of the two only `./rocblas-bench -f gemm -r f32_r --transposeA T --transposeB N -m 256 -n 1 -k 4 --alpha 1 --lda 4 --ldb 4 --beta 1 --ldc 256` is significantly slower.

**Comment by amdkila** [comment]
@Delaunay for the MI50, it looks like a source kernel was selected as the ideal solution (hence ISA 000), which isn't correct. Can you check /usr/share/misc/pci.ids if on Ubuntu or /usr/share/hwdata/pci.ids if on CentOS/RHEL and let me know your GPU's Device ID/Number (ex. 9999) and the corresponding alias (ex. Vega 10) is.  

We've seen an issue in the past where the Device ID or the alias for the GPU is not available in our rocblas configs (yaml files), and if that's the case for your GPU, we have to add that to all the corresponding yaml files.

**Comment by Delaunay** [comment]
I am not too sure what you need so I saved all I could think of

[pci.ids.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/3809829/pci.ids.txt)
[rocminfo.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/3809831/rocminfo.txt)
[lspci.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/3809864/lspci.txt)
[lspci-k.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/3810032/lspci-k.txt)

* from `lspci -k`  device ID 0834 
* from rocm-smi device ID 0x66a1 
Both seems to be the uniquely identifying the MI50 32Go

```
(base) test@testamd:~$ rocm-smi --showproductname 
========================ROCm System Management Interface========================
================================================================================
GPU[1]          : Card series:          Vega 20
GPU[1]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[1]          : Card SKU:             D16317
GPU[2]          : Card series:          Vega 20
GPU[2]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[2]          : Card SKU:             D16317
GPU[3]          : Card series:          Vega 20
GPU[3]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[3]          : Card SKU:             D16317
GPU[4]          : Card series:          Vega 20
GPU[4]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[4]          : Card SKU:             D16317
GPU[5]          : Card series:          Vega 20
GPU[5]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[5]          : Card SKU:             D16317
GPU[6]          : Card series:          Vega 20
GPU[6]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[6]          : Card SKU:             D16317
GPU[7]          : Card series:          Vega 20
GPU[7]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[7]          : Card SKU:             D16317
GPU[8]          : Card series:          Vega 20
GPU[8]          : Card vendor:          Advanced Micro Devices, Inc. [AMD/ATI]
GPU[8]          : Card SKU:             D16317
================================================================================
==============================End of ROCm SMI Log ==============================
```


```
rocm-smi -i

========================ROCm System Management Interface========================
================================================================================
GPU[1]          : GPU ID: 0x66a1
GPU[2]          : GPU ID: 0x66a1
GPU[3]          : GPU ID: 0x66a1
GPU[4]          : GPU ID: 0x66a1
GPU[5]          : GPU ID: 0x66a1
GPU[6]          : GPU ID: 0x66a1
GPU[7]          : GPU ID: 0x66a1
GPU[8]          : GPU ID: 0x66a1
================================================================================
==============================End of ROCm SMI Log ==============================
```

**Comment by amdkila** [comment]
That's good, thank you. So, my hunch was wrong about this being a Device ID that hasn't been added to the rocblas config files- 66a1 is added to all vega20 yaml files. Anyway, we have a tuning mechanism that improves performance for rocblas-bench calls. I'll try that and will get back to you by the end of the day.

**Comment by amdkila** [comment]
@Delaunay I have created a PR [here](https://github.com/ROCmSoftwarePlatform/rocBLAS/pull/782) that should fix the issue you're having. I tuned on Radeon 7, which per your profiler results seems to have the same problem. I was working on rocm2.9 as well.

**Comment by amdkila** [comment]
@Delaunay can you confirm that the issue has been fixed? Try out the latest rocBLAS-develop branch. Once you've had a chance to do that, I will close the issue.

**Comment by Delaunay** [comment]
I do not have access to AMD GPUs at the moment.
I will close the issue for now and will reopen it if it persists.
Thanks!
