### ISSUE TITLE
Installation (./install.sh -d) freezes rocm-terminal docker instance

### ISSUE THREAD

**Issue by settle** [ROCmSoftwarePlatform/rocBLAS#608]
### What is the expected behavior
-  System remains stable and successfully completes compilation

### What actually happens
-  System freezes before compilation successfully completes, requiring a hard power reset

### How to reproduce
-  sudo apt-get update
-  sudo apt-get install docker.io
-  sudo docker run --rm -it rocm/rocm-terminal:2.5
-  sudo apt-get update
-  sudo apt-get install gcc-gfortran
-  git clone https://github.com/ROCmSoftwarePlatform/rocBLAS.git
-  cd rocBLAS
-  ./install.sh -d

### Environment
-  HP dv6 laptop
-    GPU - NVIDIA GeForce GT 650M
-    CPU - Intel Core i7-3630QM
-    OS - Ubuntu 18.04.2
-    Docker Container - rocm-terminal:2.5

**Comment by saadrahim** [comment]
How much system RAM do you have? It is possible you are running out and crashing your system. I recommend 32GB to compile rocBLAS.
