### ISSUE TITLE
race condition of device_matrix_copy() and device_strided_batched_matrix_copy()

### ISSUE THREAD

**Issue by scxiao** [ROCmSoftwarePlatform/rocBLAS#685]
### What is the expected behavior
-  Matrix C is supported to be copied to D correctly by calling the function hipMemcpy() in the function device_strided_batched_matrix_copy() and device_matrix_copy().
    We should replace the hipMemcpy() with the async version hipMemcpyAsync() to ensure computation and memory copy happen in the same stream.

### What actually happens
-  There is race condition between the memory copy and the later gemm computation. 

### How to reproduce
-  

### Environment
| Hardware | description |
|-----|-----|
| GPU | device string |
| CPU | device string |

| Software | version |
|-----|-----|
| ROCK | v0.0 |
| ROCR | v0.0 |
| HCC | v0.0 |
| Library | v0.0 |

**Comment by leekillough** [comment]
Moved to JIRA
