### ISSUE TITLE
BUG: A sgemm case triggers memory page fault on gfx906

### ISSUE THREAD

**Issue by ghostplant** [ROCmSoftwarePlatform/rocBLAS#793]
GPU device: gfx906;

Updating DIM1, DIM2 and DIM3 to 1024, 2, 7680 respectively can easily replay the bug that crashes on gfx906:
https://github.com/ROCmSoftwarePlatform/rocBLAS/blob/develop/clients/samples/example_sgemm.cpp

Crash Case:   `M=1024, N=2, K=7680, tA = N, tB = T`

**Comment by ghostplant** [comment]
Rocblas Version: installed from prebuild rocm-2.9.0

**Comment by bragadeesh** [comment]
Please reopen if this is still an issue after trying rocm 3.7
