### ISSUE TITLE
Prebuilt ROCm libraries

### ISSUE THREAD

**Issue by zjin-lcf** [ROCmSoftwarePlatform/rocBLAS#802]
I don't have sudo permission. I found installing these ROCm libraries (e.g. ROCmBLAS) in my home directories are painful and slow when the OS is CentOS. Could you please consider providing prebuilt libraries for users who do not have sudo permission ?

Thank you

**Comment by bragadeesh** [comment]
Pleasse report the issue here: https://github.com/RadeonOpenCompute/ROCm
