### ISSUE TITLE
ubuntu 18.04 cannot build rocBLAS with ROCm 2.10

### ISSUE THREAD

**Issue by zjunweihit** [ROCmSoftwarePlatform/rocBLAS#840]
### What is the expected behavior
-  install.sh could build rocBLAS successfully

### What actually happens
-  get stuck in the middle
```
0         1
012345678901234
..########|||..
0         1
01234567890123456
..########|||..||
info: growing pool += 2 * 2 for GlobalWrite

0         1         2
012345678901234567890123456789
................#########||..|
0         1         2         3
0123456789012345678901234567890
................#########||..||
info: growing pool += 2 * 2 for GlobalWrite

0         1         2
012345678901234567890123456789
................#########||..|
0         1         2         3
0123456789012345678901234567890
................#########||..||
(get stuck here)
```

### How to reproduce
-  install ROCm 2.10
- git clone rocBLAS 2.10 or 2.10.1 branch
- ./install.sh

### Environment
| Hardware | description |
|-----|-----|
| GPU | vega20  |
| CPU | Intel i7-8700K 3.7GHz 12 CPUs |

| Software | version |
|-----|-----|
| ROCK | v2.10 |
| ROCR | v2.10 |
| HCC | v2.10 |
| Library | v2.10 |

**Comment by ekuznetsov139** [comment]
That stage always takes a very long time. Can take 20 minutes or longer.

**Comment by zjunweihit** [comment]
> That stage always takes a very long time. Can take 20 minutes or longer.

Thanks for your reply.
It stopped there for half a day.
Then I also check gpu status which has no working queue, gpu load is 0%.
check the process status, it's sleep "S+" from ps command.

I built blas 2.6 before, it didn't take too much time. And I can see progress for a while.
