### ISSUE TITLE
Issues building 2.10 from source on Arch Linux

### ISSUE THREAD

**Issue by ekuznetsov139** [ROCmSoftwarePlatform/rocBLAS#856]
I am attempting to build the ROCm 2.10 stack from source on Arch Linux. I've been able to do it previously with 2.6, but 2.10 refuses to cooperate. 

I had to deal with a number of problems, but I got through ROCT-ThunkInterface, ROCR-Runtime, ROCm-CompilerSupport, hcc, hip. But I'm having no luck with rocBLAS.

The first problem is that it assumes the existence of a number of ROCm executables and libraries in the wrong places. This includes, among others:
/opt/rocm/bin/hcc
/opt/rocm/lib/libhip_hcc.so 
/opt/rocm/bin/lpl
None of these files are put there by "make install" commands of hip & hcc. There are /opt/rocm/hcc/bin/hcc, /opt/rocm/hip/lib/libhip_hcc.so, etc. 

I do see symlinks in those locations on an Ubuntu system with a prepackaged ROCm install. I'm not sure who creates them, but their existence probably shouldn't be assumed.
It also assumes that hcc-config, hipconfig, extractkernel are in the PATH, which is unjustified.

After creating all missing symlinks I could find, I run into the following.

When building with 
CXX=/opt/rocm/hcc/bin/hcc cmake ..
or
CXX=/opt/rocm/bin/hcc cmake ..

cmake fails with

> CMake Error at /opt/rocm/hcc/lib/cmake/hcc/hcc-config.cmake:44 (add_library):
>   add_library cannot create imported target "hsa-runtime64" because another
>   target with the same name already exists.
> Call Stack (most recent call first):
>   /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
>   /opt/rocm/hip/lib/cmake/hip/hip-config.cmake:77 (find_dependency)
>   CMakeLists.txt:203 (find_package)
> 

This is caused by /opt/rocm/hcc/lib/cmake/hcc/hcc-config.cmake being included twice. I thought of adding "include_guard(GLOBAL)" to hcc-config.cmake, but that just results in a different error:

> Target "TensileHost" links to target "hcc::hccrt" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
> Target "TensileHost" links to target "hcc::hc_am" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?

This makes no sense to me at all, because I can see those targets in the cmake trace.

When building with

CXX=/opt/rocm/bin/hipcc cmake ..

I get

> 
> [zen@zenpc build]$ make 
> Scanning dependencies of target TensileHost
> [  1%] Building CXX object Tensile/lib/CMakeFiles/TensileHost.dir/source/AMDGPU.cpp.o
> In file included from /home/zen/rocm/rocBLAS/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/source/AMDGPU.cpp:27:
> In file included from /home/zen/rocm/rocBLAS/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/include/Tensile/AMDGPU.hpp:29:
> /home/zen/rocm/rocBLAS/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/include/Tensile/Tensile.hpp:55:9: error: virtual member function is not supported
>         virtual HIPCC_BUILD ~ProblemInputs();
>         ^
> 1 error generated.
> In file included from /home/zen/rocm/rocBLAS/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/source/AMDGPU.cpp:27:
> In file included from /home/zen/rocm/rocBLAS/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/include/Tensile/AMDGPU.hpp:29:
> /home/zen/rocm/rocBLAS/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/include/Tensile/Tensile.hpp:55:9: error: virtual member function is not supported
>         virtual HIPCC_BUILD ~ProblemInputs();
>         ^
> 1 error generated.
> make[2]: *** [Tensile/lib/CMakeFiles/TensileHost.dir/build.make:63: Tensile/lib/CMakeFiles/TensileHost.dir/source/AMDGPU.cpp.o] Error 1
> make[1]: *** [CMakeFiles/Makefile2:154: Tensile/lib/CMakeFiles/TensileHost.dir/all] Error 2
> 

Finally, when I try to use the provided install.sh script, after hacking it to not to throw an error because it does not know how to install prerequisite packages (I've installed them all manually), I get 

> 
> Compiling source kernels: Launching 16 threads...
> Unrecognised token: -D__HIP_HCC_COMPAT_MODE__
> Died at /opt/rocm/bin/hipcc line 360.
> Traceback (most recent call last):
>   File "/home/zen/rocm/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/Common.py", line 1194, in apply_print_exception
>     return func(*args)
>   File "/home/zen/rocm/rocBLAS/build/release/virtualenv/lib/python3.8/site-packages/Tensile/TensileCreateLibrary.py", line 165, in buildSourceCodeObjectFile
>     subprocess.check_call(compileArgs)
>   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/opt/rocm/bin/hipcc', '--genco', '-D__HIP_HCC_COMPAT_MODE__=1', '-I', '/home/zen/rocm/rocBLAS/build/release/Tensile', '--amdgpu-target=gfx803', '--amdgpu-target=gfx900', '--amdgpu-target=gfx906', '--amdgpu-target=gfx908', '/home/zen/rocm/rocBLAS/build/release/Tensile/Kernels.cpp', '-c', '-o', '/home/zen/rocm/rocBLAS/build/release/code_object_tmp/Kernels.so']' returned non-zero exit status 2.
> 

This is because Tensile here https://github.com/ROCmSoftwarePlatform/Tensile/blame/develop/Tensile/TensileCreateLibrary.py#L158 tries to launch hipcc with the command line options "--genco -D__HIP_HCC_COMPAT_MODE__=1", and these options are invalid (you can run "/opt/rocm/bin/hipcc --genco -D__HIP_HCC_COMPAT_MODE__=1" and no further options and it'll bail with the exact same error).

After puzzling over this, I tried to see if I can even build standalone Tensile, and I can't:

> 
> zen@zenpc build]$ CXX=/opt/rocm/bin/hipcc cmake ..
> -- The C compiler identification is GNU 9.2.0
> -- The CXX compiler identification is Clang 10.0.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /opt/rocm/bin/hipcc
> -- Check for working CXX compiler: /opt/rocm/bin/hipcc -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Processing hcc-config.cmake
> -- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_CXX: -fopenmp=libomp (found version "4.5") 
> -- Found OpenMP: TRUE (found version "4.5")  
> -- Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) 
> -- Found ROCmSMI: /opt/rocm/rocm_smi/lib/librocm_smi64.so  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/zen/rocm/Tensile/Tensile/Source/build
> [zen@zenpc build]$ make
> Scanning dependencies of target TensileHost
> [  3%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/AMDGPU.cpp.o
> In file included from /home/zen/rocm/Tensile/Tensile/Source/lib/source/AMDGPU.cpp:27:
> In file included from /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/AMDGPU.hpp:29:
> /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/Tensile.hpp:55:9: error: virtual member function is not supported
>         virtual HIPCC_BUILD ~ProblemInputs();
>         ^
> 1 error generated.
> 

> [zen@zenpc build]$ CXX=/opt/rocm/bin/hcc cmake ..
> -- The C compiler identification is GNU 9.2.0
> -- The CXX compiler identification is Clang 10.0.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /opt/rocm/bin/hcc
> -- Check for working CXX compiler: /opt/rocm/bin/hcc -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Processing hcc-config.cmake
> -- Found PkgConfig: /usr/bin/pkg-config (found version "1.6.3") 
> -- Found OpenMP_C: -fopenmp (found version "4.5") 
> -- Found OpenMP_CXX: -fopenmp=libomp (found version "4.5") 
> -- Found OpenMP: TRUE (found version "4.5")  
> -- Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options) 
> -- Found ROCmSMI: /opt/rocm/rocm_smi/lib/librocm_smi64.so  
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/zen/rocm/Tensile/Tensile/Source/build
> [zen@zenpc build]$ make
> Scanning dependencies of target TensileHost
> [  3%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/AMDGPU.cpp.o
> [  6%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/ContractionProblem.cpp.o
> [  9%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/ContractionSolution.cpp.o
> [ 12%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/DataTypes.cpp.o
> [ 16%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/Debug.cpp.o
> [ 19%] Building CXX object lib/CMakeFiles/TensileHost.dir/source/EmbeddedLibrary.cpp.o
> In file included from /home/zen/rocm/Tensile/Tensile/Source/lib/source/EmbeddedLibrary.cpp:29:
> In file included from /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/EmbeddedLibrary.hpp:32:
> /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/Singleton.hpp:39:26: error: call to implicitly-deleted default constructor of 'Tensile::EmbeddedData<Tensile::SolutionLibrary<Tensile::ContractionProblem, Tensile::ContractionSolution> >'
>             static Class instance;
>                          ^
> /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:62:39: note: in instantiation of member function 'Tensile::LazySingleton<Tensile::EmbeddedData<Tensile::SolutionLibrary<Tensile::ContractionProblem, Tensile::ContractionSolution> > >::Instance' requested here
>             auto const& items = Base::Instance().items;
>                                       ^
> /home/zen/rocm/Tensile/Tensile/Source/lib/source/EmbeddedLibrary.cpp:42:82: note: in instantiation of member function 'Tensile::EmbeddedData<Tensile::SolutionLibrary<Tensile::ContractionProblem, Tensile::ContractionSolution> >::Get' requested here
>         auto const& data = EmbeddedData<SolutionLibrary<MyProblem, MySolution>>::Get(key);
>                                                                                  ^
> /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:84:9: note: explicitly defaulted function was implicitly deleted here
>         EmbeddedData() = default;
>         ^
> /home/zen/rocm/Tensile/Tensile/Source/lib/include/Tensile/EmbeddedData.hpp:87:21: note: default constructor of 'EmbeddedData<Tensile::SolutionLibrary<Tensile::ContractionProblem, Tensile::ContractionSolution> >' is implicitly deleted because field 'empty' of const-qualified type 'const Tensile::EmbeddedData::Items' (aka 'const vector<vector<unsigned char> >') would not be initialized
>         const Items empty;
>                     ^
> 1 error generated.
> 

Any suggestions (apart from sticking to Ubuntu)?

**Comment by justxi** [comment]
You problem could be the same like this: https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/845

For general installation on Gentoo Linux (source based) you can find my ebuild here: https://github.com/justxi/rocm/blob/master/sci-libs/rocBLAS/rocBLAS-2.10.0.ebuild

**Comment by ekuznetsov139** [comment]
I have a partial explanation for my troubles.

Ubuntu 18.04 comes with CMake 3.10. Arch Linux comes with the latest version, which is 3.16. After downgrading to the oldest CMake still available in the Arch Linux archive (3.13), I've been able to get past "target with the same name already exists" and then run straight into #845 "call to implicitly-deleted default constructor".

@justxi  your proposed fix seems reasonable, but I don't understand why it's needed at all: I've confirmed that the same exact code compiles with no errors with hcc (clang-10) that is part of the "official" 2.10 Ubuntu package release. It is possible that the Ubuntu package was somehow built from a different tag vs. what we're building from. 

I'm going to try to build 2.10 hcc from source on Ubuntu and see if that one works.

**Comment by ekuznetsov139** [comment]
Ok, so the problem is somehow caused by a mismatch between the STL headers, specifically.

On both systems, hcc (clang) uses native STL headers from /usr/include/c++. On Ubuntu 18.04, they belong to gcc 7.4.0. On Arch Linux, they belong to gcc 9.2.0. With the headers from 7.4.0, everything compiles fine. With the headers from 9.2.0, with the same exact compiler binary, I get "implicitly-deleted default constructor".

**Comment by acxz** [comment]
@ekuznetsov139 the Arch AUR community has rocblas working now and the PKGBUILD is on the AUR. See https://github.com/rocm-arch/rocm-arch for more info. I believe this issue can be closed.
