### ISSUE TITLE
[Questions]-1.Enbale log Traces in Kerenel & API  2. Google Test Running test cases shown-0

### ISSUE THREAD

**Issue by anilbommareddy** [ROCmSoftwarePlatform/rocBLAS#908]
1.How to enable Traces(Printf) or log_traces in Kernel API(Inside gemvc_kernel()) Example: and Routine API(rocblas_status rocblas_gemv_impl())

Example1:
rocblas_status rocblas_gemv_impl() -->enabled Printf
rocblas_status gemvc_kernel( ) -- >Enable printf

[Run Binary from Build Directory] ./example-sgemm

Enable Printf traces not displayed 
Printf may be under development in Rocm
https://rocm-documentation.readthedocs.io/en/latest/Programming_Guides/HIP-GUIDE.html#printf

Example2:
export PATH=$PATH:/opt/rocm/bin
export LD_LIBRARY_PATH=/opt/rocm/rocblas/lib:$LD_LIBRARY_PATH
export ROCBLAS_LAYER=1
export ROCBLAS_LOG_TRACE_PATH=/home/user/rocBLAS/log_trace
[Run binary from Build Directory] ./example-sgemm  or ./rocblas-test 
Traces not displayed or Trace logging outputs  in directory log_trace

2. Google Test:
on Google test run shows   Running Test cases -0 . Kindly let me know correct command.

Example1:
/rocblas-test --gtest_filter=*checkin*gemm*float*-*batched*:*NaN*
rocBLAS version: 2.12.1.1749-rocm-rel-3.0-6-ca5535b

Query device success: there are 2 devices
-------------------------------------------------------------------------------
Device ID 0 : Vega 20
---

Note: Google Test filter = *checkin*gemm*float*-*batched*:*NaN*
[==========] Running 0 tests from 0 test cases.
[==========] 0 tests from 0 test cases ran. (56 ms total)
[  PASSED  ] 0 tests.

And also,I would like know is arguments can be pass in gtest_filter similar like  ./rocblas-bench -f gemm -r s -m 1024 -n 1024 -k 1024 --transposeB T -v 1
Kindly help me out on above questions

**Comment by bragadeesh** [comment]
Read about rocblas logging here: https://rocblas.readthedocs.io/en/master/logging.html
