### ISSUE TITLE
Undefined references 'rocblas_gemm_ex' and 'rocblas_gemm_strided_batched_ex' when trying to link with MIOpenDriver

### ISSUE THREAD

**Issue by darjankrijan** [ROCmSoftwarePlatform/rocBLAS#991]
### What is the expected behavior
'rocblas_gemm_ex' and 'rocblas_gemm_strided_batched_ex' being defined in librocblas.so

### What actually happens
'rocblas_gemm_ex' and 'rocblas_gemm_strided_batched_ex' are undefined in librocblas.so

### How to reproduce
Build rocBLAS with these build options:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocblas&id=7c9965639ddb3c7c578bffac3e3b58317f0022ab

And try to build MIOpen with these build options:
https://pastebin.com/vWwBmyiV

It then fails at "Linking CXX executable ../bin/MIOpenDriver" with "/opt/rocm/rocblas/rocblas/lib/librocblas.so.0.1" given on the command line:
```
ld: ../lib/libMIOpen.so.1: undefined reference to `rocblas_gemm_ex'
ld: ../lib/libMIOpen.so.1: undefined reference to `rocblas_gemm_strided_batched_ex'
```

### Environment
| Hardware | description |
|-----|-----|
| GPU | AMD Radeon VII |
| CPU | AMD Ryzen 9 3950x |

| Software | version |
|-----|-----|
| OS | Arch Linux |
| Upstream kernel driver | 5.5.2-arch1-1 |
| ROCR | v3.0 |
| HCC | v3.0 |
| Library | v3.0 |

Is Tensile necessary for these functions to be compiled? When trying to configure with 
```
-DBUILD_WITH_TENSILE=ON
```
 it throws a couple of python exceptions while doing so...

**Comment by darjankrijan** [comment]
Hello, is this maintained?

**Comment by amcamd** [comment]
Can you please try to remove the directive: -DBUILD_WITH_TENSILE=OFF  from your rocBLAS build options in the link

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=rocblas&id=7c9965639ddb3c7c578bffac3e3b58317f0022ab 

The default is to build with Tensile. If you build with Tensile the symbols rocblas_gemm_ex and rocblas_gemm_strided_batched_ex should be included in librocblas.sh.

**Comment by marcopompili** [comment]
I'm able to build rocBLAS 3.1 on Arch with Tensile and GCC9.

I had to set `Tensile_LOGIC=asm_full` and `Tensile_ARCHITECTURE=gfx900` for my configuration (RX Vega 64) to shorten the process of kernel generation because generating "all logics" would saturate my RAM (32GB). I don't now if my wording is correct, I'm not familiar with Tensile.

This is the `cmake` command I used on my PKGBUILD:
```
cmake -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/opt/rocm/rocblas \
      -HIP_DIR=/opt/rocm/hip/lib/cmake/hip \
      -hcc_DIR=/opt/rocm/hcc/lib/cmake/hcc \
      -Damd_comgr_DIR=/opt/rocm/lib/cmake/amd_comgr \
      -DTensile_ARCHITECTURE=gfx900 \
      -DTensile_LOGIC=asm_full \
      -DBUILD_WITH_TENSILE=ON \
      "$srcdir/rocBLAS-rocm-$_pkgver"
```

After `cmake` before launching `make` I had to apply this fix to build rocBLAS on GCC9: https://github.com/ROCmSoftwarePlatform/rocBLAS/issues/856

For now I built the PKGBUILD manually, and then repackage it using: `makepkg --repackage`, after installing rocBLAS I'm able to link MIOpen successfully.

**Comment by darjankrijan** [comment]
@marcopompili 
Good catch, I haven't checked the memory usage during building.
Should have known since another ROCm package would barely build with make -j4 on 32GB here (don't remember which).

This software stack sure is some fragile C++/Python bloat that breaks left and right.

**Comment by darjankrijan** [comment]
It still breaks for me with the same Python errors when trying something similar for my setup, some type mismatch... 

[rocblas_log.txt](https://github.com/ROCmSoftwarePlatform/rocBLAS/files/4399836/rocblas_log.txt)

My bet is another of these breaking Python changes between versions.

**Comment by s-bernard** [comment]
@darjankrijan You can fix these errors by putting hipconfig and extractkernel in the PATH, with a symbolic link for instance:
```
sudo ln -s /opt/rocm/hcc/bin/extractkernel /usr/bin/
sudo ln -s /opt/rocm/hip/bin/hipconfig /usr/bin/
```

**Comment by s-bernard** [comment]
Then I hit an compilation error: 
> rocblas/src/build/virtualenv/lib/python3.8/site-packages/Tensile/Source/lib/include/Tensile/llvm/YAML.hpp:249:36: error: no viable conversion from 'llvm::StringRef' to 'const std::string' (aka 'const basic_string<char>')
                Impl::inputOne(io, key, *value);

The solution is to change `key to key.str()` to be: `Impl::inputOne(io, key.str(), *value);`

Then it compiles fine (at least for me).

**Comment by darjankrijan** [comment]
@s-bernard 
Nice find, this runs through and compiles for me as well when adding the bin directory of HCC and HIP to the PATH environment variable and fixing that YAML.hpp C++ header.

Would have never found out since that Tensile part doesn't ever hint that some binary is missing, throwing type exceptions left and right.

And that C++ header is some softwaregore right there, good job finding the fix for that.
